export const Affixs = [
    { id: "hit1", name: "黄金之", affixType: "prefix", statId: "hit", lo: 0.5, hi: 1, loIlvlDelta: 0.12, hiIlvlDelta: 0.4, availOn: ["necklace", "charm", "ring"] },
    { id: "mhit1", name: "铂金之", affixType: "prefix", statId: "mhit", lo: 0.5, hi: 1, loIlvlDelta: 0.12, hiIlvlDelta: 0.4, availOn: ["necklace", "charm", "ring"] },
    { id: "xdmg1", name: "锋利之", affixType: "prefix", statId: "xdmg", lo: 3, hi: 7, loIlvlDelta: 7, hiIlvlDelta: 21, fluctuate: 0.15, availOn: ["necklace", "weapon", "charm", "ring"] },
    { id: "xdmg1rev", name: "锐利之", affixType: "prefix", statId: "xdmg", lo: 3, hi: 7, loIlvlDelta: 7, hiIlvlDelta: 21, fluctuate: 0.15, reversed: true, availOn: ["necklace", "weapon", "charm", "ring"] },
    { id: "fdmg1", name: "烟熏之", affixType: "prefix", statId: "fdmg", lo: 4, hi: 6, loIlvlDelta: 12, hiIlvlDelta: 16, fluctuate: 0.15, availOn: ["necklace", "weapon", "charm", "ring"] },
    { id: "tdmg1", name: "北风之", affixType: "prefix", statId: "tdmg", lo: 1, hi: 9, loIlvlDelta: 3, hiIlvlDelta: 25, fluctuate: 0.15, availOn: ["necklace", "weapon", "charm", "ring"] },
    { id: "hdmg1", name: "蜂鸣之", affixType: "prefix", statId: "hdmg", lo: 5, hi: 5, loIlvlDelta: 14, hiIlvlDelta: 14, fluctuate: 0.15, availOn: ["necklace", "weapon", "charm", "ring"] },
    { id: "pdmg1", name: "腐蚀之", affixType: "prefix", statId: "pdmg", lo: 0, hi: 10, loIlvlDelta: 0, hiIlvlDelta: 28, fluctuate: 0.15, availOn: ["necklace", "weapon", "charm", "ring"] },
    { id: "xed1", name: "残忍之", affixType: "prefix", statId: "xed", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace", "ring"] },
    { id: "fed1", name: "阴燃之", affixType: "prefix", statId: "fed", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace", "ring"] },
    { id: "ted1", name: "颤栗之", affixType: "prefix", statId: "ted", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace", "ring"] },
    { id: "hed1", name: "弧光之", affixType: "prefix", statId: "hed", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace", "ring"] },
    { id: "ped1", name: "剧毒之", affixType: "prefix", statId: "ped", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace", "ring"] },
    { id: "ued1", name: "光辉之", affixType: "prefix", statId: "ued", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace", "ring"] },
    { id: "ded1", name: "桃木之", affixType: "prefix", statId: "ded", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace", "ring"] },
    { id: "ced1", name: "克星之", affixType: "prefix", statId: "ced", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace", "ring"] },
    { id: "doted1", name: "折磨之", affixType: "prefix", statId: "doted", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace", "ring"] },
    { id: "hled1", name: "医者之", affixType: "prefix", statId: "hled", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace", "ring"] },
    { id: "xdr1", name: "钻石之", affixType: "prefix", statId: "xdr", lo: 0.7, hi: 2, loIlvlDelta: 1, hiIlvlDelta: 3, fluctuate: 0.15, availOn: ["necklace", "armor"] },
    { id: "fdr1", name: "红宝石之", affixType: "prefix", statId: "fdr", lo: 0.7, hi: 2, loIlvlDelta: 1, hiIlvlDelta: 3, fluctuate: 0.15, availOn: ["necklace", "armor"] },
    { id: "tdr1", name: "蓝宝石之", affixType: "prefix", statId: "tdr", lo: 0.7, hi: 2, loIlvlDelta: 1, hiIlvlDelta: 3, fluctuate: 0.15, availOn: ["necklace", "armor"] },
    { id: "hdr1", name: "黄宝石之", affixType: "prefix", statId: "hdr", lo: 0.7, hi: 2, loIlvlDelta: 1, hiIlvlDelta: 3, fluctuate: 0.15, availOn: ["necklace", "armor"] },
    { id: "pdr1", name: "绿宝石之", affixType: "prefix", statId: "pdr", lo: 0.7, hi: 2, loIlvlDelta: 1, hiIlvlDelta: 3, fluctuate: 0.15, availOn: ["necklace", "armor"] },
    { id: "xref1", name: "棘刺之", affixType: "prefix", statId: "xref", lo: 0.30000000000000004, hi: 1.05, loIlvlDelta: 0.7000000000000001, hiIlvlDelta: 3.15, availOn: ["necklace", "armor"] },
    { id: "fref1", name: "熔岩之", affixType: "prefix", statId: "fref", lo: 0.4, hi: 0.8999999999999999, loIlvlDelta: 1.2000000000000002, hiIlvlDelta: 2.4, availOn: ["necklace", "armor"] },
    { id: "tref1", name: "冰锥之", affixType: "prefix", statId: "tref", lo: 0.1, hi: 1.3499999999999999, loIlvlDelta: 0.30000000000000004, hiIlvlDelta: 3.75, availOn: ["necklace", "armor"] },
    { id: "href1", name: "结界之", affixType: "prefix", statId: "href", lo: 0.625, hi: 0.625, loIlvlDelta: 1.75, hiIlvlDelta: 1.75, availOn: ["necklace", "armor"] },
    { id: "pref1", name: "疫病之", affixType: "prefix", statId: "pref", lo: 0, hi: 1.5, loIlvlDelta: 0, hiIlvlDelta: 4.2, availOn: ["necklace", "armor"] },
    { id: "maxhp1", name: "猛犸之", affixType: "prefix", statId: "maxhp", lo: 3, hi: 5, loIlvlDelta: 6, hiIlvlDelta: 20, availOn: ["necklace", "armor", "ring"] },
    { id: "maxmp1", name: "灵狐之", affixType: "prefix", statId: "maxmp", lo: 3, hi: 5, loIlvlDelta: 6, hiIlvlDelta: 20, availOn: ["necklace", "armor", "ring"] },
    { id: "sumreg1", name: "德鲁伊之", affixType: "prefix", statId: "sumreg", lo: 2, hi: 10, loIlvlDelta: 5, hiIlvlDelta: 22.5, availOn: ["necklace", "armor", "ring"] },
    { id: "xres1", name: "灰白之", affixType: "prefix", statId: "xres", lo: 5, hi: 10, loIlvlDelta: 1.2, hiIlvlDelta: 2.4, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "fres1", name: "猩红之", affixType: "prefix", statId: "fres", lo: 10, hi: 20, loIlvlDelta: 2.5, hiIlvlDelta: 5, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "tres1", name: "深蓝之", affixType: "prefix", statId: "tres", lo: 10, hi: 20, loIlvlDelta: 2.5, hiIlvlDelta: 5, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "hres1", name: "橘黄之", affixType: "prefix", statId: "hres", lo: 10, hi: 20, loIlvlDelta: 2.5, hiIlvlDelta: 5, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "pres1", name: "青绿之", affixType: "prefix", statId: "pres", lo: 10, hi: 20, loIlvlDelta: 2.5, hiIlvlDelta: 5, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "mxxres1", name: "壁垒之", affixType: "prefix", statId: "mxxres", lo: 1, hi: 3, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "mxfres1", name: "熔炉之", affixType: "prefix", statId: "mxfres", lo: 1, hi: 3, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "mxtres1", name: "要塞之", affixType: "prefix", statId: "mxtres", lo: 1, hi: 3, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "mxhres1", name: "教堂之", affixType: "prefix", statId: "mxhres", lo: 1, hi: 3, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "mxpres1", name: "堡垒之", affixType: "prefix", statId: "mxpres", lo: 1, hi: 3, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "ures1", name: "亡者之", affixType: "prefix", statId: "ures", lo: 5, hi: 10, loIlvlDelta: 0.5, hiIlvlDelta: 2, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "dres1", name: "妖魔之", affixType: "prefix", statId: "dres", lo: 5, hi: 10, loIlvlDelta: 0.5, hiIlvlDelta: 2, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "cres1", name: "精英之", affixType: "prefix", statId: "cres", lo: 5, hi: 10, loIlvlDelta: 0.5, hiIlvlDelta: 2, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "c1res1", name: "勇士之", affixType: "prefix", statId: "c1res", lo: 5, hi: 10, loIlvlDelta: 0.5, hiIlvlDelta: 2, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "c23res1", name: "战术之", affixType: "prefix", statId: "c23res", lo: 5, hi: 10, loIlvlDelta: 0.5, hiIlvlDelta: 2, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "dotres1", name: "忍耐之", affixType: "prefix", statId: "dotres", lo: 5, hi: 10, loIlvlDelta: 0.5, hiIlvlDelta: 2, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "sumres1", name: "驯兽师之", affixType: "prefix", statId: "sumres", lo: 5, hi: 15, loIlvlDelta: 0.5, hiIlvlDelta: 4, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "flvl1", name: "烈焰之", affixType: "prefix", statId: "flvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "tlvl1", name: "冰冻之", affixType: "prefix", statId: "tlvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "flvlmage1", name: "火山之", affixType: "prefix", statId: "flvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "charm"] },
    { id: "tlvlmage1", name: "冰川之", affixType: "prefix", statId: "tlvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "charm"] },
    { id: "magelvl1", name: "法神之", affixType: "prefix", statId: "magelvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "blvl1", name: "愤怒之", affixType: "prefix", statId: "blvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "xlvl1", name: "老兵之", affixType: "prefix", statId: "xlvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "blvlwarr1", name: "狂战士之", affixType: "prefix", statId: "blvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "charm"] },
    { id: "xlvlwarr1", name: "统帅之", affixType: "prefix", statId: "xlvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "charm"] },
    { id: "warrlvl1", name: "战神之", affixType: "prefix", statId: "warrlvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "hlvl1", name: "传教士之", affixType: "prefix", statId: "hlvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "plvl1", name: "上古之", affixType: "prefix", statId: "plvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "hlvlwlok1", name: "牧师之", affixType: "prefix", statId: "hlvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "charm"] },
    { id: "plvlwlok1", name: "始祖之", affixType: "prefix", statId: "plvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "charm"] },
    { id: "wlklvl1", name: "天尊之", affixType: "prefix", statId: "wlklvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "alvl1", name: "精通之", affixType: "prefix", statId: "alvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.25, availOn: ["necklace"] },
    { id: "slvl1", name: "灵感之", affixType: "prefix", statId: "slvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "glvl1", name: "角斗士之", affixType: "prefix", statId: "glvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "luck1", name: "运气之", affixType: "prefix", statId: "luck", lo: 3, hi: 10, loIlvlDelta: 1, hiIlvlDelta: 7.5, availOn: ["necklace", "armor", "charm"] },
    { id: "eg1", name: "财富之", affixType: "prefix", statId: "eg", lo: 10, hi: 30, loIlvlDelta: 5, hiIlvlDelta: 20, availOn: ["necklace", "armor", "charm"] },
    { id: "sok1", name: "初学者之", affixType: "prefix", statId: "sok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0, availOn: ["belt", "necklace", "ring"] },
    { id: "sok2", name: "学徒之", affixType: "prefix", statId: "sok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.25, availOn: ["boot", "glove", "pauldron", "weapon", "bracelet"] },
    { id: "sok3", name: "技工之", affixType: "prefix", statId: "sok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["helm", "pant", "weapon"] },
    { id: "sok4", name: "专家之", affixType: "prefix", statId: "sok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.75, availOn: ["armor", "weapon"] },
    { id: "sok5", name: "大师之", affixType: "prefix", statId: "sok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 1, availOn: ["weapon"] },
    { id: "rw1", name: "五行的", affixType: "suffix", statId: "rw", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0, availOn: ["armor", "belt", "boot", "glove", "helm", "necklace", "pant", "pauldron", "ring", "weapon", "bracelet"] },
    { id: "mhex1", name: "巨鲸的", affixType: "suffix", statId: "mhex", lo: 5, hi: 10, loIlvlDelta: 0, hiIlvlDelta: 5, availOn: ["necklace", "armor", "ring"] },
    { id: "mpex", name: "古龙的", affixType: "suffix", statId: "mpex", lo: 5, hi: 10, loIlvlDelta: 0, hiIlvlDelta: 5, availOn: ["necklace", "armor", "ring"] },
    { id: "hreg1", name: "巨魔的", affixType: "suffix", statId: "hreg", lo: 1, hi: 5, loIlvlDelta: 2, hiIlvlDelta: 6, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "mreg1", name: "精灵的", affixType: "suffix", statId: "mreg", lo: 2, hi: 7, loIlvlDelta: 3, hiIlvlDelta: 10, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "spd1", name: "快速的", affixType: "suffix", statId: "spd", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0, availOn: ["necklace", "ring"] },
    { id: "doge1", name: "迅捷的", affixType: "suffix", statId: "doge", lo: 0.5, hi: 1, loIlvlDelta: 0.12, hiIlvlDelta: 0.4, availOn: ["necklace", "armor", "ring"] },
    { id: "mdoge1", name: "绝缘的", affixType: "suffix", statId: "mdoge", lo: 0.5, hi: 1, loIlvlDelta: 0.12, hiIlvlDelta: 0.4, availOn: ["necklace", "armor", "ring"] },
    { id: "crit1", name: "弱点的", affixType: "suffix", statId: "crit", lo: 1, hi: 2, loIlvlDelta: 0.1, hiIlvlDelta: 1.5, availOn: ["necklace", "ring"] },
    { id: "critd1", name: "屠杀的", affixType: "suffix", statId: "critd", lo: 20, hi: 40, loIlvlDelta: 5, hiIlvlDelta: 50, availOn: ["necklace", "ring"] },
    { id: "scrit1", name: "迷信的", affixType: "suffix", statId: "scrit", lo: 1, hi: 2, loIlvlDelta: 0.1, hiIlvlDelta: 1.5, availOn: ["necklace", "ring"] },
    { id: "scritd1", name: "愚者的", affixType: "suffix", statId: "scritd", lo: 20, hi: 40, loIlvlDelta: 5, hiIlvlDelta: 50, availOn: ["necklace", "ring"] },
    { id: "str1", name: "力量的", affixType: "suffix", statId: "str", lo: 1, hi: 4, loIlvlDelta: 2, hiIlvlDelta: 24, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "int1", name: "智慧的", affixType: "suffix", statId: "int", lo: 1, hi: 4, loIlvlDelta: 2, hiIlvlDelta: 24, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "spi1", name: "精神的", affixType: "suffix", statId: "spi", lo: 1, hi: 4, loIlvlDelta: 2, hiIlvlDelta: 24, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "vit1", name: "活力的", affixType: "suffix", statId: "vit", lo: 1, hi: 4, loIlvlDelta: 2, hiIlvlDelta: 24, availOn: ["necklace", "armor", "charm", "ring"] },
    { id: "ll1", name: "吸血鬼的", affixType: "suffix", statId: "ll", lo: 0.5, hi: 1, loIlvlDelta: 0.5, hiIlvlDelta: 1, availOn: ["necklace", "ring"] },
    { id: "ml1", name: "魅魔的", affixType: "suffix", statId: "ml", lo: 0.5, hi: 1, loIlvlDelta: 0.5, hiIlvlDelta: 1, availOn: ["necklace", "ring"] },
    { id: "skfbltmage1", name: "火球的", affixType: "suffix", statId: "skfbltmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skfrngmage1", name: "火环的", affixType: "suffix", statId: "skfrngmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skfinfmage1", name: "地狱火的", affixType: "suffix", statId: "skfinfmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skfbalmage1", name: "大火球的", affixType: "suffix", statId: "skfbalmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skfblsmage1", name: "烈焰的", affixType: "suffix", statId: "skfblsmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skfwalmage1", name: "火墙的", affixType: "suffix", statId: "skfwalmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "sktchmmage1", name: "诱惑的", affixType: "suffix", statId: "sktchmmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "sktbltmage1", name: "雷电的", affixType: "suffix", statId: "sktbltmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "sktltnmage1", name: "疾光的", affixType: "suffix", statId: "sktltnmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "sktnovmage1", name: "雷光的", affixType: "suffix", statId: "sktnovmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "sktshdmage1", name: "魔法盾的", affixType: "suffix", statId: "sktshdmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "sktblzmage1", name: "冰咆哮的", affixType: "suffix", statId: "sktblzmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skbbaswarr1", name: "基础的", affixType: "suffix", statId: "skbbaswarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skbcrtwarr1", name: "攻杀的", affixType: "suffix", statId: "skbcrtwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skbthrwarr1", name: "刺杀的", affixType: "suffix", statId: "skbthrwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skbclvwarr1", name: "半月的", affixType: "suffix", statId: "skbclvwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skbcrzwarr1", name: "十字的", affixType: "suffix", statId: "skbcrzwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skbfblwarr1", name: "烈火的", affixType: "suffix", statId: "skbfblwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skxdefwarr1", name: "铁布衫的", affixType: "suffix", statId: "skxdefwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skxdogwarr1", name: "猎犬的", affixType: "suffix", statId: "skxdogwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skxctawarr1", name: "狂战的", affixType: "suffix", statId: "skxctawarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skxwmswarr1", name: "龙皮的", affixType: "suffix", statId: "skxwmswarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skxchgwarr1", name: "野蛮的", affixType: "suffix", statId: "skxchgwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skxtstwarr1", name: "霜冻踏地的", affixType: "suffix", statId: "skxtstwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skhhelwlok1", name: "治愈的", affixType: "suffix", statId: "skhhelwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skhgsdwlok1", name: "幽灵盾的", affixType: "suffix", statId: "skhgsdwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skhinvwlok1", name: "隐身的", affixType: "suffix", statId: "skhinvwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skhhsdwlok1", name: "圣甲的", affixType: "suffix", statId: "skhhsdwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skhlokwlok1", name: "困魔的", affixType: "suffix", statId: "skhlokwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skhmhlwlok1", name: "责难的", affixType: "suffix", statId: "skhmhlwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skpbaswlok1", name: "精神力的", affixType: "suffix", statId: "skpbaswlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skppoiwlok1", name: "施毒的", affixType: "suffix", statId: "skppoiwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skpsklwlok1", name: "骷髅的", affixType: "suffix", statId: "skpsklwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skprunwlok1", name: "火符的", affixType: "suffix", statId: "skprunwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skpcblwlok1", name: "降魔的", affixType: "suffix", statId: "skpcblwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "skpsdmwlok1", name: "神兽的", affixType: "suffix", statId: "skpsdmwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace", "ring"] },
    { id: "atkfblt1", name: "火球术的", affixType: "suffix", statId: "procatk", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "fblt", skillChance: [0.03, 0.15], availOn: ["necklace", "ring"] },
    { id: "atkfbal1", name: "大火球术的", affixType: "suffix", statId: "procatk", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "fbal", skillChance: [0.03, 0.15], availOn: ["necklace", "ring"] },
    { id: "atktblt1", name: "雷电术的", affixType: "suffix", statId: "procatk", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "tblt", skillChance: [0.03, 0.15], availOn: ["necklace", "ring"] },
    { id: "atkpcbl1", name: "降魔术的", affixType: "suffix", statId: "procatk", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "pcbl", skillChance: [0.03, 0.15], availOn: ["necklace", "ring"] },
    { id: "hitfrng1", name: "火环术的", affixType: "suffix", statId: "prochit", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "frng", skillChance: [0.03, 0.15], availOn: ["necklace", "armor", "ring"] },
    { id: "atktnov1", name: "雷光术的", affixType: "suffix", statId: "prochit", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "tnov", skillChance: [0.03, 0.15], availOn: ["necklace", "armor", "ring"] },
    { id: "atkhhel1", name: "治愈术的", affixType: "suffix", statId: "prochit", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "hhel", skillChance: [0.03, 0.15], availOn: ["necklace", "armor", "ring"] },
    { id: "hithinv1", name: "隐身术的", affixType: "suffix", statId: "prochit", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "hinv", skillChance: [0.03, 0.15], availOn: ["necklace", "armor", "ring"] },
    { id: "curs1", name: "诅咒的", affixType: "suffix", statId: "curs", lo: 1, hi: 10, loIlvlDelta: 0, hiIlvlDelta: 1.25, availOn: ["necklace", "ring"] },
    { id: "bles1", name: "祝福的", affixType: "suffix", statId: "bles", lo: 1, hi: 10, loIlvlDelta: 0, hiIlvlDelta: 1.25, availOn: ["necklace", "ring"] },
    { id: "moral1", name: "士气的", affixType: "suffix", statId: "moral", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.25, availOn: ["necklace", "ring"] },
    { id: "cb1", name: "粉碎的", affixType: "suffix", statId: "cb", lo: 1, hi: 5, loIlvlDelta: 0, hiIlvlDelta: 1.25 },
    { id: "pmh1", name: "恶毒的", affixType: "suffix", statId: "pmh", lo: 5, hi: 15, loIlvlDelta: 1.25, hiIlvlDelta: 8.75, availOn: ["necklace"] },
    { id: "xlr1", name: "破甲的", affixType: "suffix", statId: "xlr", lo: 2.5, hi: 5, loIlvlDelta: 0.625, hiIlvlDelta: 1.25 },
    { id: "flr1", name: "助燃的", affixType: "suffix", statId: "flr", lo: 5, hi: 10, loIlvlDelta: 1.25, hiIlvlDelta: 2.5 },
    { id: "tlr1", name: "伤寒的", affixType: "suffix", statId: "tlr", lo: 5, hi: 10, loIlvlDelta: 1.25, hiIlvlDelta: 2.5 },
    { id: "hlr1", name: "定罪的", affixType: "suffix", statId: "hlr", lo: 5, hi: 10, loIlvlDelta: 1.25, hiIlvlDelta: 2.5 },
    { id: "plr1", name: "虚弱的", affixType: "suffix", statId: "plr", lo: 5, hi: 10, loIlvlDelta: 1.25, hiIlvlDelta: 2.5 },
    { id: "skfblt1", name: "skfblt", affixType: "suffix", statId: "skfblt", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skfrng1", name: "skfrng", affixType: "suffix", statId: "skfrng", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skfinf1", name: "skfinf", affixType: "suffix", statId: "skfinf", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skfbal1", name: "skfbal", affixType: "suffix", statId: "skfbal", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skfbls1", name: "skfbls", affixType: "suffix", statId: "skfbls", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skfwal1", name: "skfwal", affixType: "suffix", statId: "skfwal", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "sktchm1", name: "sktchm", affixType: "suffix", statId: "sktchm", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "sktblt1", name: "sktblt", affixType: "suffix", statId: "sktblt", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "sktltn1", name: "sktltn", affixType: "suffix", statId: "sktltn", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "sktnov1", name: "sktnov", affixType: "suffix", statId: "sktnov", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "sktshd1", name: "sktshd", affixType: "suffix", statId: "sktshd", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "sktblz1", name: "sktblz", affixType: "suffix", statId: "sktblz", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skbbas1", name: "skbbas", affixType: "suffix", statId: "skbbas", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skbcrt1", name: "skbcrt", affixType: "suffix", statId: "skbcrt", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skbthr1", name: "skbthr", affixType: "suffix", statId: "skbthr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skbclv1", name: "skbclv", affixType: "suffix", statId: "skbclv", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skbcrz1", name: "skbcrz", affixType: "suffix", statId: "skbcrz", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skbfbl1", name: "skbfbl", affixType: "suffix", statId: "skbfbl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skxdef1", name: "skxdef", affixType: "suffix", statId: "skxdef", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skxdog1", name: "skxdog", affixType: "suffix", statId: "skxdog", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skxcta1", name: "skxcta", affixType: "suffix", statId: "skxcta", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skxwms1", name: "skxwms", affixType: "suffix", statId: "skxwms", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skxchg1", name: "skxchg", affixType: "suffix", statId: "skxchg", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skxtst1", name: "skxtst", affixType: "suffix", statId: "skxtst", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skhhel1", name: "skhhel", affixType: "suffix", statId: "skhhel", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skhgsd1", name: "skhgsd", affixType: "suffix", statId: "skhgsd", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skhinv1", name: "skhinv", affixType: "suffix", statId: "skhinv", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skhhsd1", name: "skhhsd", affixType: "suffix", statId: "skhhsd", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skhlok1", name: "skhlok", affixType: "suffix", statId: "skhlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skhmhl1", name: "skhmhl", affixType: "suffix", statId: "skhmhl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skpbas1", name: "skpbas", affixType: "suffix", statId: "skpbas", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skppoi1", name: "skppoi", affixType: "suffix", statId: "skppoi", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skpskl1", name: "skpskl", affixType: "suffix", statId: "skpskl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skprun1", name: "skprun", affixType: "suffix", statId: "skprun", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skpcbl1", name: "skpcbl", affixType: "suffix", statId: "skpcbl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skpsdm1", name: "skpsdm", affixType: "suffix", statId: "skpsdm", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "setwargod", name: "setwargod", affixType: "suffix", statId: "setwargod", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setmara", name: "setmara", affixType: "suffix", statId: "setmara", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setjihad", name: "setjihad", affixType: "suffix", statId: "setjihad", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setghost", name: "setghost", affixType: "suffix", statId: "setghost", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setvenerable", name: "setvenerable", affixType: "suffix", statId: "setvenerable", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setmaster", name: "setmaster", affixType: "suffix", statId: "setmaster", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setdemon", name: "setdemon", affixType: "suffix", statId: "setdemon", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setmagegod", name: "setmagegod", affixType: "suffix", statId: "setmagegod", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setcolorful", name: "setcolorful", affixType: "suffix", statId: "setcolorful", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setblackiron", name: "setblackiron", affixType: "suffix", statId: "setblackiron", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setmysterious", name: "setmysterious", affixType: "suffix", statId: "setmysterious", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setmemory", name: "setmemory", affixType: "suffix", statId: "setmemory", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setvoma", name: "setvoma", affixType: "suffix", statId: "setvoma", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setzuma", name: "setzuma", affixType: "suffix", statId: "setzuma", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setredmoon", name: "setredmoon", affixType: "suffix", statId: "setredmoon", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setprisma", name: "setprisma", affixType: "suffix", statId: "setprisma", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setdragon", name: "setdragon", affixType: "suffix", statId: "setdragon", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setempire", name: "setempire", affixType: "suffix", statId: "setempire", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
];

export const AffixById = Object.fromEntries(Affixs.map(e => [e.id, e]));
export const AffixGroupByAvailOn = Affixs.reduce((acc, e) => {
    if (e.availOn != null) {
        e.availOn.forEach(group => {
            if (!acc[group]) {
                acc[group] = [];
            }
            acc[group].push(e);
        })
    }
    return acc;
}, {})
