export const Affixs = [
    { id: "hit1", affixType: "prefix", statId: "hit", lo: 0.5, hi: 1, loIlvlDelta: 0.12, hiIlvlDelta: 0.4, availOn: ["necklace"] },
    { id: "mhit1", affixType: "prefix", statId: "mhit", lo: 0.5, hi: 1, loIlvlDelta: 0.12, hiIlvlDelta: 0.4, availOn: ["necklace"] },
    { id: "xdmg1", affixType: "prefix", statId: "xdmg", lo: 3, hi: 7, loIlvlDelta: 7, hiIlvlDelta: 21, fluctuate: 0.15, availOn: ["necklace", "weapon"] },
    { id: "xdmg1rev", affixType: "prefix", statId: "xdmg", lo: 3, hi: 7, loIlvlDelta: 7, hiIlvlDelta: 21, fluctuate: 0.15, reversed: true, availOn: ["necklace", "weapon"] },
    { id: "fdmg1", affixType: "prefix", statId: "fdmg", lo: 4, hi: 6, loIlvlDelta: 12, hiIlvlDelta: 16, fluctuate: 0.15, availOn: ["necklace", "weapon"] },
    { id: "tdmg1", affixType: "prefix", statId: "tdmg", lo: 1, hi: 9, loIlvlDelta: 3, hiIlvlDelta: 25, fluctuate: 0.15, availOn: ["necklace", "weapon"] },
    { id: "hdmg1", affixType: "prefix", statId: "hdmg", lo: 5, hi: 5, loIlvlDelta: 14, hiIlvlDelta: 14, fluctuate: 0.15, availOn: ["necklace", "weapon"] },
    { id: "pdmg1", affixType: "prefix", statId: "pdmg", lo: 0, hi: 10, loIlvlDelta: 0, hiIlvlDelta: 28, fluctuate: 0.15, availOn: ["necklace", "weapon"] },
    { id: "xed1", affixType: "prefix", statId: "xed", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace"] },
    { id: "fed1", affixType: "prefix", statId: "fed", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace"] },
    { id: "ted1", affixType: "prefix", statId: "ted", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace"] },
    { id: "hed1", affixType: "prefix", statId: "hed", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace"] },
    { id: "ped1", affixType: "prefix", statId: "ped", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace"] },
    { id: "ued1", affixType: "prefix", statId: "ued", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace"] },
    { id: "ded1", affixType: "prefix", statId: "ded", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace"] },
    { id: "ced1", affixType: "prefix", statId: "ced", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace"] },
    { id: "doted1", affixType: "prefix", statId: "doted", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace"] },
    { id: "hled1", affixType: "prefix", statId: "hled", lo: 10, hi: 50, loIlvlDelta: 15, hiIlvlDelta: 75, availOn: ["necklace"] },
    { id: "xdr1", affixType: "prefix", statId: "xdr", lo: 0.7, hi: 2, loIlvlDelta: 1, hiIlvlDelta: 3, fluctuate: 0.15, availOn: ["necklace"] },
    { id: "fdr1", affixType: "prefix", statId: "fdr", lo: 0.7, hi: 2, loIlvlDelta: 1, hiIlvlDelta: 3, fluctuate: 0.15, availOn: ["necklace"] },
    { id: "tdr1", affixType: "prefix", statId: "tdr", lo: 0.7, hi: 2, loIlvlDelta: 1, hiIlvlDelta: 3, fluctuate: 0.15, availOn: ["necklace"] },
    { id: "hdr1", affixType: "prefix", statId: "hdr", lo: 0.7, hi: 2, loIlvlDelta: 1, hiIlvlDelta: 3, fluctuate: 0.15, availOn: ["necklace"] },
    { id: "pdr1", affixType: "prefix", statId: "pdr", lo: 0.7, hi: 2, loIlvlDelta: 1, hiIlvlDelta: 3, fluctuate: 0.15, availOn: ["necklace"] },
    { id: "xref1", affixType: "prefix", statId: "xref", lo: 0.30000000000000004, hi: 1.05, loIlvlDelta: 0.7000000000000001, hiIlvlDelta: 3.15, availOn: ["necklace"] },
    { id: "fref1", affixType: "prefix", statId: "fref", lo: 0.4, hi: 0.8999999999999999, loIlvlDelta: 1.2000000000000002, hiIlvlDelta: 2.4, availOn: ["necklace"] },
    { id: "tref1", affixType: "prefix", statId: "tref", lo: 0.1, hi: 1.3499999999999999, loIlvlDelta: 0.30000000000000004, hiIlvlDelta: 3.75, availOn: ["necklace"] },
    { id: "href1", affixType: "prefix", statId: "href", lo: 0.625, hi: 0.625, loIlvlDelta: 1.75, hiIlvlDelta: 1.75, availOn: ["necklace"] },
    { id: "pref1", affixType: "prefix", statId: "pref", lo: 0, hi: 1.5, loIlvlDelta: 0, hiIlvlDelta: 4.2, availOn: ["necklace"] },
    { id: "maxhp1", affixType: "prefix", statId: "maxhp", lo: 3, hi: 5, loIlvlDelta: 6, hiIlvlDelta: 20, availOn: ["necklace"] },
    { id: "maxmp1", affixType: "prefix", statId: "maxmp", lo: 3, hi: 5, loIlvlDelta: 6, hiIlvlDelta: 20, availOn: ["necklace"] },
    { id: "sumreg1", affixType: "prefix", statId: "sumreg", lo: 2, hi: 10, loIlvlDelta: 5, hiIlvlDelta: 22.5, availOn: ["necklace"] },
    { id: "xres1", affixType: "prefix", statId: "xres", lo: 5, hi: 10, loIlvlDelta: 1.2, hiIlvlDelta: 2.4, availOn: ["necklace"] },
    { id: "fres1", affixType: "prefix", statId: "fres", lo: 10, hi: 20, loIlvlDelta: 2.5, hiIlvlDelta: 5, availOn: ["necklace"] },
    { id: "tres1", affixType: "prefix", statId: "tres", lo: 10, hi: 20, loIlvlDelta: 2.5, hiIlvlDelta: 5, availOn: ["necklace"] },
    { id: "hres1", affixType: "prefix", statId: "hres", lo: 10, hi: 20, loIlvlDelta: 2.5, hiIlvlDelta: 5, availOn: ["necklace"] },
    { id: "pres1", affixType: "prefix", statId: "pres", lo: 10, hi: 20, loIlvlDelta: 2.5, hiIlvlDelta: 5, availOn: ["necklace"] },
    { id: "mxxres1", affixType: "prefix", statId: "mxxres", lo: 1, hi: 3, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "mxfres1", affixType: "prefix", statId: "mxfres", lo: 1, hi: 3, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "mxtres1", affixType: "prefix", statId: "mxtres", lo: 1, hi: 3, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "mxhres1", affixType: "prefix", statId: "mxhres", lo: 1, hi: 3, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "mxpres1", affixType: "prefix", statId: "mxpres", lo: 1, hi: 3, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "ures1", affixType: "prefix", statId: "ures", lo: 5, hi: 10, loIlvlDelta: 0.5, hiIlvlDelta: 2, availOn: ["necklace"] },
    { id: "dres1", affixType: "prefix", statId: "dres", lo: 5, hi: 10, loIlvlDelta: 0.5, hiIlvlDelta: 2, availOn: ["necklace"] },
    { id: "cres1", affixType: "prefix", statId: "cres", lo: 5, hi: 10, loIlvlDelta: 0.5, hiIlvlDelta: 2, availOn: ["necklace"] },
    { id: "c1res1", affixType: "prefix", statId: "c1res", lo: 5, hi: 10, loIlvlDelta: 0.5, hiIlvlDelta: 2, availOn: ["necklace"] },
    { id: "c23res1", affixType: "prefix", statId: "c23res", lo: 5, hi: 10, loIlvlDelta: 0.5, hiIlvlDelta: 2, availOn: ["necklace"] },
    { id: "dotres1", affixType: "prefix", statId: "dotres", lo: 5, hi: 10, loIlvlDelta: 0.5, hiIlvlDelta: 2, availOn: ["necklace"] },
    { id: "sumres1", affixType: "prefix", statId: "sumres", lo: 5, hi: 15, loIlvlDelta: 0.5, hiIlvlDelta: 4, availOn: ["necklace"] },
    { id: "flvl1", affixType: "prefix", statId: "flvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "tlvl1", affixType: "prefix", statId: "tlvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "magelvl1", affixType: "prefix", statId: "magelvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "blvl1", affixType: "prefix", statId: "blvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "xlvl1", affixType: "prefix", statId: "xlvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "warrlvl1", affixType: "prefix", statId: "warrlvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "hlvl1", affixType: "prefix", statId: "hlvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "plvl1", affixType: "prefix", statId: "plvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "wlklvl1", affixType: "prefix", statId: "wlklvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "alvl1", affixType: "prefix", statId: "alvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.25, availOn: ["necklace"] },
    { id: "slvl1", affixType: "prefix", statId: "slvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "glvl1", affixType: "prefix", statId: "glvl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "luck1", affixType: "prefix", statId: "luck", lo: 3, hi: 10, loIlvlDelta: 1, hiIlvlDelta: 7.5, availOn: ["necklace"] },
    { id: "eg1", affixType: "prefix", statId: "eg", lo: 10, hi: 30, loIlvlDelta: 5, hiIlvlDelta: 20, availOn: ["necklace"] },
    { id: "sok1", affixType: "prefix", statId: "sok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0, availOn: ["necklace"] },
    { id: "sok2", affixType: "prefix", statId: "sok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.25 },
    { id: "sok3", affixType: "prefix", statId: "sok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "sok4", affixType: "prefix", statId: "sok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.75 },
    { id: "sok5", affixType: "prefix", statId: "sok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 1 },
    { id: "rw1", affixType: "suffix", statId: "rw", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "mhex1", affixType: "suffix", statId: "mhex", lo: 5, hi: 10, loIlvlDelta: 0, hiIlvlDelta: 5, availOn: ["necklace"] },
    { id: "mpex", affixType: "suffix", statId: "mpex", lo: 5, hi: 10, loIlvlDelta: 0, hiIlvlDelta: 5, availOn: ["necklace"] },
    { id: "hreg1", affixType: "suffix", statId: "hreg", lo: 1, hi: 5, loIlvlDelta: 2, hiIlvlDelta: 6, availOn: ["necklace"] },
    { id: "mreg1", affixType: "suffix", statId: "mreg", lo: 2, hi: 7, loIlvlDelta: 3, hiIlvlDelta: 10, availOn: ["necklace"] },
    { id: "spd1", affixType: "suffix", statId: "spd", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0, availOn: ["necklace"] },
    { id: "doge1", affixType: "suffix", statId: "doge", lo: 0.5, hi: 1, loIlvlDelta: 0.12, hiIlvlDelta: 0.4, availOn: ["necklace"] },
    { id: "mdoge1", affixType: "suffix", statId: "mdoge", lo: 0.5, hi: 1, loIlvlDelta: 0.12, hiIlvlDelta: 0.4, availOn: ["necklace"] },
    { id: "crit1", affixType: "suffix", statId: "crit", lo: 1, hi: 2, loIlvlDelta: 0.1, hiIlvlDelta: 1.5, availOn: ["necklace"] },
    { id: "critd1", affixType: "suffix", statId: "critd", lo: 20, hi: 40, loIlvlDelta: 5, hiIlvlDelta: 50, availOn: ["necklace"] },
    { id: "scrit1", affixType: "suffix", statId: "scrit", lo: 1, hi: 2, loIlvlDelta: 0.1, hiIlvlDelta: 1.5, availOn: ["necklace"] },
    { id: "scritd1", affixType: "suffix", statId: "scritd", lo: 20, hi: 40, loIlvlDelta: 5, hiIlvlDelta: 50, availOn: ["necklace"] },
    { id: "str1", affixType: "suffix", statId: "str", lo: 1, hi: 4, loIlvlDelta: 2, hiIlvlDelta: 24, availOn: ["necklace"] },
    { id: "int1", affixType: "suffix", statId: "int", lo: 1, hi: 4, loIlvlDelta: 2, hiIlvlDelta: 24, availOn: ["necklace"] },
    { id: "spi1", affixType: "suffix", statId: "spi", lo: 1, hi: 4, loIlvlDelta: 2, hiIlvlDelta: 24, availOn: ["necklace"] },
    { id: "vit1", affixType: "suffix", statId: "vit", lo: 1, hi: 4, loIlvlDelta: 2, hiIlvlDelta: 24, availOn: ["necklace"] },
    { id: "ll1", affixType: "suffix", statId: "ll", lo: 0.5, hi: 1, loIlvlDelta: 0.5, hiIlvlDelta: 1, availOn: ["necklace"] },
    { id: "ml1", affixType: "suffix", statId: "ml", lo: 0.5, hi: 1, loIlvlDelta: 0.5, hiIlvlDelta: 1, availOn: ["necklace"] },
    { id: "skfbltmage1", affixType: "suffix", statId: "skfbltmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skfrngmage1", affixType: "suffix", statId: "skfrngmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skfinfmage1", affixType: "suffix", statId: "skfinfmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skfbalmage1", affixType: "suffix", statId: "skfbalmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skfblsmage1", affixType: "suffix", statId: "skfblsmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skfwalmage1", affixType: "suffix", statId: "skfwalmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "sktchmmage1", affixType: "suffix", statId: "sktchmmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "sktbltmage1", affixType: "suffix", statId: "sktbltmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "sktltnmage1", affixType: "suffix", statId: "sktltnmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "sktnovmage1", affixType: "suffix", statId: "sktnovmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "sktshdmage1", affixType: "suffix", statId: "sktshdmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "sktblzmage1", affixType: "suffix", statId: "sktblzmage", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skbbaswarr1", affixType: "suffix", statId: "skbbaswarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skbcrtwarr1", affixType: "suffix", statId: "skbcrtwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skbthrwarr1", affixType: "suffix", statId: "skbthrwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skbclvwarr1", affixType: "suffix", statId: "skbclvwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skbcrzwarr1", affixType: "suffix", statId: "skbcrzwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skbfblwarr1", affixType: "suffix", statId: "skbfblwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skxdefwarr1", affixType: "suffix", statId: "skxdefwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skxdogwarr1", affixType: "suffix", statId: "skxdogwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skxctawarr1", affixType: "suffix", statId: "skxctawarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skxwmswarr1", affixType: "suffix", statId: "skxwmswarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skxchgwarr1", affixType: "suffix", statId: "skxchgwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skxtstwarr1", affixType: "suffix", statId: "skxtstwarr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skhhelwlok1", affixType: "suffix", statId: "skhhelwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skhgsdwlok1", affixType: "suffix", statId: "skhgsdwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skhinvwlok1", affixType: "suffix", statId: "skhinvwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skhhsdwlok1", affixType: "suffix", statId: "skhhsdwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skhlokwlok1", affixType: "suffix", statId: "skhlokwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skhmhlwlok1", affixType: "suffix", statId: "skhmhlwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skpbaswlok1", affixType: "suffix", statId: "skpbaswlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skppoiwlok1", affixType: "suffix", statId: "skppoiwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skpsklwlok1", affixType: "suffix", statId: "skpsklwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skprunwlok1", affixType: "suffix", statId: "skprunwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skpcblwlok1", affixType: "suffix", statId: "skpcblwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "skpsdmwlok1", affixType: "suffix", statId: "skpsdmwlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5, availOn: ["necklace"] },
    { id: "atkfblt1", affixType: "suffix", statId: "procatk", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "fblt", availOn: ["necklace"] },
    { id: "atkfbal1", affixType: "suffix", statId: "procatk", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "fbal", availOn: ["necklace"] },
    { id: "atktblt1", affixType: "suffix", statId: "procatk", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "tblt", availOn: ["necklace"] },
    { id: "atkpcbl1", affixType: "suffix", statId: "procatk", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "pcbl", availOn: ["necklace"] },
    { id: "hitfrng1", affixType: "suffix", statId: "prochit", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "frng", availOn: ["necklace"] },
    { id: "atktnov1", affixType: "suffix", statId: "prochit", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "tnov", availOn: ["necklace"] },
    { id: "atkhhel1", affixType: "suffix", statId: "prochit", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "hhel", availOn: ["necklace"] },
    { id: "hithinv1", affixType: "suffix", statId: "prochit", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 2, skill: "hinv", availOn: ["necklace"] },
    { id: "curs1", affixType: "suffix", statId: "curs", lo: 1, hi: 10, loIlvlDelta: 0, hiIlvlDelta: 1.25, availOn: ["necklace"] },
    { id: "bles1", affixType: "suffix", statId: "bles", lo: 1, hi: 10, loIlvlDelta: 0, hiIlvlDelta: 1.25, availOn: ["necklace"] },
    { id: "moral1", affixType: "suffix", statId: "moral", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.25, availOn: ["necklace"] },
    { id: "cb1", affixType: "suffix", statId: "cb", lo: 1, hi: 5, loIlvlDelta: 0, hiIlvlDelta: 1.25 },
    { id: "pmh1", affixType: "suffix", statId: "pmh", lo: 5, hi: 15, loIlvlDelta: 1.25, hiIlvlDelta: 8.75, availOn: ["necklace"] },
    { id: "xlr1", affixType: "suffix", statId: "xlr", lo: 2.5, hi: 5, loIlvlDelta: 0.625, hiIlvlDelta: 1.25, availOn: ["necklace"] },
    { id: "flr1", affixType: "suffix", statId: "flr", lo: 5, hi: 10, loIlvlDelta: 1.25, hiIlvlDelta: 2.5, availOn: ["necklace"] },
    { id: "tlr1", affixType: "suffix", statId: "tlr", lo: 5, hi: 10, loIlvlDelta: 1.25, hiIlvlDelta: 2.5, availOn: ["necklace"] },
    { id: "hlr1", affixType: "suffix", statId: "hlr", lo: 5, hi: 10, loIlvlDelta: 1.25, hiIlvlDelta: 2.5, availOn: ["necklace"] },
    { id: "plr1", affixType: "suffix", statId: "plr", lo: 5, hi: 10, loIlvlDelta: 1.25, hiIlvlDelta: 2.5, availOn: ["necklace"] },
    { id: "skfblt1", affixType: "suffix", statId: "skfblt", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skfrng1", affixType: "suffix", statId: "skfrng", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skfinf1", affixType: "suffix", statId: "skfinf", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skfbal1", affixType: "suffix", statId: "skfbal", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skfbls1", affixType: "suffix", statId: "skfbls", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skfwal1", affixType: "suffix", statId: "skfwal", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "sktchm1", affixType: "suffix", statId: "sktchm", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "sktblt1", affixType: "suffix", statId: "sktblt", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "sktltn1", affixType: "suffix", statId: "sktltn", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "sktnov1", affixType: "suffix", statId: "sktnov", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "sktshd1", affixType: "suffix", statId: "sktshd", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "sktblz1", affixType: "suffix", statId: "sktblz", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skbbas1", affixType: "suffix", statId: "skbbas", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skbcrt1", affixType: "suffix", statId: "skbcrt", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skbthr1", affixType: "suffix", statId: "skbthr", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skbclv1", affixType: "suffix", statId: "skbclv", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skbcrz1", affixType: "suffix", statId: "skbcrz", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skbfbl1", affixType: "suffix", statId: "skbfbl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skxdef1", affixType: "suffix", statId: "skxdef", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skxdog1", affixType: "suffix", statId: "skxdog", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skxcta1", affixType: "suffix", statId: "skxcta", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skxwms1", affixType: "suffix", statId: "skxwms", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skxchg1", affixType: "suffix", statId: "skxchg", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skxtst1", affixType: "suffix", statId: "skxtst", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skhhel1", affixType: "suffix", statId: "skhhel", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skhgsd1", affixType: "suffix", statId: "skhgsd", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skhinv1", affixType: "suffix", statId: "skhinv", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skhhsd1", affixType: "suffix", statId: "skhhsd", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skhlok1", affixType: "suffix", statId: "skhlok", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skhmhl1", affixType: "suffix", statId: "skhmhl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skpbas1", affixType: "suffix", statId: "skpbas", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skppoi1", affixType: "suffix", statId: "skppoi", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skpskl1", affixType: "suffix", statId: "skpskl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skprun1", affixType: "suffix", statId: "skprun", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skpcbl1", affixType: "suffix", statId: "skpcbl", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "skpsdm1", affixType: "suffix", statId: "skpsdm", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0.5 },
    { id: "setwargod", affixType: "suffix", statId: "setwargod", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setmara", affixType: "suffix", statId: "setmara", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setjihad", affixType: "suffix", statId: "setjihad", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setghost", affixType: "suffix", statId: "setghost", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setvenerable", affixType: "suffix", statId: "setvenerable", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setmaster", affixType: "suffix", statId: "setmaster", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setdemon", affixType: "suffix", statId: "setdemon", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setmagegod", affixType: "suffix", statId: "setmagegod", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setcolorful", affixType: "suffix", statId: "setcolorful", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setblackiron", affixType: "suffix", statId: "setblackiron", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setmysterious", affixType: "suffix", statId: "setmysterious", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setmemory", affixType: "suffix", statId: "setmemory", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setvoma", affixType: "suffix", statId: "setvoma", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setzuma", affixType: "suffix", statId: "setzuma", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setredmoon", affixType: "suffix", statId: "setredmoon", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setprisma", affixType: "suffix", statId: "setprisma", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setdragon", affixType: "suffix", statId: "setdragon", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
    { id: "setempire", affixType: "suffix", statId: "setempire", lo: 1, hi: 1, loIlvlDelta: 0, hiIlvlDelta: 0 },
];

export const AffixById = Object.fromEntries(Affixs.map(e => [e.id, e]));
export const AffixGroupByAvailOn = Affixs.reduce((acc, e) => {
    if (e.availOn != null) {
        e.availOn.forEach(group => {
            if (!acc[group]) {
                acc[group] = [];
            }
            acc[group].push(e);
        })
    }
    return acc;
}, {})
