export const Items = [
    { id: "clotharmor", name: "布衣", level: 1, quality: 1, description: "布衣描述", image: "🗡️", type: "armor", size: 1, stat: { ["xdr"]: [1, 2, 2, 3] }, randomStat: { ["fdr"]: [0, 0.1, 1, 1.5], ["tdr"]: [0, 0.1, 1, 1.5], ["hdr"]: [0, 0.1, 1, 1.5], ["pdr"]: [0, 0.1, 1, 1.5] } },
    { id: "leatherarmor", name: "皮甲", level: 1, quality: 1, type: "armor", stat: { ["xdr"]: [1, 2, 3, 4.5] } },
    { id: "lightarmor", name: "轻型盔甲", level: 14, quality: 1, type: "armor", stat: { ["xdr"]: [1.5, 3, 3, 4.5] }, randomStat: { ["fdr"]: [0.5, 1, 2, 3], ["tdr"]: [0.5, 1, 2, 3], ["hdr"]: [0.5, 1, 2, 3], ["pdr"]: [0.5, 1, 2, 3] } },
    { id: "bronzearmor", name: "青铜链甲", level: 14, quality: 1, type: "armor", stat: { ["xdr"]: [1.5, 3, 4, 6] } },
    { id: "mediumarmor", name: "中型盔甲", level: 28, quality: 1, type: "armor", stat: { ["xdr"]: [1.5, 3, 5, 7.5] }, randomStat: { ["fdr"]: [0.5, 1, 2, 3], ["tdr"]: [0.5, 1, 2, 3], ["hdr"]: [0.5, 1, 2, 3], ["pdr"]: [0.5, 1, 2, 3] } },
    { id: "ironarmor", name: "铁质铠甲", level: 28, quality: 1, type: "armor" },
    { id: "platearmor", name: "钢制板甲", level: 35, quality: 1, type: "armor" },
    { id: "blackarmor", name: "黑铁战甲", level: 35, quality: 1, type: "armor" },
    { id: "heavyarmor", name: "重盔甲", level: 21, quality: 3, classOnly: ["warr"], type: "armor", stat: { ["xdr"]: [2, 4, 7, 10.5] }, randomStat: { ["fdr"]: [1, 2, 3, 4.5], ["tdr"]: [1, 2, 3, 4.5], ["hdr"]: [1, 2, 3, 4.5], ["pdr"]: [1, 2, 3, 4.5] } },
    { id: "wargodarmor", name: "战神盔甲", level: 21, quality: 4, classOnly: ["warr"], type: "armor", stat: { ["xdr"]: [2.5, 5, 9, 13.5] }, randomStat: { ["fdr"]: [1.5, 3, 5, 7.5], ["tdr"]: [1.5, 3, 5, 7.5], ["hdr"]: [1.5, 3, 5, 7.5], ["pdr"]: [1.5, 3, 5, 7.5] } },
    { id: "maraarmor", name: "天魔神甲", level: 35, quality: 4, classOnly: ["warr"], type: "armor", stat: { ["xdr"]: [2.5, 5, 12, 18], ["xatk"]: [0.5, 1, 2, 3] }, randomStat: { ["fdr"]: [2, 4, 7, 10.5], ["tdr"]: [2, 4, 7, 10.5], ["hdr"]: [2, 4, 7, 10.5], ["pdr"]: [2, 4, 7, 10.5] } },
    { id: "jihadarmor", name: "圣战宝甲", level: 35, quality: 5, classOnly: ["warr"], type: "armor" },
    { id: "soularmor", name: "灵魂战衣", level: 21, quality: 3, classOnly: ["wlk"], type: "armor", stat: { ["xdr"]: [0, 0.1, 2, 3], ["watk"]: [1.5, 3, 3, 4.5] }, randomStat: { ["fdr"]: [1.5, 3, 6, 9], ["tdr"]: [1.5, 3, 6, 9], ["hdr"]: [1.5, 3, 6, 9], ["pdr"]: [1.5, 3, 6, 9] } },
    { id: "ghostarmor", name: "幽灵战衣", level: 21, quality: 4, classOnly: ["wlk"], type: "armor", stat: { ["xdr"]: [0.5, 1, 4, 6], ["watk"]: [1.5, 3, 4, 6] }, randomStat: { ["fdr"]: [2, 4, 7, 10.5], ["tdr"]: [2, 4, 7, 10.5], ["hdr"]: [2, 4, 7, 10.5], ["pdr"]: [2, 4, 7, 10.5] } },
    { id: "venerablerobe", name: "天尊道袍", level: 35, quality: 4, classOnly: ["wlk"], type: "armor", stat: { ["xdr"]: [1, 2, 5, 7.5], ["watk"]: [2, 4, 6, 9] }, randomStat: { ["fdr"]: [2, 4, 9, 13.5], ["tdr"]: [2, 4, 9, 13.5], ["hdr"]: [2, 4, 9, 13.5], ["pdr"]: [2, 4, 9, 13.5] } },
    { id: "masterrobe", name: "天师长袍", level: 35, quality: 5, classOnly: ["wlk"], type: "armor" },
    { id: "magicrobe", name: "魔法长袍", level: 21, quality: 3, classOnly: ["mage"], type: "armor", stat: { ["xdr"]: [0, 0.1, 2, 3], ["watk"]: [1.5, 3, 4, 6] }, randomStat: { ["fdr"]: [1.5, 3, 5, 7.5], ["tdr"]: [1.5, 3, 5, 7.5], ["hdr"]: [1.5, 3, 5, 7.5], ["pdr"]: [1.5, 3, 5, 7.5] } },
    { id: "demonrobe", name: "恶魔长袍", level: 21, quality: 4, classOnly: ["mage"], type: "armor", stat: { ["xdr"]: [0.5, 1, 4, 6], ["watk"]: [1.5, 3, 4, 6] }, randomStat: { ["fdr"]: [2, 4, 7, 10.5], ["tdr"]: [2, 4, 7, 10.5], ["hdr"]: [2, 4, 7, 10.5], ["pdr"]: [2, 4, 7, 10.5] } },
    { id: "magegodarmor", name: "法神披风", level: 35, quality: 4, classOnly: ["mage"], type: "armor", stat: { ["xdr"]: [1, 2, 5, 7.5], ["watk"]: [1.5, 3, 6, 9] }, randomStat: { ["fdr"]: [3, 6, 9, 13.5], ["tdr"]: [3, 6, 9, 13.5], ["hdr"]: [3, 6, 9, 13.5], ["pdr"]: [3, 6, 9, 13.5] } },
    { id: "colorarmor", name: "霓裳羽衣", level: 35, quality: 5, classOnly: ["mage"], type: "armor" },
    { id: "dragonarmor", name: "龙之披挂", type: "armor" },
    { id: "archonplate", name: "执政官铠甲", type: "armor" },
    { id: "ancientarmor", name: "古代装甲", type: "armor" },
    { id: "duskshround", name: "灰暮寿衣", type: "armor" },
    { id: "gladitatorarmor", name: "角斗士战甲", type: "armor" },
    { id: "mageplate", name: "法师铠甲", type: "armor" },
    { id: "clothbelt", name: "麻布束腰", type: "belt" },
    { id: "leatherbelt", name: "皮腰带", type: "belt" },
    { id: "lightbelt", name: "轻型腰带", type: "belt" },
    { id: "bronzebelt", name: "青铜锁链腰带", type: "belt" },
    { id: "mediumbelt", name: "中型腰带", type: "belt" },
    { id: "ironbelt", name: "铁质腰带", type: "belt" },
    { id: "platebelt", name: "钢制腰带", type: "belt" },
    { id: "mysteriousbelt", name: "神秘腰带", type: "belt" },
    { id: "corruptedbelt", name: "腐化缠腰带", type: "belt" },
    { id: "ancientbelt", name: "上古钢索", type: "belt" },
    { id: "guardbelt", name: "卫戍腰带", type: "belt" },
    { id: "palemoonbelt", name: "苍月束带", type: "belt" },
    { id: "maneofdevilbeast", name: "神兽之鬃", classOnly: ["wlk"], type: "belt" },
    { id: "orcbelt", name: "半兽人腰带", type: "belt" },
    { id: "mistbelt", name: "毒瘴腰带", type: "belt" },
    { id: "stringofears", name: "长串之耳", type: "belt" },
    { id: "witchinghour", name: "巫异时刻", type: "belt" },
    { id: "thunderlordvigor", name: "雷神腰带", type: "belt" },
    { id: "blizzardbelt", name: "暴雪束腰", type: "belt" },
    { id: "snakecord", name: "蛇索", type: "belt" },
    { id: "arnachbelt", name: "蛛网束带", type: "belt" },
    { id: "finesew", name: "精细织带", type: "belt" },
    { id: "chaosbelt", name: "混沌腰带", type: "belt" },
    { id: "arcticbelt", name: "极地腰带", type: "belt" },
    { id: "skullbelt", name: "骷髅腰带", type: "belt" },
    { id: "stygianbelt", name: "冥神裹布", type: "belt" },
    { id: "clothboots", name: "布靴", type: "boot" },
    { id: "leatherboots", name: "皮靴", type: "boot" },
    { id: "lightboots", name: "轻型战靴", type: "boot" },
    { id: "bronzeboots", name: "青铜战靴", type: "boot" },
    { id: "mediumboots", name: "中型战靴", type: "boot" },
    { id: "ironboots", name: "铁战靴", type: "boot" },
    { id: "plateboots", name: "钢制战靴", type: "boot" },
    { id: "hargenerboots", name: "哈根纳战靴", type: "boot" },
    { id: "geebahkboots", name: "吉巴科胫甲", type: "boot" },
    { id: "saintoasboots", name: "圣奥长靴", type: "boot" },
    { id: "shabakaboots", name: "沙巴克马靴", type: "boot" },
    { id: "borderboots", name: "边陲战靴", type: "boot" },
    { id: "mountainboots", name: "雪山靴", type: "boot" },
    { id: "lostboots", name: "失落长靴", type: "boot" },
    { id: "oasisboots", name: "绿洲马靴", type: "boot" },
    { id: "northstarboots", name: "北斗短靴", classOnly: ["wlk"], type: "boot" },
    { id: "sanderfolly", name: "山德的愚行", type: "boot" },
    { id: "aldurboots", name: "埃尔多胫甲", type: "boot" },
    { id: "infernostride", name: "地狱阔步", type: "boot" },
    { id: "goblintoes", name: "小妖精脚趾", type: "boot" },
    { id: "stormtread", name: "沙暴之旅", type: "boot" },
    { id: "gorerider", name: "蚀肉骑士", type: "boot" },
    { id: "wartraveller", name: "战争旅者", type: "boot" },
    { id: "shadowdance", name: "影舞者", type: "boot" },
    { id: "bloodfeet", name: "血脚", type: "boot" },
    { id: "warstomp", name: "战争践踏", type: "boot" },
    { id: "smallcharm", name: "小护身符", level: 1, quality: 2, type: "charm" },
    { id: "largecharm", name: "护身符", level: 1, quality: 2, type: "charm" },
    { id: "grandcharm", name: "大护身符", level: 1, quality: 2, type: "charm" },
    { id: "clothglove", name: "布手套", type: "glove" },
    { id: "leatherglove", name: "皮质手套", type: "glove" },
    { id: "lightglove", name: "轻型手套", type: "glove" },
    { id: "bronzeglove", name: "青铜手甲", type: "glove" },
    { id: "mediumglove", name: "中型手套", type: "glove" },
    { id: "ironglove", name: "铁质手套", type: "glove" },
    { id: "plateglove", name: "钢制手甲", type: "glove" },
    { id: "steadyglove", name: "坚固手套", type: "glove" },
    { id: "reaperglove", name: "死神手套", type: "glove" },
    { id: "ghostglove", name: "幽灵手套", type: "glove" },
    { id: "devilglove", name: "阎罗手套", type: "glove" },
    { id: "tigerguardglove", name: "虎卫手甲", type: "glove" },
    { id: "devilclaw", name: "魔界异爪", type: "glove" },
    { id: "dragonguardgloves", name: "龙卫长手套", type: "glove" },
    { id: "tigertoothglove", name: "虎齿手套", type: "glove" },
    { id: "bulldemongloves", name: "牛魔手甲", type: "glove" },
    { id: "draculagrip", name: "德古拉之握", type: "glove" },
    { id: "layingofhands", name: "手掌的安置", type: "glove" },
    { id: "shattersteel", name: "碎钢", type: "glove" },
    { id: "frostburn", name: "霜燃", type: "glove" },
    { id: "valkyriegloves", name: "女武神护手", type: "glove" },
    { id: "trangoulclaw", name: "塔格奥之爪", type: "glove" },
    { id: "bloodfist", name: "血拳", type: "glove" },
    { id: "deathgrip", name: "死亡之握", type: "glove" },
    { id: "chanceguard", name: "运气守护", type: "glove" },
    { id: "handofincenerator", name: "焚毁者之手", type: "glove" },
    { id: "clothcap", name: "布帽", type: "helm" },
    { id: "leathercap", name: "皮帽", type: "helm" },
    { id: "lightcap", name: "轻型头盔", type: "helm" },
    { id: "bronzecap", name: "青铜头盔", type: "helm", stat: { ["xdr"]: [0, 0.1, 1, 1.5] } },
    { id: "mediumcap", name: "中型头盔", type: "helm" },
    { id: "ironcap", name: "铁质头盔", type: "helm" },
    { id: "platecap", name: "板甲头盔", type: "helm" },
    { id: "magiccap", name: "魔法头盔", type: "helm", stat: { ["xdr"]: [0, 0.1, 1, 1.5] }, randomStat: { ["fdr"]: [0.5, 1, 1, 1.5], ["tdr"]: [0.5, 1, 1, 1.5], ["hdr"]: [0.5, 1, 1, 1.5], ["pdr"]: [0.5, 1, 1, 1.5] } },
    { id: "warlockcap", name: "道士头盔", type: "helm", stat: { ["xdr"]: [0.5, 1, 2, 3] }, randomStat: { ["fdr"]: [1, 2, 3, 4.5], ["tdr"]: [1, 2, 3, 4.5], ["hdr"]: [1, 2, 3, 4.5], ["pdr"]: [1, 2, 3, 4.5] } },
    { id: "skullcap", name: "骷髅头盔", type: "helm", stat: { ["xdr"]: [1, 2, 3, 4.5] } },
    { id: "memorycap", name: "记忆头盔", type: "helm", stat: { ["xdr"]: [1.5, 3, 3, 4.5] } },
    { id: "prayercap", name: "祈祷头盔", type: "helm", stat: { ["xdr"]: [1.5, 3, 4, 6] }, randomStat: { ["fdr"]: [0.5, 1, 2, 3], ["tdr"]: [0.5, 1, 2, 3], ["hdr"]: [0.5, 1, 2, 3], ["pdr"]: [0.5, 1, 2, 3] } },
    { id: "blackironcap", name: "黑铁头盔", type: "helm", stat: { ["xdr"]: [2, 4, 5, 7.5] }, randomStat: { ["fdr"]: [1, 2, 3, 4.5], ["tdr"]: [1, 2, 3, 4.5], ["hdr"]: [1, 2, 3, 4.5], ["pdr"]: [1, 2, 3, 4.5] } },
    { id: "mysteriouscap", name: "神秘头盔", type: "helm", stat: { ["xdr"]: [2.5, 5, 5, 7.5] }, randomStat: { ["fdr"]: [1.5, 3, 3, 4.5], ["tdr"]: [1.5, 3, 3, 4.5], ["hdr"]: [1.5, 3, 3, 4.5], ["pdr"]: [1.5, 3, 3, 4.5] } },
    { id: "harbingerhelm", name: "先驱者战盔", type: "helm" },
    { id: "glintswordwill", name: "辉剑的意志", classOnly: ["warr"], type: "helm" },
    { id: "flamefeatherwisdom", name: "焰翎的智慧", classOnly: ["mage"], type: "helm" },
    { id: "azurecloudmeditation", name: "皓云的冥思", classOnly: ["wlk"], type: "helm" },
    { id: "flickeringflame", name: "摇曳之火", type: "helm" },
    { id: "dream", name: "梦境", type: "helm" },
    { id: "dilirium", name: "迪勒瑞姆", type: "helm" },
    { id: "faceofjiron", name: "吉永之脸", type: "helm" },
    { id: "crownofage", name: "年纪之冠", type: "helm" },
    { id: "griffoneye", name: "格力风之眼", type: "helm" },
    { id: "wolfhowl", name: "狼嗷", type: "helm" },
    { id: "haleriumcrest", name: "邪角之冠", type: "helm" },
    { id: "goldnecklace", name: "金项链", level: 2, type: "necklace", size: 1, stat: { ["xatk"]: [0, 0.1, 1, 1.5], ["doge"]: [1, 1.5] } },
    { id: "ordinarynecklace", name: "传统项链", level: 3, type: "necklace", size: 1, stat: { ["hit"]: [1, 1.5] } },
    { id: "topaznecklace", name: "黄色水晶项链", level: 13, type: "necklace", size: 1, stat: { ["watk"]: [1, 1.5, 0, 0.1] } },
    { id: "sandalnecklace", name: "黑檀项链", level: 13, type: "necklace", size: 1, stat: { ["matk"]: [1, 1.5, 0, 0.1] } },
    { id: "blackcrystalnecklace", name: "黑色水晶项链", level: 13, type: "necklace", size: 1, stat: { ["watk"]: [0.5, 1, 1, 1.5] } },
    { id: "whitetigernecklace", name: "白色虎齿项链", level: 11, type: "necklace", size: 1, stat: { ["xdr"]: [0, 0.1, 1, 1.5], ["mdoge"]: [2, 3] }, randomStat: { ["fdr"]: [0.5, 1, 2, 3], ["tdr"]: [0.5, 1, 2, 3], ["hdr"]: [0.5, 1, 2, 3], ["pdr"]: [0.5, 1, 2, 3] } },
    { id: "whitegoldnecklace", name: "白金项链", level: 10, type: "necklace", size: 1, stat: { ["matk"]: [0, 0.1, 2, 3] } },
    { id: "lampnecklace", name: "灯笼项链", level: 18, type: "necklace", size: 1, stat: { ["xatk"]: [1, 1.5, 0, 0.1], ["mdoge"]: [1, 1.5] } },
    { id: "ambernecklace", name: "琥珀项链", level: 17, type: "necklace", size: 1, stat: { ["matk"]: [2, 3, 0, 0.1] } },
    { id: "devilnecklace", name: "魔鬼项链", level: 17, type: "necklace", size: 1, stat: { ["xatk"]: [2, 3, 0, 0.1] } },
    { id: "pheonixnecklace", name: "凤凰明珠", level: 17, type: "necklace", size: 1, stat: { ["watk"]: [0.5, 1, 2, 3] } },
    { id: "blueemeraldnecklace", name: "蓝翡翠项链", level: 23, type: "necklace", size: 1, stat: { ["xatk"]: [1, 2, 2, 3] } },
    { id: "bambooflute", name: "竹笛", level: 24, type: "necklace", size: 1, stat: { ["watk"]: [0.5, 1, 3, 4.5] } },
    { id: "maganifier", name: "放大镜", level: 24, type: "necklace", size: 1, stat: { ["matk"]: [0.5, 1, 3, 4.5] } },
    { id: "ghostnecklace", name: "幽灵项链", level: 24, type: "necklace", size: 1, stat: { ["xatk"]: [0, 0.1, 5, 7.5] } },
    { id: "greennecklace", name: "绿色项链", level: 39, type: "necklace", size: 1, stat: { ["xatk"]: [1, 2, 5, 7.5] } },
    { id: "soulnecklace", name: "灵魂项链", level: 23, type: "necklace", size: 1, stat: { ["watk"]: [0.5, 1, 6, 9], ["hit"]: [2, 3] } },
    { id: "devilbell", name: "恶魔铃铛", level: 27, type: "necklace", size: 1, stat: { ["matk"]: [0, 0.1, 7, 10.5], ["hit"]: [2, 3] } },
    { id: "demonbloodnecklace", name: "魔血项链", level: 33, type: "necklace", size: 1, stat: { ["xatk"]: [1, 2, 2, 3], ["matk"]: [0.5, 1, 3, 4.5] } },
    { id: "prismademonnecklace", name: "虹魔项链", level: 33, type: "necklace", size: 1, stat: { ["matk"]: [0, 0.1, 4, 6] } },
    { id: "breezenecklace", name: "狂风项链", level: 19, type: "necklace", size: 1, stat: { ["xatk"]: [0, 0.1, 1, 1.5], ["spd"]: [2, 3] } },
    { id: "dodgenecklace", name: "躲避项链", level: 12, type: "necklace", size: 1, stat: { ["doge"]: [2, 3] } },
    { id: "marakelopscope", name: "天魔神镜", type: "necklace" },
    { id: "rageoftyrant", name: "暴君之怒", type: "necklace" },
    { id: "risingsun", name: "旭日东升", type: "necklace" },
    { id: "metalgrid", name: "金属网格", type: "necklace" },
    { id: "clothpants", name: "轻便长裤", type: "pant" },
    { id: "leatherpants", name: "皮腿甲", type: "pant" },
    { id: "lightpants", name: "轻型腿甲", type: "pant" },
    { id: "bronzepants", name: "青铜腿甲", type: "pant" },
    { id: "mediumpants", name: "中型腿甲", type: "pant" },
    { id: "ironpants", name: "铁质腿甲", type: "pant" },
    { id: "platepants", name: "钢制腿甲", type: "pant" },
    { id: "zumapants", name: "祖玛护腿", type: "pant" },
    { id: "demonpants", name: "恶魔长裤", type: "pant" },
    { id: "bitchpant", name: "比奇马裤", type: "pant" },
    { id: "monchonpants", name: "盟重腿甲", type: "pant" },
    { id: "dragonkinpants", name: "龙族腿甲", type: "pant" },
    { id: "crusadepants", name: "征伐绑腿", type: "pant" },
    { id: "lostpants", name: "失乐腿甲", type: "pant" },
    { id: "avalanchepants", name: "雪崩长裤", type: "pant" },
    { id: "undeaddemonpants", name: "尸魔腿甲", type: "pant" },
    { id: "faudpox", name: "恶疮马裤", type: "pant" },
    { id: "deathbargin", name: "冥神的交易", type: "pant" },
    { id: "stonepants", name: "石像长裤", type: "pant" },
    { id: "defilerpants", name: "污染者腿甲", type: "pant" },
    { id: "serpentwanderer", name: "蛇谷游荡者", type: "pant" },
    { id: "diggerdepth", name: "矿工裤", type: "pant" },
    { id: "gehenas", name: "基赫纳斯", type: "pant" },
    { id: "cunningpants", name: "狡诈长裤", type: "pant" },
    { id: "captainspants", name: "队长腿甲", type: "pant" },
    { id: "shadowcoil", name: "阴影缠结", type: "pant" },
    { id: "clothpauldron", name: "布衬肩", type: "pauldron" },
    { id: "leatherpauldron", name: "硬皮肩甲", type: "pauldron" },
    { id: "lightpauldron", name: "轻型护肩", type: "pauldron" },
    { id: "bronzepauldron", name: "青铜肩甲", type: "pauldron" },
    { id: "mediumpauldron", name: "中型护肩", type: "pauldron" },
    { id: "ironpauldron", name: "铁质肩甲", type: "pauldron" },
    { id: "platepauldron", name: "钢制肩胄", type: "pauldron" },
    { id: "ormapauldron", name: "奥马垫肩", type: "pauldron" },
    { id: "neelpauldron", name: "尼耳护肩", type: "pauldron" },
    { id: "whitesunpauldron", name: "白日肩甲", type: "pauldron" },
    { id: "ruinspauldron", name: "遗迹肩甲", type: "pauldron" },
    { id: "demondragonpauldron", name: "魔龙护肩", type: "pauldron" },
    { id: "blooddemonpauldron", name: "血魔肩甲", type: "pauldron" },
    { id: "thoriumpauldron", name: "瑟银肩甲", type: "pauldron" },
    { id: "empirepauldron", name: "帝国肩甲", type: "pauldron" },
    { id: "bonedemonpauldrons", name: "骨魔肩甲", type: "pauldron" },
    { id: "homingpads", name: "归家垫肩", type: "pauldron" },
    { id: "corpsekingpauldron", name: "尸王肩甲", type: "pauldron" },
    { id: "betrayerpauldron", name: "叛教者护肩", type: "pauldron" },
    { id: "deathguard", name: "死神守护", type: "pauldron" },
    { id: "corpsewhisper", name: "尸语者护肩", type: "pauldron" },
    { id: "lifesiphoning", name: "生命虹吸肩甲", type: "pauldron" },
    { id: "channelingpauldron", name: "导能护肩", type: "pauldron" },
    { id: "ancientwrath", name: "远古之怒肩甲", type: "pauldron" },
    { id: "vileguard", name: "邪魔守卫护肩", type: "pauldron" },
    { id: "sevensinspauldron", name: "七罪护肩", type: "pauldron" },
    { id: "bronzering", name: "古铜戒指", type: "ring" },
    { id: "glassring", name: "玻璃戒指", type: "ring" },
    { id: "hexagonring", name: "六角戒指", type: "ring" },
    { id: "hornring", name: "牛角戒指", type: "ring" },
    { id: "saphirering", name: "蓝色水晶戒指", type: "ring" },
    { id: "lifering", name: "生命戒指", type: "ring" },
    { id: "pearlring", name: "珍珠戒指", type: "ring" },
    { id: "blackcrystalring", name: "黑色水晶戒指", type: "ring" },
    { id: "snakeeyering", name: "蛇眼戒指", type: "ring" },
    { id: "goldring", name: "金戒指", type: "ring" },
    { id: "moralring", name: "道德戒指", type: "ring" },
    { id: "charmring", name: "魅力戒指", type: "ring" },
    { id: "demoslayerring", name: "降妖除魔戒指", type: "ring" },
    { id: "platiniumring", name: "铂金戒指", type: "ring" },
    { id: "skullring", name: "骷髅戒指", type: "ring" },
    { id: "coralring", name: "珊瑚戒指", type: "ring" },
    { id: "prismademonring", name: "虹魔戒指", type: "ring" },
    { id: "rubyring", name: "红宝石戒指", type: "ring" },
    { id: "dragonring", name: "龙之戒指", type: "ring" },
    { id: "breezering", name: "狂风戒指", type: "ring" },
    { id: "titanring", name: "泰坦戒指", type: "ring" },
    { id: "valorring", name: "力量戒指", type: "ring" },
    { id: "purplesnail", name: "紫碧螺", type: "ring" },
    { id: "mysteriousring", name: "神秘戒指", type: "ring" },
    { id: "nummingring", name: "麻痹戒指", type: "ring" },
    { id: "contractingring", name: "收缩戒指", type: "ring" },
    { id: "woodsword", name: "木剑", level: 1, quality: 1, description: "木剑描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [1, 2, 5, 7.5] } },
    { id: "dagger", name: "匕首", level: 1, quality: 1, description: "匕首描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [2, 4, 5, 7.5] } },
    { id: "ebonywoodsword", name: "乌木剑", level: 1, quality: 1, description: "乌木剑描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [2, 4, 8, 12], ["matk"]: [0, 0.1, 1, 1.1] } },
    { id: "bronzesword", name: "青铜剑", level: 5, quality: 1, description: "青铜剑描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [1, 3, 7, 10] } },
    { id: "shortsword", name: "短剑", level: 10, quality: 1, description: "短剑描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [1, 3, 11, 16] } },
    { id: "ironsword", name: "铁剑", level: 10, quality: 1, description: "铁剑描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [2, 5, 9, 13] } },
    { id: "mattock", name: "鹤嘴锄", level: 11, quality: 1, description: "鹤嘴锄描述", image: "⛏", type: "weapon", size: 1, stat: { ["xatk"]: [0, 0.1, 8, 12], ["luck"]: [1, 2] } },
    { id: "bronzeaxe", name: "青铜斧", level: 11, quality: 1, description: "青铜斧描述", image: "🪓", type: "weapon", size: 1, stat: { ["xatk"]: [5, 10, 15, 22] } },
    { id: "rakshasa", name: "罗刹", level: 15, quality: 4, description: "罗刹描述", image: "🪓", type: "weapon", size: 2, stat: { ["xatk"]: [13, 19, 0, 0.1], ["curs"]: [7, 15] } },
    { id: "eightwilderness", name: "八荒", level: 15, quality: 4, classOnly: ["warr"], description: "八荒描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [2, 4, 12, 18] } },
    { id: "overwind", name: "凌风", level: 19, quality: 4, classOnly: ["warr"], description: "凌风描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [3, 6, 12, 18] } },
    { id: "brokensoul", name: "破魂", level: 20, quality: 4, classOnly: ["warr"], description: "破魂", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [4, 8, 10, 15], ["hit"]: [1, 2] } },
    { id: "horsecleaver", name: "斩马刀", level: 20, quality: 4, classOnly: ["warr"], description: "斩马刀", image: "🗡️", type: "weapon", size: 2, stat: { ["xatk"]: [2, 5, 15, 22] } },
    { id: "shura", name: "修罗", level: 22, quality: 4, classOnly: ["warr"], description: "修罗", image: "🗡️", type: "weapon", size: 2, stat: { ["xatk"]: [0, 0.1, 20, 30] } },
    { id: "condensefrost", name: "凝霜", level: 22, quality: 4, classOnly: ["warr"], description: "凝霜", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [5, 10, 13, 19] } },
    { id: "inferno", name: "炼狱", level: 22, quality: 4, classOnly: ["warr"], description: "炼狱", image: "🗡️", type: "weapon", size: 2, stat: { ["xatk"]: [0, 0.1, 25, 37] } },
    { id: "wellmoon", name: "井中月", level: 28, quality: 4, classOnly: ["warr"], description: "井中月", image: "🗡️", type: "weapon", size: 2, stat: { ["xatk"]: [3, 7, 22, 33] } },
    { id: "judgestaff", name: "裁决之杖", level: 30, quality: 4, classOnly: ["warr"], description: "裁决之杖描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [0, 0.1, 30, 45] } },
    { id: "dragonslayer", name: "屠龙刀", level: 35, quality: 4, classOnly: ["warr"], description: "屠龙刀描述", image: "🗡️", type: "weapon", size: 2, stat: { ["xatk"]: [2, 5, 35, 52] } },
    { id: "halfmoon", name: "半月", level: 15, quality: 4, classOnly: ["wlk"], description: "半月描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [2, 5, 10, 15], ["matk"]: [0, 0.1, 1, 1.1], ["watk"]: [1, 1.1, 1.1, 1.2] } },
    { id: "subduedemon", name: "降魔", level: 15, quality: 4, classOnly: ["wlk"], description: "降魔描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [3, 6, 11, 16.5], ["watk"]: [0.5, 1, 2, 3], ["hit"]: [1, 2] } },
    { id: "silverserpent", name: "银蛇", level: 15, quality: 4, classOnly: ["wlk"], description: "银蛇描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [4, 8, 16, 24], ["watk"]: [0.5, 1, 3, 4.5], ["hit"]: [1, 2] } },
    { id: "nullstaff", name: "无极棍", level: 15, quality: 4, classOnly: ["wlk"], description: "无极棍描述", image: "🗡️", type: "weapon", size: 2, stat: { ["xatk"]: [4, 8, 16, 24], ["watk"]: [1.5, 3, 5, 7.5] } },
    { id: "dragonsword", name: "龙纹剑", level: 35, quality: 4, classOnly: ["wlk"], description: "龙纹剑描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [4, 8, 20, 30], ["watk"]: [1.5, 3, 6, 9], ["hit"]: [1, 2] } },
    { id: "seasoul", name: "海魂", level: 15, quality: 4, classOnly: ["mage"], description: "海魂描述", image: "🗡️", type: "weapon", size: 2, stat: { ["xatk"]: [1.5, 3, 10, 15], ["matk"]: [1, 1.1, 2, 3] } },
    { id: "siezemoon", name: "偃月", level: 35, quality: 4, classOnly: ["mage"], description: "偃月描述", image: "🗡️", type: "weapon", size: 2, stat: { ["xatk"]: [2, 4, 10, 15], ["matk"]: [1, 1.1, 3, 4.5] } },
    { id: "magicstaff", name: "魔杖", level: 35, quality: 4, classOnly: ["mage"], description: "魔杖描述", image: "🗡️", type: "weapon", size: 2, stat: { ["xatk"]: [2.5, 5, 9, 13.5], ["matk"]: [1, 2, 5, 7.5] } },
    { id: "blooddrink", name: "血饮", level: 35, quality: 4, classOnly: ["mage"], description: "血饮描述", image: "🗡️", type: "weapon", size: 1, stat: { ["xatk"]: [1.5, 3, 14, 21], ["matk"]: [1.5, 3, 5, 7.5], ["hit"]: [5, 7.5] } },
    { id: "bonescepter", name: "骨玉权杖", level: 35, quality: 4, classOnly: ["mage"], description: "骨玉权杖描述", image: "🗡️", type: "weapon", size: 2, stat: { ["xatk"]: [3, 6, 12, 18], ["matk"]: [1, 2, 6, 9] } },
    { id: "prismademonstaff", name: "虹魔法杖", type: "weapon", size: 2 },
    { id: "dragongodsword", name: "神龙剑", type: "weapon", size: 1 },
    { id: "demonbloodvessel", name: "魔血法器", type: "weapon", size: 1 },
    { id: "renmoonsaber", name: "赤月弯刀", type: "weapon", size: 1 },
    { id: "revelation", name: "启示录", classOnly: ["mage"], type: "weapon" },
    { id: "ragecleave", name: "怒斩", classOnly: ["warr"], type: "weapon" },
    { id: "dragontooth", name: "龙牙", classOnly: ["mage"], type: "weapon" },
    { id: "elysianfan", name: "逍遥扇", classOnly: ["wlk"], type: "weapon" },
    { id: "layingserpent", name: "卧龙", type: "weapon" },
    { id: "clothwrist", name: "白布护臂", type: "wrist" },
    { id: "leatherwrist", name: "软皮臂甲", type: "wrist" },
    { id: "lightwrist", name: "轻型手镯", type: "wrist" },
    { id: "bronzewrist", name: "青铜手镯", type: "wrist" },
    { id: "mediumwrist", name: "中型手镯", type: "wrist" },
    { id: "ironwrist", name: "铁护腕", type: "wrist" },
    { id: "platewrist", name: "钢制臂甲", type: "wrist" },
    { id: "womawrist", name: "沃玛手镯", type: "wrist" },
    { id: "ironbracelet", name: "铁手镯", type: "wrist" },
    { id: "smallbracelet", name: "小手镯", type: "wrist" },
    { id: "silverbracelet", name: "银手镯", type: "wrist" },
    { id: "largebracelet", name: "大手镯", type: "wrist" },
    { id: "steelbracelet", name: "钢手镯", type: "wrist" },
    { id: "magicbracelet", name: "魔法手镯", type: "wrist" },
    { id: "sharpelbracelet", name: "夏普儿手镯", type: "wrist" },
    { id: "antijinxbracelet", name: "辟邪手镯", type: "wrist" },
    { id: "warlockbracelet", name: "道士手镯", type: "wrist" },
    { id: "blacksandalbracelet", name: "黑檀手镯", type: "wrist" },
    { id: "powerbracelet", name: "魔力手镯", type: "wrist" },
    { id: "goldbracelet", name: "金手镯", type: "wrist" },
    { id: "spiritbracelet", name: "心灵手镯", type: "wrist" },
    { id: "tripleeyebracelet", name: "三眼手镯", type: "wrist" },
    { id: "sebelbracelet", name: "思贝儿手镯", type: "wrist" },
    { id: "dragonbracelet", name: "龙之手镯", type: "wrist" },
    { id: "knightbracelet", name: "骑士手镯", type: "wrist" },
    { id: "demonbloodbracelet", name: "魔血手镯", type: "wrist" },
]

export const ItemById = Object.fromEntries(Items.map(e => [e.id, e]))
