export const Items = [
    { id: "clotharmor", name: "布衣", level: 1, quality: 0, maxQuality: 2, description: "布衣描述", image: "INV_Shirt_14", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 0 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 }, sockets: "sok4" },
    { id: "leatherarmor", name: "皮甲", level: 1, quality: 0, maxQuality: 2, image: "INV_Chest_Leather_09", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 0.2 }, sockets: "sok4" },
    { id: "lightarmor", name: "轻型盔甲", level: 7, quality: 0, maxQuality: 2, image: "INV_Chest_Leather_10", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 0.5 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 }, sockets: "sok4" },
    { id: "bronzearmor", name: "青铜链甲", level: 7, quality: 0, maxQuality: 2, image: "INV_Chest_Plate07", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 0.7 }, sockets: "sok4" },
    { id: "mediumarmor", name: "中型盔甲", level: 14, quality: 0, maxQuality: 2, image: "INV_Chest_Plate01", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 1 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 }, sockets: "sok4" },
    { id: "ironarmor", name: "铁质铠甲", level: 14, quality: 0, maxQuality: 2, image: "INV_Chest_Plate02", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 1.1 }, sockets: "sok4" },
    { id: "platearmor", name: "钢制板甲", level: 21, quality: 0, maxQuality: 2, image: "INV_Chest_Plate05", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 1.5 }, sockets: "sok4" },
    { id: "blackarmor", name: "黑铁战甲", level: 21, quality: 0, maxQuality: 2, image: "INV_Chest_Plate10", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 2 }, sockets: "sok4" },
    { id: "heavyarmor", name: "重盔甲", level: 21, quality: 3, classOnly: ["warr"], image: "重", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 1.5 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "wargodarmor", name: "战神盔甲", level: 21, quality: 3, classOnly: ["warr"], image: "战", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 2.5 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "maraarmor", name: "天魔神甲", level: 35, quality: 3, classOnly: ["warr"], image: "天", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 3, ["str1"]: 1 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "jihadarmor", name: "圣战宝甲", level: 35, quality: 4, classOnly: ["warr"], image: "圣", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 4 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "soularmor", name: "灵魂战衣", level: 21, quality: 3, classOnly: ["wlk"], image: "灵", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 0.2, ["spi1"]: 1 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "ghostarmor", name: "幽灵战衣", level: 21, quality: 3, classOnly: ["wlk"], image: "幽", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 0.7, ["spi1"]: 1 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "venerablerobe", name: "天尊道袍", level: 35, quality: 3, classOnly: ["wlk"], image: "天", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 1.2, ["spi1"]: 1 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "masterrobe", name: "天师长袍", level: 35, quality: 4, classOnly: ["wlk"], image: "天", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 1.8, ["spi1"]: 1.5 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "magicrobe", name: "魔法长袍", level: 21, quality: 3, classOnly: ["mage"], image: "魔", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 0.2, ["int1"]: 1 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "demonrobe", name: "恶魔长袍", level: 21, quality: 3, classOnly: ["mage"], image: "恶", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 0.5, ["int1"]: 1 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "magegodarmor", name: "法神披风", level: 35, quality: 3, classOnly: ["mage"], image: "法", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 0.7, ["int1"]: 1 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "colorarmor", name: "霓裳羽衣", level: 35, quality: 4, classOnly: ["mage"], image: "霓", type: "armor", slot: "torso", size: 1, fixedAffix: { ["xdr1"]: 1, ["int1"]: 1.5 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "dragonarmor", name: "龙之披挂", level: 1, quality: 3, image: "龙", type: "armor", slot: "torso", size: 1 },
    { id: "archonplate", name: "执政官铠甲", level: 1, quality: 3, image: "执", type: "armor", slot: "torso", size: 1 },
    { id: "ancientarmor", name: "古代装甲", level: 1, quality: 3, image: "古", type: "armor", slot: "torso", size: 1 },
    { id: "duskshround", name: "灰暮寿衣", level: 1, quality: 3, image: "灰", type: "armor", slot: "torso", size: 1 },
    { id: "gladitatorarmor", name: "角斗士战甲", level: 1, quality: 3, image: "角", type: "armor", slot: "torso", size: 1 },
    { id: "mageplate", name: "法师铠甲", level: 1, quality: 3, image: "法", type: "armor", slot: "torso", size: 1 },
    { id: "clothbelt", name: "麻布束腰", level: 1, quality: 0, maxQuality: 2, image: "麻", type: "belt", slot: "waist", size: 1, sockets: "sok1" },
    { id: "leatherbelt", name: "皮腰带", level: 1, quality: 0, maxQuality: 2, image: "皮", type: "belt", slot: "waist", size: 1, sockets: "sok1" },
    { id: "lightbelt", name: "轻型腰带", level: 1, quality: 0, maxQuality: 2, image: "轻", type: "belt", slot: "waist", size: 1, sockets: "sok1" },
    { id: "bronzebelt", name: "青铜锁链腰带", level: 1, quality: 0, maxQuality: 2, image: "青", type: "belt", slot: "waist", size: 1, sockets: "sok1" },
    { id: "mediumbelt", name: "中型腰带", level: 1, quality: 0, maxQuality: 2, image: "中", type: "belt", slot: "waist", size: 1, sockets: "sok1" },
    { id: "ironbelt", name: "铁质腰带", level: 1, quality: 0, maxQuality: 2, image: "铁", type: "belt", slot: "waist", size: 1, sockets: "sok1" },
    { id: "platebelt", name: "钢制腰带", level: 1, quality: 0, maxQuality: 2, image: "钢", type: "belt", slot: "waist", size: 1, sockets: "sok1" },
    { id: "mysteriousbelt", name: "神秘腰带", level: 1, quality: 3, image: "神", type: "belt", slot: "waist", size: 1 },
    { id: "corruptedbelt", name: "腐化缠腰带", level: 1, quality: 3, image: "腐", type: "belt", slot: "waist", size: 1 },
    { id: "ancientbelt", name: "上古钢索", level: 1, quality: 3, image: "上", type: "belt", slot: "waist", size: 1 },
    { id: "guardbelt", name: "卫戍腰带", level: 1, quality: 3, image: "卫", type: "belt", slot: "waist", size: 1 },
    { id: "palemoonbelt", name: "苍月束带", level: 1, quality: 3, image: "苍", type: "belt", slot: "waist", size: 1 },
    { id: "maneofdevilbeast", name: "神兽之鬃", level: 1, quality: 3, classOnly: ["wlk"], image: "神", type: "belt", slot: "waist", size: 1 },
    { id: "orcbelt", name: "半兽人腰带", level: 1, quality: 3, image: "半", type: "belt", slot: "waist", size: 1 },
    { id: "mistbelt", name: "毒瘴腰带", level: 1, quality: 3, image: "毒", type: "belt", slot: "waist", size: 1 },
    { id: "stringofears", name: "长串之耳", level: 1, quality: 3, image: "长", type: "belt", slot: "waist", size: 1 },
    { id: "witchinghour", name: "巫异时刻", level: 1, quality: 3, image: "巫", type: "belt", slot: "waist", size: 1 },
    { id: "thunderlordvigor", name: "雷神腰带", level: 1, quality: 3, image: "雷", type: "belt", slot: "waist", size: 1 },
    { id: "blizzardbelt", name: "暴雪束腰", level: 1, quality: 3, image: "暴", type: "belt", slot: "waist", size: 1 },
    { id: "snakecord", name: "蛇索", level: 1, quality: 3, image: "蛇", type: "belt", slot: "waist", size: 1 },
    { id: "arnachbelt", name: "蛛网束带", level: 1, quality: 3, image: "蛛", type: "belt", slot: "waist", size: 1 },
    { id: "finesew", name: "精细织带", level: 1, quality: 3, image: "精", type: "belt", slot: "waist", size: 1 },
    { id: "chaosbelt", name: "混沌腰带", level: 1, quality: 3, image: "混", type: "belt", slot: "waist", size: 1 },
    { id: "arcticbelt", name: "极地腰带", level: 1, quality: 3, image: "极", type: "belt", slot: "waist", size: 1 },
    { id: "skullbelt", name: "骷髅腰带", level: 1, quality: 3, image: "骷", type: "belt", slot: "waist", size: 1 },
    { id: "stygianbelt", name: "冥神裹布", level: 1, quality: 3, image: "冥", type: "belt", slot: "waist", size: 1 },
    { id: "clothboots", name: "布靴", level: 1, quality: 0, maxQuality: 2, image: "布", type: "boot", slot: "foot", size: 1, sockets: "sok2" },
    { id: "leatherboots", name: "皮靴", level: 1, quality: 0, maxQuality: 2, image: "皮", type: "boot", slot: "foot", size: 1, sockets: "sok2" },
    { id: "lightboots", name: "轻型战靴", level: 1, quality: 0, maxQuality: 2, image: "轻", type: "boot", slot: "foot", size: 1, sockets: "sok2" },
    { id: "bronzeboots", name: "青铜战靴", level: 1, quality: 0, maxQuality: 2, image: "青", type: "boot", slot: "foot", size: 1, sockets: "sok2" },
    { id: "mediumboots", name: "中型战靴", level: 1, quality: 0, maxQuality: 2, image: "中", type: "boot", slot: "foot", size: 1, sockets: "sok2" },
    { id: "ironboots", name: "铁战靴", level: 1, quality: 0, maxQuality: 2, image: "铁", type: "boot", slot: "foot", size: 1, sockets: "sok2" },
    { id: "plateboots", name: "钢制战靴", level: 1, quality: 0, maxQuality: 2, image: "钢", type: "boot", slot: "foot", size: 1, sockets: "sok2" },
    { id: "hargenerboots", name: "哈根纳战靴", level: 1, quality: 3, image: "哈", type: "boot", slot: "foot", size: 1 },
    { id: "geebahkboots", name: "吉巴科胫甲", level: 1, quality: 3, image: "吉", type: "boot", slot: "foot", size: 1 },
    { id: "saintoasboots", name: "圣奥长靴", level: 1, quality: 3, image: "圣", type: "boot", slot: "foot", size: 1 },
    { id: "shabakaboots", name: "沙巴克马靴", level: 1, quality: 3, image: "沙", type: "boot", slot: "foot", size: 1 },
    { id: "borderboots", name: "边陲战靴", level: 1, quality: 3, image: "边", type: "boot", slot: "foot", size: 1 },
    { id: "mountainboots", name: "雪山靴", level: 1, quality: 3, image: "雪", type: "boot", slot: "foot", size: 1 },
    { id: "lostboots", name: "失落长靴", level: 1, quality: 3, image: "失", type: "boot", slot: "foot", size: 1 },
    { id: "oasisboots", name: "绿洲马靴", level: 1, quality: 3, image: "绿", type: "boot", slot: "foot", size: 1 },
    { id: "northstarboots", name: "北斗短靴", level: 1, quality: 3, classOnly: ["wlk"], image: "北", type: "boot", slot: "foot", size: 1 },
    { id: "sanderfolly", name: "山德的愚行", level: 1, quality: 3, image: "山", type: "boot", slot: "foot", size: 1 },
    { id: "aldurboots", name: "埃尔多胫甲", level: 1, quality: 3, image: "埃", type: "boot", slot: "foot", size: 1 },
    { id: "infernostride", name: "地狱阔步", level: 1, quality: 3, image: "地", type: "boot", slot: "foot", size: 1 },
    { id: "goblintoes", name: "小妖精脚趾", level: 1, quality: 3, image: "小", type: "boot", slot: "foot", size: 1 },
    { id: "stormtread", name: "沙暴之旅", level: 1, quality: 3, image: "沙", type: "boot", slot: "foot", size: 1 },
    { id: "gorerider", name: "蚀肉骑士", level: 1, quality: 3, image: "蚀", type: "boot", slot: "foot", size: 1 },
    { id: "wartraveller", name: "战争旅者", level: 1, quality: 3, image: "战", type: "boot", slot: "foot", size: 1 },
    { id: "shadowdance", name: "影舞者", level: 1, quality: 3, image: "影", type: "boot", slot: "foot", size: 1 },
    { id: "bloodfeet", name: "血脚", level: 1, quality: 3, image: "血", type: "boot", slot: "foot", size: 1 },
    { id: "warstomp", name: "战争践踏", level: 1, quality: 3, image: "战", type: "boot", slot: "foot", size: 1 },
    { id: "smallcharm", name: "小护身符", level: 1, quality: 1, maxQuality: 1, image: "INV_Misc_Bone_06", type: "charm", slot: "accessory", size: 1 },
    { id: "largecharm", name: "护身符", level: 1, quality: 1, maxQuality: 1, image: "INV_Misc_Bone_07", type: "charm", slot: "accessory", size: 2 },
    { id: "grandcharm", name: "大护身符", level: 1, quality: 1, maxQuality: 1, image: "INV_Misc_Bone_ElfSkull_01", type: "charm", slot: "accessory", size: 3 },
    { id: "clothglove", name: "布手套", level: 1, quality: 0, maxQuality: 2, image: "布", type: "glove", slot: "hand", size: 1, sockets: "sok2" },
    { id: "leatherglove", name: "皮质手套", level: 1, quality: 0, maxQuality: 2, image: "皮", type: "glove", slot: "hand", size: 1, sockets: "sok2" },
    { id: "lightglove", name: "轻型手套", level: 1, quality: 0, maxQuality: 2, image: "轻", type: "glove", slot: "hand", size: 1, sockets: "sok2" },
    { id: "bronzeglove", name: "青铜手甲", level: 1, quality: 0, maxQuality: 2, image: "青", type: "glove", slot: "hand", size: 1, sockets: "sok2" },
    { id: "mediumglove", name: "中型手套", level: 1, quality: 0, maxQuality: 2, image: "中", type: "glove", slot: "hand", size: 1, sockets: "sok2" },
    { id: "ironglove", name: "铁质手套", level: 1, quality: 0, maxQuality: 2, image: "铁", type: "glove", slot: "hand", size: 1, sockets: "sok2" },
    { id: "plateglove", name: "钢制手甲", level: 1, quality: 0, maxQuality: 2, image: "钢", type: "glove", slot: "hand", size: 1, sockets: "sok2" },
    { id: "steadyglove", name: "坚固手套", level: 1, quality: 3, image: "坚", type: "glove", slot: "hand", size: 1 },
    { id: "reaperglove", name: "死神手套", level: 1, quality: 3, image: "死", type: "glove", slot: "hand", size: 1 },
    { id: "ghostglove", name: "幽灵手套", level: 1, quality: 3, image: "幽", type: "glove", slot: "hand", size: 1 },
    { id: "devilglove", name: "阎罗手套", level: 1, quality: 3, image: "阎", type: "glove", slot: "hand", size: 1 },
    { id: "tigerguardglove", name: "虎卫手甲", level: 1, quality: 3, image: "虎", type: "glove", slot: "hand", size: 1 },
    { id: "devilclaw", name: "魔界异爪", level: 1, quality: 3, image: "魔", type: "glove", slot: "hand", size: 1 },
    { id: "dragonguardgloves", name: "龙卫长手套", level: 1, quality: 3, image: "龙", type: "glove", slot: "hand", size: 1 },
    { id: "tigertoothglove", name: "虎齿手套", level: 1, quality: 3, image: "虎", type: "glove", slot: "hand", size: 1 },
    { id: "bulldemongloves", name: "牛魔手甲", level: 1, quality: 3, image: "牛", type: "glove", slot: "hand", size: 1 },
    { id: "draculagrip", name: "德古拉之握", level: 1, quality: 3, image: "德", type: "glove", slot: "hand", size: 1 },
    { id: "layingofhands", name: "手掌的安置", level: 1, quality: 3, image: "手", type: "glove", slot: "hand", size: 1 },
    { id: "shattersteel", name: "碎钢", level: 1, quality: 3, image: "碎", type: "glove", slot: "hand", size: 1 },
    { id: "frostburn", name: "霜燃", level: 1, quality: 3, image: "霜", type: "glove", slot: "hand", size: 1 },
    { id: "valkyriegloves", name: "女武神护手", level: 1, quality: 3, image: "女", type: "glove", slot: "hand", size: 1 },
    { id: "trangoulclaw", name: "塔格奥之爪", level: 1, quality: 3, image: "塔", type: "glove", slot: "hand", size: 1 },
    { id: "bloodfist", name: "血拳", level: 1, quality: 3, image: "血", type: "glove", slot: "hand", size: 1 },
    { id: "deathgrip", name: "死亡之握", level: 1, quality: 3, image: "死", type: "glove", slot: "hand", size: 1 },
    { id: "chanceguard", name: "运气守护", level: 1, quality: 3, image: "运", type: "glove", slot: "hand", size: 1 },
    { id: "handofincenerator", name: "焚毁者之手", level: 1, quality: 3, image: "焚", type: "glove", slot: "hand", size: 1 },
    { id: "clothcap", name: "布帽", level: 1, quality: 0, maxQuality: 2, image: "布", type: "helm", slot: "head", size: 1, sockets: "sok3" },
    { id: "leathercap", name: "皮帽", level: 1, quality: 0, maxQuality: 2, image: "皮", type: "helm", slot: "head", size: 1, sockets: "sok3" },
    { id: "lightcap", name: "轻型头盔", level: 1, quality: 0, maxQuality: 2, image: "轻", type: "helm", slot: "head", size: 1, sockets: "sok3" },
    { id: "bronzecap", name: "青铜头盔", level: 1, quality: 0, maxQuality: 2, image: "青", type: "helm", slot: "head", size: 1, fixedAffix: { ["xdr1"]: 0 }, sockets: "sok3" },
    { id: "mediumcap", name: "中型头盔", level: 1, quality: 0, maxQuality: 2, image: "中", type: "helm", slot: "head", size: 1, sockets: "sok3" },
    { id: "ironcap", name: "铁质头盔", level: 1, quality: 0, maxQuality: 2, image: "铁", type: "helm", slot: "head", size: 1, sockets: "sok3" },
    { id: "platecap", name: "板甲头盔", level: 1, quality: 0, maxQuality: 2, image: "板", type: "helm", slot: "head", size: 1, sockets: "sok3" },
    { id: "magiccap", name: "魔法头盔", level: 1, quality: 3, image: "魔", type: "helm", slot: "head", size: 1, fixedAffix: { ["xdr1"]: 0 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "warlockcap", name: "道士头盔", level: 1, quality: 3, image: "道", type: "helm", slot: "head", size: 1, fixedAffix: { ["xdr1"]: 0 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "skullcap", name: "骷髅头盔", level: 1, quality: 3, image: "骷", type: "helm", slot: "head", size: 1, fixedAffix: { ["xdr1"]: 0.5 } },
    { id: "memorycap", name: "记忆头盔", level: 1, quality: 3, image: "记", type: "helm", slot: "head", size: 1, fixedAffix: { ["xdr1"]: 0.5 } },
    { id: "prayercap", name: "祈祷头盔", level: 1, quality: 3, image: "祈", type: "helm", slot: "head", size: 1, fixedAffix: { ["xdr1"]: 0.7 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "blackironcap", name: "黑铁头盔", level: 1, quality: 3, image: "黑", type: "helm", slot: "head", size: 1, fixedAffix: { ["xdr1"]: 2 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "mysteriouscap", name: "神秘头盔", level: 1, quality: 3, image: "神", type: "helm", slot: "head", size: 1, fixedAffix: { ["xdr1"]: 1.7 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "harbingerhelm", name: "先驱者战盔", level: 1, quality: 3, image: "先", type: "helm", slot: "head", size: 1 },
    { id: "glintswordwill", name: "辉剑的意志", level: 1, quality: 3, classOnly: ["warr"], image: "辉", type: "helm", slot: "head", size: 1 },
    { id: "flamefeatherwisdom", name: "焰翎的智慧", level: 1, quality: 3, classOnly: ["mage"], image: "焰", type: "helm", slot: "head", size: 1 },
    { id: "azurecloudmeditation", name: "皓云的冥思", level: 1, quality: 3, classOnly: ["wlk"], image: "皓", type: "helm", slot: "head", size: 1 },
    { id: "flickeringflame", name: "摇曳之火", level: 1, quality: 3, image: "摇", type: "helm", slot: "head", size: 1 },
    { id: "dream", name: "梦境", level: 1, quality: 3, image: "梦", type: "helm", slot: "head", size: 1 },
    { id: "dilirium", name: "迪勒瑞姆", level: 1, quality: 3, image: "迪", type: "helm", slot: "head", size: 1 },
    { id: "faceofjiron", name: "吉永之脸", level: 1, quality: 3, image: "吉", type: "helm", slot: "head", size: 1 },
    { id: "crownofage", name: "年纪之冠", level: 1, quality: 3, image: "年", type: "helm", slot: "head", size: 1 },
    { id: "griffoneye", name: "格力风之眼", level: 1, quality: 3, image: "格", type: "helm", slot: "head", size: 1 },
    { id: "wolfhowl", name: "狼嗷", level: 1, quality: 3, image: "狼", type: "helm", slot: "head", size: 1 },
    { id: "haleriumcrest", name: "邪角之冠", level: 1, quality: 3, image: "邪", type: "helm", slot: "head", size: 1 },
    { id: "commonnecklace", name: "项链", level: 1, quality: 1, maxQuality: 2, image: "INV_Jewelry_Necklace_21", type: "necklace", slot: "neck", size: 1, sockets: "sok1" },
    { id: "goldnecklace", name: "金项链", level: 2, quality: 3, image: "金", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["xdmg1"]: 0, ["doge1"]: 0 } },
    { id: "ordinarynecklace", name: "传统项链", level: 3, quality: 3, image: "传", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["hit1"]: 0 } },
    { id: "topaznecklace", name: "黄色水晶项链", level: 13, quality: 3, image: "黄", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["spi1"]: 0 } },
    { id: "sandalnecklace", name: "黑檀项链", level: 13, quality: 3, image: "黑", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["int1"]: 0 } },
    { id: "blackcrystalnecklace", name: "黑色水晶项链", level: 13, quality: 3, image: "黑", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["spi1"]: 0 } },
    { id: "whitetigernecklace", name: "白色虎齿项链", level: 11, quality: 3, image: "白", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["xdr1"]: 0, ["mdoge1"]: 0 }, randomAffix: { ["fres1"]: 0, ["tres1"]: 0, ["hres1"]: 0, ["pres1"]: 0 } },
    { id: "whitegoldnecklace", name: "白金项链", level: 10, quality: 3, image: "白", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["int1"]: 0 } },
    { id: "lampnecklace", name: "灯笼项链", level: 18, quality: 3, image: "灯", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["str1"]: 0, ["mdoge1"]: 0 } },
    { id: "ambernecklace", name: "琥珀项链", level: 17, quality: 3, image: "琥", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["int1"]: 0 } },
    { id: "devilnecklace", name: "魔鬼项链", level: 17, quality: 3, image: "魔", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["str1"]: 0 } },
    { id: "pheonixnecklace", name: "凤凰明珠", level: 17, quality: 3, image: "凤", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["spi1"]: 0 } },
    { id: "blueemeraldnecklace", name: "蓝翡翠项链", level: 23, quality: 3, image: "蓝", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["str1"]: 0 } },
    { id: "bambooflute", name: "竹笛", level: 24, quality: 3, image: "竹", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["spi1"]: 0 } },
    { id: "maganifier", name: "放大镜", level: 24, quality: 3, image: "放", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["int1"]: 0 } },
    { id: "ghostnecklace", name: "幽灵项链", level: 24, quality: 3, image: "幽", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["str1"]: 0 } },
    { id: "greennecklace", name: "绿色项链", level: 39, quality: 3, image: "绿", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["str1"]: 0 } },
    { id: "soulnecklace", name: "灵魂项链", level: 23, quality: 3, image: "灵", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["spi1"]: 0, ["hit1"]: 0 } },
    { id: "devilbell", name: "恶魔铃铛", level: 27, quality: 3, image: "恶", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["int1"]: 0, ["mhit1"]: 0 } },
    { id: "demonbloodnecklace", name: "魔血项链", level: 33, quality: 3, image: "魔", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["str1"]: 0, ["int1"]: 0 } },
    { id: "prismademonnecklace", name: "虹魔项链", level: 33, quality: 3, image: "虹", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["int1"]: 0 } },
    { id: "breezenecklace", name: "狂风项链", level: 19, quality: 3, image: "狂", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["str1"]: 0, ["spd1"]: 0 } },
    { id: "dodgenecklace", name: "躲避项链", level: 12, quality: 3, image: "躲", type: "necklace", slot: "neck", size: 1, fixedAffix: { ["doge1"]: 0 } },
    { id: "marakelopscope", name: "天魔神镜", level: 1, quality: 3, image: "天", type: "necklace", slot: "neck", size: 1 },
    { id: "rageoftyrant", name: "暴君之怒", level: 1, quality: 3, image: "暴", type: "necklace", slot: "neck", size: 1 },
    { id: "risingsun", name: "旭日东升", level: 1, quality: 3, image: "旭", type: "necklace", slot: "neck", size: 1 },
    { id: "metalgrid", name: "金属网格", level: 1, quality: 3, image: "金", type: "necklace", slot: "neck", size: 1 },
    { id: "clothpants", name: "轻便长裤", level: 1, quality: 0, maxQuality: 2, image: "轻", type: "pant", slot: "leg", size: 1, sockets: "sok3" },
    { id: "leatherpants", name: "皮腿甲", level: 1, quality: 0, maxQuality: 2, image: "皮", type: "pant", slot: "leg", size: 1, sockets: "sok3" },
    { id: "lightpants", name: "轻型腿甲", level: 1, quality: 0, maxQuality: 2, image: "轻", type: "pant", slot: "leg", size: 1, sockets: "sok3" },
    { id: "bronzepants", name: "青铜腿甲", level: 1, quality: 0, maxQuality: 2, image: "青", type: "pant", slot: "leg", size: 1, sockets: "sok3" },
    { id: "mediumpants", name: "中型腿甲", level: 1, quality: 0, maxQuality: 2, image: "中", type: "pant", slot: "leg", size: 1, sockets: "sok3" },
    { id: "ironpants", name: "铁质腿甲", level: 1, quality: 0, maxQuality: 2, image: "铁", type: "pant", slot: "leg", size: 1, sockets: "sok3" },
    { id: "platepants", name: "钢制腿甲", level: 1, quality: 0, maxQuality: 2, image: "钢", type: "pant", slot: "leg", size: 1, sockets: "sok3" },
    { id: "zumapants", name: "祖玛护腿", level: 1, quality: 3, image: "祖", type: "pant", slot: "leg", size: 1 },
    { id: "demonpants", name: "恶魔长裤", level: 1, quality: 3, image: "恶", type: "pant", slot: "leg", size: 1 },
    { id: "bitchpant", name: "比奇马裤", level: 1, quality: 3, image: "比", type: "pant", slot: "leg", size: 1 },
    { id: "monchonpants", name: "盟重腿甲", level: 1, quality: 3, image: "盟", type: "pant", slot: "leg", size: 1 },
    { id: "dragonkinpants", name: "龙族腿甲", level: 1, quality: 3, image: "龙", type: "pant", slot: "leg", size: 1 },
    { id: "crusadepants", name: "征伐绑腿", level: 1, quality: 3, image: "征", type: "pant", slot: "leg", size: 1 },
    { id: "lostpants", name: "失乐腿甲", level: 1, quality: 3, image: "失", type: "pant", slot: "leg", size: 1 },
    { id: "avalanchepants", name: "雪崩长裤", level: 1, quality: 3, image: "雪", type: "pant", slot: "leg", size: 1 },
    { id: "undeaddemonpants", name: "尸魔腿甲", level: 1, quality: 3, image: "尸", type: "pant", slot: "leg", size: 1 },
    { id: "faudpox", name: "恶疮马裤", level: 1, quality: 3, image: "恶", type: "pant", slot: "leg", size: 1 },
    { id: "deathbargin", name: "冥神的交易", level: 1, quality: 3, image: "冥", type: "pant", slot: "leg", size: 1 },
    { id: "stonepants", name: "石像长裤", level: 1, quality: 3, image: "石", type: "pant", slot: "leg", size: 1 },
    { id: "defilerpants", name: "污染者腿甲", level: 1, quality: 3, image: "污", type: "pant", slot: "leg", size: 1 },
    { id: "serpentwanderer", name: "蛇谷游荡者", level: 1, quality: 3, image: "蛇", type: "pant", slot: "leg", size: 1 },
    { id: "diggerdepth", name: "矿工裤", level: 1, quality: 3, image: "矿", type: "pant", slot: "leg", size: 1 },
    { id: "gehenas", name: "基赫纳斯", level: 1, quality: 3, image: "基", type: "pant", slot: "leg", size: 1 },
    { id: "cunningpants", name: "狡诈长裤", level: 1, quality: 3, image: "狡", type: "pant", slot: "leg", size: 1 },
    { id: "captainspants", name: "队长腿甲", level: 1, quality: 3, image: "队", type: "pant", slot: "leg", size: 1 },
    { id: "shadowcoil", name: "阴影缠结", level: 1, quality: 3, image: "阴", type: "pant", slot: "leg", size: 1 },
    { id: "clothpauldron", name: "布衬肩", level: 1, quality: 0, maxQuality: 2, image: "布", type: "pauldron", slot: "shoulder", size: 1, sockets: "sok2" },
    { id: "leatherpauldron", name: "硬皮肩甲", level: 1, quality: 0, maxQuality: 2, image: "硬", type: "pauldron", slot: "shoulder", size: 1, sockets: "sok2" },
    { id: "lightpauldron", name: "轻型护肩", level: 1, quality: 0, maxQuality: 2, image: "轻", type: "pauldron", slot: "shoulder", size: 1, sockets: "sok2" },
    { id: "bronzepauldron", name: "青铜肩甲", level: 1, quality: 0, maxQuality: 2, image: "青", type: "pauldron", slot: "shoulder", size: 1, sockets: "sok2" },
    { id: "mediumpauldron", name: "中型护肩", level: 1, quality: 0, maxQuality: 2, image: "中", type: "pauldron", slot: "shoulder", size: 1, sockets: "sok2" },
    { id: "ironpauldron", name: "铁质肩甲", level: 1, quality: 0, maxQuality: 2, image: "铁", type: "pauldron", slot: "shoulder", size: 1, sockets: "sok2" },
    { id: "platepauldron", name: "钢制肩胄", level: 1, quality: 0, maxQuality: 2, image: "钢", type: "pauldron", slot: "shoulder", size: 1, sockets: "sok2" },
    { id: "ormapauldron", name: "奥马垫肩", level: 1, quality: 3, image: "奥", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "neelpauldron", name: "尼耳护肩", level: 1, quality: 3, image: "尼", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "whitesunpauldron", name: "白日肩甲", level: 1, quality: 3, image: "白", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "ruinspauldron", name: "遗迹肩甲", level: 1, quality: 3, image: "遗", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "demondragonpauldron", name: "魔龙护肩", level: 1, quality: 3, image: "魔", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "blooddemonpauldron", name: "血魔肩甲", level: 1, quality: 3, image: "血", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "thoriumpauldron", name: "瑟银肩甲", level: 1, quality: 3, image: "瑟", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "empirepauldron", name: "帝国肩甲", level: 1, quality: 3, image: "帝", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "bonedemonpauldrons", name: "骨魔肩甲", level: 1, quality: 3, image: "骨", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "homingpads", name: "归家垫肩", level: 1, quality: 3, image: "归", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "corpsekingpauldron", name: "尸王肩甲", level: 1, quality: 3, image: "尸", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "betrayerpauldron", name: "叛教者护肩", level: 1, quality: 3, image: "叛", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "deathguard", name: "死神守护", level: 1, quality: 3, image: "死", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "corpsewhisper", name: "尸语者护肩", level: 1, quality: 3, image: "尸", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "lifesiphoning", name: "生命虹吸肩甲", level: 1, quality: 3, image: "生", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "channelingpauldron", name: "导能护肩", level: 1, quality: 3, image: "导", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "ancientwrath", name: "远古之怒肩甲", level: 1, quality: 3, image: "远", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "vileguard", name: "邪魔守卫护肩", level: 1, quality: 3, image: "邪", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "sevensinspauldron", name: "七罪护肩", level: 1, quality: 3, image: "七", type: "pauldron", slot: "shoulder", size: 1 },
    { id: "commonring", name: "戒指", level: 1, quality: 1, maxQuality: 2, image: "INV_Jewelry_Ring_02", type: "ring", slot: "finger", size: 1, sockets: "sok1" },
    { id: "bronzering", name: "古铜戒指", level: 1, quality: 3, image: "古", type: "ring", slot: "finger", size: 1 },
    { id: "glassring", name: "玻璃戒指", level: 1, quality: 3, image: "玻", type: "ring", slot: "finger", size: 1 },
    { id: "hexagonring", name: "六角戒指", level: 1, quality: 3, image: "六", type: "ring", slot: "finger", size: 1 },
    { id: "hornring", name: "牛角戒指", level: 1, quality: 3, image: "牛", type: "ring", slot: "finger", size: 1 },
    { id: "saphirering", name: "蓝色水晶戒指", level: 1, quality: 3, image: "蓝", type: "ring", slot: "finger", size: 1 },
    { id: "lifering", name: "生命戒指", level: 1, quality: 3, image: "生", type: "ring", slot: "finger", size: 1 },
    { id: "pearlring", name: "珍珠戒指", level: 1, quality: 3, image: "珍", type: "ring", slot: "finger", size: 1 },
    { id: "blackcrystalring", name: "黑色水晶戒指", level: 1, quality: 3, image: "黑", type: "ring", slot: "finger", size: 1 },
    { id: "snakeeyering", name: "蛇眼戒指", level: 1, quality: 3, image: "蛇", type: "ring", slot: "finger", size: 1 },
    { id: "goldring", name: "金戒指", level: 1, quality: 3, image: "金", type: "ring", slot: "finger", size: 1 },
    { id: "moralring", name: "道德戒指", level: 1, quality: 3, image: "道", type: "ring", slot: "finger", size: 1 },
    { id: "charmring", name: "魅力戒指", level: 1, quality: 3, image: "魅", type: "ring", slot: "finger", size: 1 },
    { id: "demoslayerring", name: "降妖除魔戒指", level: 1, quality: 3, image: "降", type: "ring", slot: "finger", size: 1 },
    { id: "platiniumring", name: "铂金戒指", level: 1, quality: 3, image: "铂", type: "ring", slot: "finger", size: 1 },
    { id: "skullring", name: "骷髅戒指", level: 1, quality: 3, image: "骷", type: "ring", slot: "finger", size: 1 },
    { id: "coralring", name: "珊瑚戒指", level: 1, quality: 3, image: "珊", type: "ring", slot: "finger", size: 1 },
    { id: "prismademonring", name: "虹魔戒指", level: 1, quality: 3, image: "虹", type: "ring", slot: "finger", size: 1 },
    { id: "rubyring", name: "红宝石戒指", level: 1, quality: 3, image: "红", type: "ring", slot: "finger", size: 1 },
    { id: "dragonring", name: "龙之戒指", level: 1, quality: 3, image: "龙", type: "ring", slot: "finger", size: 1 },
    { id: "breezering", name: "狂风戒指", level: 1, quality: 3, image: "狂", type: "ring", slot: "finger", size: 1 },
    { id: "titanring", name: "泰坦戒指", level: 1, quality: 3, image: "泰", type: "ring", slot: "finger", size: 1 },
    { id: "valorring", name: "力量戒指", level: 1, quality: 3, image: "力", type: "ring", slot: "finger", size: 1 },
    { id: "purplesnail", name: "紫碧螺", level: 1, quality: 3, image: "紫", type: "ring", slot: "finger", size: 1 },
    { id: "mysteriousring", name: "神秘戒指", level: 1, quality: 3, image: "神", type: "ring", slot: "finger", size: 1 },
    { id: "nummingring", name: "麻痹戒指", level: 1, quality: 3, image: "麻", type: "ring", slot: "finger", size: 1 },
    { id: "contractingring", name: "收缩戒指", level: 1, quality: 3, image: "收", type: "ring", slot: "finger", size: 1 },
    { id: "woodsword", name: "木剑", level: 1, quality: 0, maxQuality: 2, description: "木剑描述", image: "INV_Sword_BloodElf_03", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 0 }, sockets: "sok3" },
    { id: "dagger", name: "匕首", level: 1, quality: 0, maxQuality: 2, description: "匕首描述", image: "INV_Weapon_ShortBlade_14", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: -0.2, ["spd1"]: 0 }, sockets: "sok2" },
    { id: "ebonywoodsword", name: "乌木剑", level: 1, quality: 0, maxQuality: 2, description: "乌木剑描述", image: "INV_Sword_22", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 0.2 }, randomAffix: { ["fdmg1"]: 0, ["tdmg1"]: 0, ["hdmg1"]: 0, ["pdmg1"]: 0 }, sockets: "sok4" },
    { id: "bronzesword", name: "青铜剑", level: 5, quality: 0, maxQuality: 2, description: "青铜剑描述", image: "INV_Sword_20", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 0.3 }, sockets: "sok4" },
    { id: "shortsword", name: "短剑", level: 10, quality: 0, maxQuality: 2, description: "短剑描述", image: "INV_Sword_23", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 0.4 }, sockets: "sok3" },
    { id: "ironsword", name: "弯刀", level: 10, quality: 0, maxQuality: 2, description: "铁剑描述", image: "INV_Sword_24", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 0.5 }, sockets: "sok5" },
    { id: "bronzeaxe", name: "青铜斧", level: 11, quality: 0, maxQuality: 2, description: "青铜斧描述", image: "INV_Axe_01", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 0.6 }, sockets: "sok5" },
    { id: "mattock", name: "鹤嘴锄", level: 11, quality: 3, description: "鹤嘴锄描述", image: "⛏", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 0, ["luck1"]: 0 } },
    { id: "rakshasa", name: "罗刹", level: 15, quality: 3, description: "罗刹描述", image: "🪓", type: "weapon", slot: "arms", size: 2, fixedAffix: { ["xdmg1rev"]: 0.5, ["curs1"]: 0 } },
    { id: "eightwilderness", name: "八荒", level: 15, quality: 3, classOnly: ["warr"], description: "八荒描述", image: "INV_Sword_137", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 2 } },
    { id: "overwind", name: "凌风", level: 19, quality: 3, classOnly: ["warr"], description: "凌风描述", image: "INV_Sword_122", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 2.1 } },
    { id: "brokensoul", name: "破魂", level: 20, quality: 3, classOnly: ["warr"], description: "破魂", image: "INV_Axe_66", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 2.1, ["hit1"]: 0 } },
    { id: "horsecleaver", name: "斩马刀", level: 20, quality: 3, classOnly: ["warr"], description: "斩马刀", image: "INV_Sword_119", type: "weapon", slot: "arms", size: 2, fixedAffix: { ["xdmg1"]: 2.2 } },
    { id: "shura", name: "修罗", level: 22, quality: 3, classOnly: ["warr"], description: "修罗", image: "INV_Sword_138", type: "weapon", slot: "arms", size: 2, fixedAffix: { ["xdmg1"]: 2.5 } },
    { id: "condensefrost", name: "凝霜", level: 22, quality: 3, classOnly: ["warr"], description: "凝霜", image: "INV_Sword_120", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 2.6 } },
    { id: "inferno", name: "炼狱", level: 22, quality: 3, classOnly: ["warr"], description: "炼狱", image: "INV_Sword_128", type: "weapon", slot: "arms", size: 2, fixedAffix: { ["xdmg1"]: 3 } },
    { id: "wellmoon", name: "井中月", level: 28, quality: 3, classOnly: ["warr"], description: "井中月", image: "INV_Sword_156", type: "weapon", slot: "arms", size: 2, fixedAffix: { ["xdmg1"]: 3.2 } },
    { id: "judgestaff", name: "裁决之杖", level: 30, quality: 3, classOnly: ["warr"], description: "裁决之杖描述", image: "INV_Staff_102", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 3.8 } },
    { id: "dragonslayer", name: "屠龙刀", level: 35, quality: 4, classOnly: ["warr"], description: "屠龙刀描述", image: "INV_Axe_116", type: "weapon", slot: "arms", size: 2, fixedAffix: { ["xdmg1"]: 4 } },
    { id: "halfmoon", name: "半月", level: 15, quality: 3, classOnly: ["wlk"], description: "半月描述", image: "🗡️", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 1.5, ["spi1"]: 0 }, randomAffix: { ["hdmg1"]: 0, ["pdmg1"]: 0 } },
    { id: "subduedemon", name: "降魔", level: 15, quality: 3, classOnly: ["wlk"], description: "降魔描述", image: "🗡️", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 1.5, ["spi1"]: 0.5, ["hit1"]: 0 } },
    { id: "silverserpent", name: "银蛇", level: 15, quality: 3, classOnly: ["wlk"], description: "银蛇描述", image: "🗡️", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 2, ["spi1"]: 0.5, ["mhit1"]: 0 } },
    { id: "nullstaff", name: "无极棍", level: 15, quality: 3, classOnly: ["wlk"], description: "无极棍描述", image: "🗡️", type: "weapon", slot: "arms", size: 2, fixedAffix: { ["xdmg1"]: 1, ["spi1"]: 2.2 }, randomAffix: { ["hdmg1"]: 0.5, ["pdmg1"]: 0.5 } },
    { id: "dragonsword", name: "龙纹剑", level: 35, quality: 4, classOnly: ["wlk"], description: "龙纹剑描述", image: "🗡️", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 2.5, ["spi1"]: 2, ["hit1"]: 0 } },
    { id: "seasoul", name: "海魂", level: 15, quality: 3, classOnly: ["mage"], description: "海魂描述", image: "🗡️", type: "weapon", slot: "arms", size: 2, fixedAffix: { ["xdmg1"]: 0.5 }, randomAffix: { ["fdmg1"]: 0, ["tdmg1"]: 0 } },
    { id: "siezemoon", name: "偃月", level: 35, quality: 3, classOnly: ["mage"], description: "偃月描述", image: "🗡️", type: "weapon", slot: "arms", size: 2, fixedAffix: { ["xdmg1"]: 0.7 }, randomAffix: { ["fdmg1"]: 1, ["tdmg1"]: 1 } },
    { id: "magicstaff", name: "魔杖", level: 35, quality: 3, classOnly: ["mage"], description: "魔杖描述", image: "🗡️", type: "weapon", slot: "arms", size: 2, fixedAffix: { ["xdmg1"]: 1.2 }, randomAffix: { ["fdmg1"]: 2, ["tdmg1"]: 2 } },
    { id: "blooddrink", name: "血饮", level: 35, quality: 3, classOnly: ["mage"], description: "血饮描述", image: "🗡️", type: "weapon", slot: "arms", size: 1, fixedAffix: { ["xdmg1"]: 2.2, ["hit1"]: 1, ["mhit1"]: 0 }, randomAffix: { ["fdmg1"]: 2, ["tdmg1"]: 2 } },
    { id: "bonescepter", name: "骨玉权杖", level: 35, quality: 4, classOnly: ["mage"], description: "骨玉权杖描述", image: "🗡️", type: "weapon", slot: "arms", size: 2, fixedAffix: { ["xdmg1"]: 1.7 }, randomAffix: { ["fdmg1"]: 3, ["tdmg1"]: 3 } },
    { id: "prismademonstaff", name: "虹魔法杖", level: 1, quality: 3, image: "虹", type: "weapon", slot: "arms", size: 2 },
    { id: "dragongodsword", name: "神龙剑", level: 1, quality: 3, image: "神", type: "weapon", slot: "arms", size: 1 },
    { id: "demonbloodvessel", name: "魔血法器", level: 1, quality: 3, image: "魔", type: "weapon", slot: "arms", size: 1 },
    { id: "renmoonsaber", name: "赤月弯刀", level: 1, quality: 3, image: "赤", type: "weapon", slot: "arms", size: 1 },
    { id: "revelation", name: "启示录", level: 1, quality: 3, classOnly: ["mage"], image: "启", type: "weapon", slot: "arms", size: 1 },
    { id: "ragecleave", name: "怒斩", level: 1, quality: 3, classOnly: ["warr"], image: "怒", type: "weapon", slot: "arms", size: 1 },
    { id: "dragontooth", name: "龙牙", level: 1, quality: 3, classOnly: ["mage"], image: "龙", type: "weapon", slot: "arms", size: 1 },
    { id: "elysianfan", name: "逍遥扇", level: 1, quality: 3, classOnly: ["wlk"], image: "逍", type: "weapon", slot: "arms", size: 1 },
    { id: "layingserpent", name: "卧龙", level: 1, quality: 3, image: "卧", type: "weapon", slot: "arms", size: 1 },
    { id: "clothwrist", name: "白布护臂", level: 1, quality: 0, maxQuality: 2, image: "白", type: "bracelet", slot: "wrist", size: 1, sockets: "sok2" },
    { id: "leatherwrist", name: "软皮臂甲", level: 1, quality: 0, maxQuality: 2, image: "软", type: "bracelet", slot: "wrist", size: 1, sockets: "sok2" },
    { id: "lightwrist", name: "轻型手镯", level: 1, quality: 0, maxQuality: 2, image: "轻", type: "bracelet", slot: "wrist", size: 1, sockets: "sok2" },
    { id: "bronzewrist", name: "青铜手镯", level: 1, quality: 0, maxQuality: 2, image: "青", type: "bracelet", slot: "wrist", size: 1, sockets: "sok2" },
    { id: "mediumwrist", name: "中型手镯", level: 1, quality: 0, maxQuality: 2, image: "中", type: "bracelet", slot: "wrist", size: 1, sockets: "sok2" },
    { id: "ironwrist", name: "铁护腕", level: 1, quality: 0, maxQuality: 2, image: "铁", type: "bracelet", slot: "wrist", size: 1, sockets: "sok2" },
    { id: "platewrist", name: "钢制臂甲", level: 1, quality: 0, maxQuality: 2, image: "钢", type: "bracelet", slot: "wrist", size: 1, sockets: "sok2" },
    { id: "womawrist", name: "沃玛手镯", level: 1, quality: 3, image: "沃", type: "bracelet", slot: "wrist", size: 1 },
    { id: "ironbracelet", name: "铁手镯", level: 1, quality: 3, image: "铁", type: "bracelet", slot: "wrist", size: 1 },
    { id: "smallbracelet", name: "小手镯", level: 1, quality: 3, image: "小", type: "bracelet", slot: "wrist", size: 1 },
    { id: "silverbracelet", name: "银手镯", level: 1, quality: 3, image: "银", type: "bracelet", slot: "wrist", size: 1 },
    { id: "largebracelet", name: "大手镯", level: 1, quality: 3, image: "大", type: "bracelet", slot: "wrist", size: 1 },
    { id: "steelbracelet", name: "钢手镯", level: 1, quality: 3, image: "钢", type: "bracelet", slot: "wrist", size: 1 },
    { id: "magicbracelet", name: "魔法手镯", level: 1, quality: 3, image: "魔", type: "bracelet", slot: "wrist", size: 1 },
    { id: "sharpelbracelet", name: "夏普儿手镯", level: 1, quality: 3, image: "夏", type: "bracelet", slot: "wrist", size: 1 },
    { id: "antijinxbracelet", name: "辟邪手镯", level: 1, quality: 3, image: "辟", type: "bracelet", slot: "wrist", size: 1 },
    { id: "warlockbracelet", name: "道士手镯", level: 1, quality: 3, image: "道", type: "bracelet", slot: "wrist", size: 1 },
    { id: "blacksandalbracelet", name: "黑檀手镯", level: 1, quality: 3, image: "黑", type: "bracelet", slot: "wrist", size: 1 },
    { id: "powerbracelet", name: "魔力手镯", level: 1, quality: 3, image: "魔", type: "bracelet", slot: "wrist", size: 1 },
    { id: "goldbracelet", name: "金手镯", level: 1, quality: 3, image: "金", type: "bracelet", slot: "wrist", size: 1 },
    { id: "spiritbracelet", name: "心灵手镯", level: 1, quality: 3, image: "心", type: "bracelet", slot: "wrist", size: 1 },
    { id: "tripleeyebracelet", name: "三眼手镯", level: 1, quality: 3, image: "三", type: "bracelet", slot: "wrist", size: 1 },
    { id: "sebelbracelet", name: "思贝儿手镯", level: 1, quality: 3, image: "思", type: "bracelet", slot: "wrist", size: 1 },
    { id: "dragonbracelet", name: "龙之手镯", level: 1, quality: 3, image: "龙", type: "bracelet", slot: "wrist", size: 1 },
    { id: "knightbracelet", name: "骑士手镯", level: 1, quality: 3, image: "骑", type: "bracelet", slot: "wrist", size: 1 },
    { id: "demonbloodbracelet", name: "魔血手镯", level: 1, quality: 3, image: "魔", type: "bracelet", slot: "wrist", size: 1 },
    { id: "rune1", name: "破碎金灵珠", level: 7, quality: 0, image: "INV_Elemental_Mote_Nether", type: "rune", slot: "socket", size: 1, fixedAffix: { ["xdmg1"]: 0 } },
    { id: "rune2", name: "破碎木灵珠", level: 7, quality: 0, image: "INV_Elemental_Mote_Life01", type: "rune", slot: "socket", size: 1, fixedAffix: { ["hdmg1"]: 0 } },
    { id: "rune3", name: "破碎水灵珠", level: 7, quality: 0, image: "INV_Elemental_Mote_Water01", type: "rune", slot: "socket", size: 1, fixedAffix: { ["tdmg1"]: 0 } },
    { id: "rune4", name: "破碎火灵珠", level: 7, quality: 0, image: "INV_Elemental_Mote_Fire01", type: "rune", slot: "socket", size: 1, fixedAffix: { ["fdmg1"]: 0 } },
    { id: "rune5", name: "破碎土灵珠", level: 7, quality: 0, image: "INV_Elemental_Mote_Earth01", type: "rune", slot: "socket", size: 1, fixedAffix: { ["pdmg1"]: 0 } },
    { id: "rune6", name: "开裂金灵珠", level: 14, quality: 1, image: "INV_Elemental_Primal_Nether", type: "rune", slot: "socket", size: 1, fixedAffix: { ["xdr1"]: 0 } },
    { id: "rune7", name: "开裂木灵珠", level: 14, quality: 1, image: "INV_Elemental_Primal_Life", type: "rune", slot: "socket", size: 1, fixedAffix: { ["hdr1"]: 0 } },
    { id: "rune8", name: "开裂水灵珠", level: 14, quality: 1, image: "INV_Elemental_Primal_Water", type: "rune", slot: "socket", size: 1, fixedAffix: { ["tdr1"]: 0 } },
    { id: "rune9", name: "开裂火灵珠", level: 14, quality: 1, image: "INV_Elemental_Primal_Fire", type: "rune", slot: "socket", size: 1, fixedAffix: { ["fdr1"]: 0 } },
    { id: "rune10", name: "开裂土灵珠", level: 14, quality: 1, image: "INV_Elemental_Primal_Earth", type: "rune", slot: "socket", size: 1, fixedAffix: { ["pdr1"]: 0 } },
    { id: "rune11", name: "金灵珠", level: 21, quality: 2, image: "INV_ELEMENTAL_CRYSTAL_EARTH", type: "rune", slot: "socket", size: 1, fixedAffix: { ["xed1"]: 0 } },
    { id: "rune12", name: "木灵珠", level: 21, quality: 2, image: "INV_Elemental_Crystal_Life", type: "rune", slot: "socket", size: 1, fixedAffix: { ["hed1"]: 0 } },
    { id: "rune13", name: "水灵珠", level: 21, quality: 2, image: "INV_Elemental_Crystal_Water", type: "rune", slot: "socket", size: 1, fixedAffix: { ["ted1"]: 0 } },
    { id: "rune14", name: "火灵珠", level: 21, quality: 2, image: "INV_Elemental_Crystal_Fire", type: "rune", slot: "socket", size: 1, fixedAffix: { ["fed1"]: 0 } },
    { id: "rune15", name: "土灵珠", level: 21, quality: 2, image: "INV_Elemental_Crystal_Air", type: "rune", slot: "socket", size: 1, fixedAffix: { ["ped1"]: 0 } },
    { id: "rune16", name: "无瑕金灵珠", level: 28, quality: 3, image: "INV_ELEMENTAL_ETERNAL_EARTH", type: "rune", slot: "socket", size: 1, fixedAffix: { ["xres1"]: 0 } },
    { id: "rune17", name: "无瑕木灵珠", level: 28, quality: 3, image: "INV_Elemental_Eternal_Life", type: "rune", slot: "socket", size: 1, fixedAffix: { ["hres1"]: 0 } },
    { id: "rune18", name: "无瑕水灵珠", level: 28, quality: 3, image: "INV_Elemental_Eternal_Water", type: "rune", slot: "socket", size: 1, fixedAffix: { ["tres1"]: 0 } },
    { id: "rune19", name: "无瑕火灵珠", level: 28, quality: 3, image: "INV_Elemental_Eternal_Fire", type: "rune", slot: "socket", size: 1, fixedAffix: { ["fres1"]: 0 } },
    { id: "rune20", name: "无瑕土灵珠", level: 28, quality: 3, image: "INV_Elemental_Eternal_Air", type: "rune", slot: "socket", size: 1, fixedAffix: { ["pres1"]: 0 } },
    { id: "rune21", name: "完美金灵珠", level: 35, quality: 4, image: "INV_Jewelcrafting_Gem_15", type: "rune", slot: "socket", size: 1, fixedAffix: { ["xlr1"]: 0 } },
    { id: "rune22", name: "完美木灵珠", level: 35, quality: 4, image: "INV_Jewelcrafting_Gem_13", type: "rune", slot: "socket", size: 1, fixedAffix: { ["hlr1"]: 0 } },
    { id: "rune23", name: "完美水灵珠", level: 35, quality: 4, image: "INV_Jewelcrafting_Gem_17", type: "rune", slot: "socket", size: 1, fixedAffix: { ["tlr1"]: 0 } },
    { id: "rune24", name: "完美火灵珠", level: 35, quality: 4, image: "INV_Jewelcrafting_Gem_16", type: "rune", slot: "socket", size: 1, fixedAffix: { ["flr1"]: 0 } },
    { id: "rune25", name: "完美土灵珠", level: 35, quality: 4, image: "INV_Jewelcrafting_Gem_14", type: "rune", slot: "socket", size: 1, fixedAffix: { ["plr1"]: 0 } },
    { id: "infinity", name: "无限", level: 1, quality: 3, image: "无", type: "runeword", slot: "inherit", size: 1, fixedAffix: { ["killbclv1"]: 0, ["spd1"]: 0, ["tlr1"]: 0 }, randomAffix: { ["xed1"]: 0, ["fed1"]: 0, ["ted1"]: 0, ["hed1"]: 0, ["ped1"]: 0 }, affixCount: 1, excludeAffix: ["sok1", "sok2", "sok3", "sok4", "sok5", "rw1"], rwTypes: ["weapon"], rwOrder: ["rune23", "rune17", "rune23", "rune18"] },
    { id: "vomaset2", name: "沃玛套装", level: 1, quality: 3, image: "沃", type: "set", slot: "inherit", setCount: 2 },
];

export const ItemById = Object.fromEntries(Items.map(e => [e.id, e]));
export const ItemGroupByType = Items.reduce((acc, e) => {
    if (e.type != null) {
        let arr = e.type;
        if (!Array.isArray(arr)) { arr = [arr]; }
        arr.forEach(group => {
            if (!acc[group]) {
                acc[group] = [];
            }
            acc[group].push(e);
        })
    }
    return acc;
}, {})
