export const Stats = [
    { id: "str", name: "力量", type: "int", description: "力量+{0}", sort: 31 },
    { id: "int", name: "魔力", type: "int", description: "魔力+{0}", sort: 32 },
    { id: "spi", name: "道术", type: "int", description: "道术+{0}", sort: 33 },
    { id: "vit", name: "体力", type: "int", description: "体力+{0}", sort: 34 },
    { id: "maxhp", name: "基础生命上限", type: "number", description: "生命上限+{0}", sort: 41 },
    { id: "mhex", name: "生命上限", type: "number", description: "生命上限+{0.2}%", sort: 42 },
    { id: "rtmaxhp", name: "生命上限", type: "number", description: "{0}", sort: 43, depends: ["maxhp", "mhex"], derived: (d) => (d.setStat("rtmaxhp", {value:Math.floor(d.getStat("maxhp").value * (1 + d.getStat("mhex").value / 100))})) },
    { id: "rthp", name: "生命", type: "number", description: "{0}", sort: 44, depends: ["rtmaxhp"], derived: (d) => (d.setStat("rthp", {value:Math.min(d.getStat("rtmaxhp").value, d.getStat("rthp").value)})) },
    { id: "maxmp", name: "基础魔法上限", type: "number", description: "魔法上限+{0}", sort: 51 },
    { id: "mpex", name: "魔法上限", type: "number", description: "魔法上限+{0.2}%", sort: 52 },
    { id: "rtmaxmp", name: "魔法上限", type: "number", description: "{0}", sort: 53, depends: ["maxmp", "mpex"], derived: (d) => (d.setStat("rtmaxmp", {value:Math.floor(d.getStat("maxmp").value * (1 + d.getStat("mpex").value / 100))})) },
    { id: "rtmp", name: "魔法值", type: "number", description: "{0}", sort: 54, depends: ["rtmaxmp"], derived: (d) => (d.setStat("rtmp", {value:Math.min(d.getStat("rtmaxmp").value, d.getStat("rtmp").value)})) },
    { id: "hreg", name: "恢复生命", type: "number", description: "每回合结束时恢复{0}点生命值", sort: 61 },
    { id: "mreg", name: "恢复魔法", type: "number", description: "每回合结束时恢复{0}点魔法值", sort: 62 },
    { id: "ll", name: "近战吸血", type: "number", description: "近战攻击汲取{0.2}%的生命值", sort: 321 },
    { id: "ml", name: "近战吸魔", type: "number", description: "近战攻击汲取{0.2}%的魔法值", sort: 322 },
    { id: "sumreg", name: "召唤物恢复生命", type: "number", description: "你的召唤物每回合结束时恢复{0}点生命值", sort: 63 },
    { id: "killhp", name: "击杀回血", type: "number", description: "杀死敌人后，恢复{0}点生命值", sort: 331 },
    { id: "killmp", name: "击杀回蓝", type: "number", description: "杀死敌人后，恢复{0}点魔法值", sort: 332 },
    { id: "xdmg", name: "物理伤害", type: "range", description: "增加物理伤害{0}-{1}", sort: 1 },
    { id: "fdmg", name: "火焰伤害", type: "range", description: "增加火焰伤害{0}-{1}", sort: 2 },
    { id: "tdmg", name: "风雷伤害", type: "range", description: "增加风雷伤害{0}-{1}", sort: 3 },
    { id: "hdmg", name: "神圣伤害", type: "range", description: "增加神圣伤害{0}-{1}", sort: 4 },
    { id: "pdmg", name: "毒素伤害", type: "range", description: "增加毒素伤害{0}-{1}", sort: 5 },
    { id: "xdmglo", name: "最小物理伤害", type: "number", description: "最小物理伤害+{0}", sort: 11 },
    { id: "fdmglo", name: "最小火焰伤害", type: "number", description: "最小火焰伤害+{0}", sort: 12 },
    { id: "tdmglo", name: "最小风雷伤害", type: "number", description: "最小风雷伤害+{0}", sort: 13 },
    { id: "hdmglo", name: "最小神圣伤害", type: "number", description: "最小神圣伤害+{0}", sort: 14 },
    { id: "pdmglo", name: "最小毒素伤害", type: "number", description: "最小毒素伤害+{0}", sort: 15 },
    { id: "xdmghi", name: "最大物理伤害", type: "number", description: "最大物理伤害+{0}", sort: 21 },
    { id: "fdmghi", name: "最大火焰伤害", type: "number", description: "最大火焰伤害+{0}", sort: 22 },
    { id: "tdmghi", name: "最大风雷伤害", type: "number", description: "最大风雷伤害+{0}", sort: 23 },
    { id: "hdmghi", name: "最大神圣伤害", type: "number", description: "最大神圣伤害+{0}", sort: 24 },
    { id: "pdmghi", name: "最大毒素伤害", type: "number", description: "最大毒素伤害+{0}", sort: 25 },
    { id: "xdr", name: "物理减免", type: "range", description: "增加物理伤害减免{0}-{1}", sort: 101 },
    { id: "fdr", name: "火焰减免", type: "range", description: "增加火焰伤害减免{0}-{1}", sort: 102 },
    { id: "tdr", name: "风雷减免", type: "range", description: "增加风雷伤害减免{0}-{1}", sort: 103 },
    { id: "hdr", name: "神圣减免", type: "range", description: "增加神圣伤害减免{0}-{1}", sort: 104 },
    { id: "pdr", name: "毒素减免", type: "range", description: "增加毒素伤害减免{0}-{1}", sort: 105 },
    { id: "xed", name: "物理增伤", type: "number", description: "物理增伤+{0.2}%", sort: 201 },
    { id: "fed", name: "火焰增伤", type: "number", description: "火焰增伤+{0.2}%", sort: 202 },
    { id: "ted", name: "风雷增伤", type: "number", description: "风雷增伤+{0.2}%", sort: 203 },
    { id: "hed", name: "神圣增伤", type: "number", description: "神圣增伤+{0.2}%", sort: 204 },
    { id: "ped", name: "毒素增伤", type: "number", description: "毒素增伤+{0.2}%", sort: 205 },
    { id: "ued", name: "对不死增伤", type: "number", description: "对不死增伤+{0.2}%", sort: 206 },
    { id: "ded", name: "对妖魔增伤", type: "number", description: "对妖魔增伤+{0.2}%", sort: 207 },
    { id: "ced", name: "对精英增伤", type: "number", description: "对精英增伤+{0.2}%", sort: 208 },
    { id: "doted", name: "持续性效果增伤", type: "number", description: "持续性效果增伤+{0.2}%", sort: 209 },
    { id: "hled", name: "治疗增强", type: "number", description: "治疗效果增强+{0.2}%", sort: 210 },
    { id: "col1ed", name: "对第一列增伤", type: "number", description: "对第一列增伤+{0.2}%", sort: 211 },
    { id: "col23ed", name: "对第二三列增伤", type: "number", description: "对第二三列增伤+{0.2}%", sort: 212 },
    { id: "sumed", name: "召唤物增伤", type: "number", description: "召唤物增伤+{0.2}%", sort: 213 },
    { id: "xres", name: "基础物理抗性", type: "number", description: "物理抗性+{0}%", sort: 221 },
    { id: "fres", name: "基础火焰抗性", type: "number", description: "火焰抗性+{0}%", sort: 222 },
    { id: "tres", name: "基础风雷抗性", type: "number", description: "风雷抗性+{0}%", sort: 223 },
    { id: "hres", name: "基础神圣抗性", type: "number", description: "神圣抗性+{0}%", sort: 224 },
    { id: "pres", name: "基础毒素抗性", type: "number", description: "毒素抗性+{0}%", sort: 225 },
    { id: "ures", name: "对不死减伤", type: "number", cgroup: "undead/demon", description: "对不死减伤+{0}%", sort: 226 },
    { id: "dres", name: "对妖魔减伤", type: "number", cgroup: "undead/demon", description: "对妖魔减伤+{0}%", sort: 227 },
    { id: "cres", name: "对精英减伤", type: "number", cgroup: "elite", description: "对精英减伤+{0}%", sort: 228 },
    { id: "c1res", name: "对第一列敌人减伤", type: "number", cgroup: "formation", description: "对第一列敌人减伤+{0}%", sort: 229 },
    { id: "c23res", name: "对第二三列敌人减伤", type: "number", cgroup: "formation", description: "对第二三列敌人减伤+{0}%", sort: 230 },
    { id: "dotres", name: "对持续性效果减伤", type: "number", cgroup: "dot", description: "对持续性效果减伤+{0}%", sort: 231 },
    { id: "sumres", name: "你的召唤物减伤", type: "number", description: "你的召唤物减伤+{0}%", sort: 232 },
    { id: "mxxres", name: "最大物理抗性", type: "number", description: "最大物理抗性+{0}%", sort: 241 },
    { id: "mxfres", name: "最大火焰抗性", type: "number", description: "最大火焰抗性+{0}%", sort: 242 },
    { id: "mxtres", name: "最大风雷抗性", type: "number", description: "最大风雷抗性+{0}%", sort: 243 },
    { id: "mxhres", name: "最大神圣抗性", type: "number", description: "最大神圣抗性+{0}%", sort: 244 },
    { id: "mxpres", name: "最大毒素抗性", type: "number", description: "最大毒素抗性+{0}%", sort: 245 },
    { id: "rtxres", name: "物理抗性", type: "number", description: "{0}", sort: 251, depends: ["xres", "mxxres"], derived: (d) => (d.setStat("rtxres", {value:Math.min(75 + d.getStat("mxxres").value, d.getStat("xres").value)})) },
    { id: "rtfres", name: "火焰抗性", type: "number", description: "{0}", sort: 252, depends: ["fres", "mxfres"], derived: (d) => (d.setStat("rtfres", {value:Math.min(75 + d.getStat("mxfres").value, d.getStat("fres").value)})) },
    { id: "rttres", name: "风雷抗性", type: "number", description: "{0}", sort: 253, depends: ["tres", "mxtres"], derived: (d) => (d.setStat("rttres", {value:Math.min(75 + d.getStat("mxtres").value, d.getStat("tres").value)})) },
    { id: "rthres", name: "神圣抗性", type: "number", description: "{0}", sort: 254, depends: ["hres", "mxhres"], derived: (d) => (d.setStat("rthres", {value:Math.min(75 + d.getStat("mxhres").value, d.getStat("hres").value)})) },
    { id: "rtpres", name: "毒素抗性", type: "number", description: "{0}", sort: 255, depends: ["pres", "mxpres"], derived: (d) => (d.setStat("rtpres", {value:Math.min(75 + d.getStat("mxpres").value, d.getStat("pres").value)})) },
    { id: "xlr", name: "降低目标物理抗性", type: "number", description: "降低目标物理抗性{0}%", sort: 261 },
    { id: "flr", name: "降低目标火焰抗性", type: "number", description: "降低目标火焰抗性{0}%", sort: 262 },
    { id: "tlr", name: "降低目标风雷抗性", type: "number", description: "降低目标风雷抗性{0}%", sort: 263 },
    { id: "hlr", name: "降低目标神圣抗性", type: "number", description: "降低目标神圣抗性{0}%", sort: 264 },
    { id: "plr", name: "降低目标毒素抗性", type: "number", description: "降低目标毒素抗性{0}%", sort: 265 },
    { id: "xref", name: "反弹物理伤害", type: "number", description: "反弹{0}点物理伤害", sort: 271 },
    { id: "fref", name: "反弹火焰伤害", type: "number", description: "反弹{0}点火焰伤害", sort: 272 },
    { id: "tref", name: "反弹风雷伤害", type: "number", description: "反弹{0}点风雷伤害", sort: 273 },
    { id: "href", name: "反弹神圣伤害", type: "number", description: "反弹{0}点神圣伤害", sort: 274 },
    { id: "pref", name: "反弹毒素伤害", type: "number", description: "反弹{0}点毒素伤害", sort: 275 },
    { id: "curs", name: "诅咒", type: "number", description: "诅咒+{0}", sort: 281 },
    { id: "bles", name: "祝福", type: "number", description: "祝福+{0}", sort: 282 },
    { id: "luck", name: "幸运", type: "number", description: "幸运+{0}", sort: 283 },
    { id: "eg", name: "获得金币", type: "number", description: "金币获取+{0.2}%", sort: 284 },
    { id: "spd", name: "速度", type: "int", description: "速度+{0}", sort: 285 },
    { id: "moral", name: "士气", type: "number", description: "士气+{0}", sort: 286 },
    { id: "d2m", name: "反馈", type: "number", description: "从受损的生命中恢复{0.2}%的魔法值", sort: 287 },
    { id: "exp", name: "经验值", type: "number", sort: 288, save: true },
    { id: "expex", name: "额外经验", type: "number", description: "经验值获取+{0.2}%", sort: 289 },
    { id: "barg", name: "商谈", type: "number", description: "商人物品售价降低{0.2}%", sort: 290 },
    { id: "pmh", name: "敌人治疗效果降低", type: "number", description: "敌人治疗效果降低{0.2}%", sort: 291 },
    { id: "sok", name: "插槽数量", type: "int", sort: 292 },
    { id: "rw", name: "允许符文之语", type: "int", sort: 293 },
    { id: "rwt", name: "允许符文之语-显示", type: "int", description: "可制作五行符", sort: 999 },
    { id: "doge", name: "闪避", type: "number", description: "闪避几率+{0.2}%", sort: 301 },
    { id: "mdoge", name: "法术闪避", type: "number", description: "法术闪避几率+{0.2}%", sort: 302 },
    { id: "hit", name: "准确", type: "number", description: "准确+{0.2}%", sort: 303 },
    { id: "mhit", name: "法术准确", type: "number", description: "法术准确+{0.2}%", sort: 304 },
    { id: "crit", name: "暴击几率", type: "number", description: "暴击几率+{0.2}%", sort: 305 },
    { id: "critd", name: "暴击伤害", type: "number", description: "暴击伤害+{0.2}%", sort: 306 },
    { id: "scrit", name: "法术暴击几率", type: "number", description: "法术暴击几率+{0.2}%", sort: 307 },
    { id: "scritd", name: "法术暴击伤害", type: "number", description: "法术暴击伤害+{0.2}%", sort: 308 },
    { id: "cb", name: "粉碎性打击", type: "number", description: "粉碎性打击几率+{0.2}%", sort: 309 },
    { id: "ucb", name: "圣言", type: "number", description: "圣言几率+{0.2}%", sort: 310 },
    { id: "debuffrd", name: "净化", type: "int", description: "负面效果持续时间-{0}回合", sort: 311 },
    { id: "resil", name: "韧性", type: "number", description: "受到暴击几率降低{0.2}%", sort: 312 },
    { id: "prochit", name: "被击触发", type: "skillList", description: "被攻击时，有{0.2}%概率施展等级{1}的{2}", sort: 313 },
    { id: "procatk", name: "攻击触发", type: "skillList", description: "攻击时，有{0.2}%概率施展等级{1}的{2}", sort: 314 },
    { id: "prockill", name: "击杀触发", type: "skillList", description: "杀死敌人时，有{0.2}%概率施展等级{1}的{2}", sort: 315 },
    { id: "flvl", name: "火焰系技能等级", type: "int", description: "火焰系技能等级+{0}", sort: 401, targetTag: "fire" },
    { id: "tlvl", name: "风雷系技能等级", type: "int", description: "风雷系技能等级+{0}", sort: 402, targetTag: "thunder" },
    { id: "magelvl", name: "魔法师技能等级", type: "int", description: "法师技能等级+{0}", sort: 403, targetUnit: ["mage"] },
    { id: "flvlmage", name: "火焰系技能等级", type: "int", description: "火焰系技能等级+{0}（限法师）", sort: 404, targetTag: "fire", unitConstraint: ["mage"] },
    { id: "tlvlmage", name: "风雷系技能等级", type: "int", description: "风雷系技能等级+{0}（限法师）", sort: 405, targetTag: "thunder", unitConstraint: ["mage"] },
    { id: "magelvlmage", name: "魔法师技能等级", type: "int", description: "法师技能等级+{0}（限法师）", sort: 406, targetUnit: ["mage"], unitConstraint: ["mage"] },
    { id: "blvl", name: "战术系技能等级", type: "int", description: "战术系技能等级+{0}", sort: 407, targetTag: "battle" },
    { id: "xlvl", name: "体术系技能等级", type: "int", description: "体术系技能等级+{0}", sort: 408, targetTag: "xskill" },
    { id: "warrlvl", name: "武士技能等级", type: "int", description: "战士技能等级+{0}", sort: 409, targetUnit: ["warr"] },
    { id: "blvlwarr", name: "战术系技能等级", type: "int", description: "战术系技能等级+{0}（限战士）", sort: 410, targetTag: "battle", unitConstraint: ["warr"] },
    { id: "xlvlwarr", name: "体术系技能等级", type: "int", description: "体术系技能等级+{0}（限战士）", sort: 411, targetTag: "xskill", unitConstraint: ["warr"] },
    { id: "warrlvlwarr", name: "武士技能等级", type: "int", description: "战士技能等级+{0}（限战士）", sort: 412, targetUnit: ["warr"], unitConstraint: ["warr"] },
    { id: "hlvl", name: "神圣系技能等级", type: "int", description: "神圣系技能等级+{0}", sort: 413, targetTag: "holy" },
    { id: "plvl", name: "道法系技能等级", type: "int", description: "道法系技能等级+{0}", sort: 414, targetTag: "psyco" },
    { id: "wlklvl", name: "道士技能等级", type: "int", description: "道士技能等级+{0}", sort: 415, targetUnit: ["wlk"] },
    { id: "hlvlwlok", name: "神圣系技能等级", type: "int", description: "神圣系技能等级+{0}（限道士）", sort: 416, targetTag: "holy", unitConstraint: ["wlk"] },
    { id: "plvlwlok", name: "道法系技能等级", type: "int", description: "道法系技能等级+{0}（限道士）", sort: 417, targetTag: "psyco", unitConstraint: ["wlk"] },
    { id: "wlklvlwlk", name: "道士技能等级", type: "int", description: "道士技能等级+{0}（限道士）", sort: 418, targetUnit: ["wlk"], unitConstraint: ["wlk"] },
    { id: "alvl", name: "所有技能等级", type: "int", description: "所有技能等级+{0}", sort: 419, targetUnit: ["mage", "warr", "wlk"] },
    { id: "slvl", name: "召唤系技能等级", type: "int", description: "召唤系技能等级+{0}", sort: 420, targetTag: "summon" },
    { id: "glvl", name: "防护系技能等级", type: "int", description: "防护系技能等级+{0}", sort: 421, targetTag: "guardian" },
    { id: "cate", name: "分类", type: "set", sort: 800 },
    { id: "skfbltmage", name: "火球术(限法师)", type: "int", description: "火球术+{0}（限法师）", sort: 431, targetSkill: "fblt", unitConstraint: ["mage"] },
    { id: "skfrngmage", name: "抗拒火环(限法师)", type: "int", description: "抗拒火环+{0}（限法师）", sort: 432, targetSkill: "frng", unitConstraint: ["mage"] },
    { id: "skfinfmage", name: "地狱火(限法师)", type: "int", description: "地狱火+{0}（限法师）", sort: 433, targetSkill: "finf", unitConstraint: ["mage"] },
    { id: "skfbalmage", name: "大火球(限法师)", type: "int", description: "大火球+{0}（限法师）", sort: 434, targetSkill: "fbal", unitConstraint: ["mage"] },
    { id: "skfblsmage", name: "爆裂火焰(限法师)", type: "int", description: "爆裂火焰+{0}（限法师）", sort: 435, targetSkill: "fbls", unitConstraint: ["mage"] },
    { id: "skfwalmage", name: "火墙术(限法师)", type: "int", description: "火墙术+{0}（限法师）", sort: 436, targetSkill: "fwal", unitConstraint: ["mage"] },
    { id: "skfblt", name: "火球术", type: "int", description: "火球术+{0}", sort: 437, targetSkill: "fblt" },
    { id: "skfrng", name: "抗拒火环", type: "int", description: "抗拒火环+{0}", sort: 438, targetSkill: "frng" },
    { id: "skfinf", name: "地狱火", type: "int", description: "地狱火+{0}", sort: 439, targetSkill: "finf" },
    { id: "skfbal", name: "大火球", type: "int", description: "大火球+{0}", sort: 440, targetSkill: "fbal" },
    { id: "skfbls", name: "爆裂火焰", type: "int", description: "爆裂火焰+{0}", sort: 441, targetSkill: "fbls" },
    { id: "skfwal", name: "火墙术", type: "int", description: "火墙术+{0}", sort: 442, targetSkill: "fwal" },
    { id: "sktchmmage", name: "诱惑之光(限法师)", type: "int", description: "诱惑之光+{0}（限法师）", sort: 443, targetSkill: "tchm", unitConstraint: ["mage"] },
    { id: "sktbltmage", name: "雷电术(限法师)", type: "int", description: "雷电术+{0}（限法师）", sort: 444, targetSkill: "tblt", unitConstraint: ["mage"] },
    { id: "sktltnmage", name: "疾光电影(限法师)", type: "int", description: "疾光电影+{0}（限法师）", sort: 445, targetSkill: "tltn", unitConstraint: ["mage"] },
    { id: "sktnovmage", name: "地狱雷光(限法师)", type: "int", description: "地狱雷光+{0}（限法师）", sort: 446, targetSkill: "tnov", unitConstraint: ["mage"] },
    { id: "sktshdmage", name: "魔法盾(限法师)", type: "int", description: "魔法盾+{0}（限法师）", sort: 447, targetSkill: "tshd", unitConstraint: ["mage"] },
    { id: "sktblzmage", name: "冰咆哮(限法师)", type: "int", description: "冰咆哮+{0}（限法师）", sort: 448, targetSkill: "tblz", unitConstraint: ["mage"] },
    { id: "sktchm", name: "诱惑之光", type: "int", description: "诱惑之光+{0}", sort: 449, targetSkill: "tchm" },
    { id: "sktblt", name: "雷电术", type: "int", description: "雷电术+{0}", sort: 450, targetSkill: "tblt" },
    { id: "sktltn", name: "疾光电影", type: "int", description: "疾光电影+{0}", sort: 451, targetSkill: "tltn" },
    { id: "sktnov", name: "地狱雷光", type: "int", description: "地狱雷光+{0}", sort: 452, targetSkill: "tnov" },
    { id: "sktshd", name: "魔法盾", type: "int", description: "魔法盾+{0}", sort: 453, targetSkill: "tshd" },
    { id: "sktblz", name: "冰咆哮", type: "int", description: "冰咆哮+{0}", sort: 454, targetSkill: "tblz" },
    { id: "skbbaswarr", name: "基础剑术(限战士)", type: "int", description: "基础剑术+{0}（限战士）", sort: 455, targetSkill: "bbas", unitConstraint: ["warr"] },
    { id: "skbcrtwarr", name: "攻杀剑术(限战士)", type: "int", description: "攻杀剑术+{0}（限战士）", sort: 456, targetSkill: "bcrt", unitConstraint: ["warr"] },
    { id: "skbthrwarr", name: "刺杀剑术(限战士)", type: "int", description: "刺杀剑术+{0}（限战士）", sort: 457, targetSkill: "bthr", unitConstraint: ["warr"] },
    { id: "skbclvwarr", name: "半月弯刀(限战士)", type: "int", description: "半月弯刀+{0}（限战士）", sort: 458, targetSkill: "bclv", unitConstraint: ["warr"] },
    { id: "skbcrzwarr", name: "十字斩(限战士)", type: "int", description: "十字斩+{0}（限战士）", sort: 459, targetSkill: "bcrz", unitConstraint: ["warr"] },
    { id: "skbfblwarr", name: "烈火剑法(限战士)", type: "int", description: "烈火剑法+{0}（限战士）", sort: 460, targetSkill: "bfbl", unitConstraint: ["warr"] },
    { id: "skbbas", name: "基础剑术", type: "int", description: "基础剑术+{0}", sort: 461, targetSkill: "bbas" },
    { id: "skbcrt", name: "攻杀剑术", type: "int", description: "攻杀剑术+{0}", sort: 462, targetSkill: "bcrt" },
    { id: "skbthr", name: "刺杀剑术", type: "int", description: "刺杀剑术+{0}", sort: 463, targetSkill: "bthr" },
    { id: "skbclv", name: "半月弯刀", type: "int", description: "半月弯刀+{0}", sort: 464, targetSkill: "bclv" },
    { id: "skbcrz", name: "十字斩", type: "int", description: "十字斩+{0}", sort: 465, targetSkill: "bcrz" },
    { id: "skbfbl", name: "烈火剑法", type: "int", description: "烈火剑法+{0}", sort: 466, targetSkill: "bfbl" },
    { id: "skxdefwarr", name: "铁布衫(限战士)", type: "int", description: "铁布衫+{0}（限战士）", sort: 467, targetSkill: "xdef", unitConstraint: ["warr"] },
    { id: "skxdogwarr", name: "猎犬步伐(限战士)", type: "int", description: "猎犬步伐+{0}（限战士）", sort: 468, targetSkill: "xdog", unitConstraint: ["warr"] },
    { id: "skxctawarr", name: "战斗指挥(限战士)", type: "int", description: "战斗指挥+{0}（限战士）", sort: 469, targetSkill: "xcta", unitConstraint: ["warr"] },
    { id: "skxwmswarr", name: "龙皮术(限战士)", type: "int", description: "龙皮术+{0}（限战士）", sort: 470, targetSkill: "xwms", unitConstraint: ["warr"] },
    { id: "skxchgwarr", name: "野蛮冲撞(限战士)", type: "int", description: "野蛮冲撞+{0}（限战士）", sort: 471, targetSkill: "xchg", unitConstraint: ["warr"] },
    { id: "skxtstwarr", name: "霜冻踏地(限战士)", type: "int", description: "霜冻踏地+{0}（限战士）", sort: 472, targetSkill: "xtst", unitConstraint: ["warr"] },
    { id: "skxdef", name: "铁布衫", type: "int", description: "铁布衫+{0}", sort: 473, targetSkill: "xdef" },
    { id: "skxdog", name: "猎犬步伐", type: "int", description: "猎犬步伐+{0}", sort: 474, targetSkill: "xdog" },
    { id: "skxcta", name: "战斗指挥", type: "int", description: "战斗指挥+{0}", sort: 475, targetSkill: "xcta" },
    { id: "skxwms", name: "龙皮术", type: "int", description: "龙皮术+{0}", sort: 476, targetSkill: "xwms" },
    { id: "skxchg", name: "野蛮冲撞", type: "int", description: "野蛮冲撞+{0}", sort: 477, targetSkill: "xchg" },
    { id: "skxtst", name: "霜冻踏地", type: "int", description: "霜冻踏地+{0}", sort: 478, targetSkill: "xtst" },
    { id: "skhhelwlok", name: "治愈术(限道士)", type: "int", description: "治愈术+{0}（限道士）", sort: 479, targetSkill: "hhel", unitConstraint: ["wlk"] },
    { id: "skhgsdwlok", name: "幽灵盾(限道士)", type: "int", description: "幽灵盾+{0}（限道士）", sort: 480, targetSkill: "hgsd", unitConstraint: ["wlk"] },
    { id: "skhinvwlok", name: "隐身术(限道士)", type: "int", description: "隐身术+{0}（限道士）", sort: 481, targetSkill: "hinv", unitConstraint: ["wlk"] },
    { id: "skhhsdwlok", name: "神圣战甲术(限道士)", type: "int", description: "神圣战甲术+{0}（限道士）", sort: 482, targetSkill: "hhsd", unitConstraint: ["wlk"] },
    { id: "skhlokwlok", name: "困魔咒(限道士)", type: "int", description: "困魔咒+{0}（限道士）", sort: 483, targetSkill: "hlok", unitConstraint: ["wlk"] },
    { id: "skhmhlwlok", name: "群体治愈术(限道士)", type: "int", description: "群体治愈术+{0}（限道士）", sort: 484, targetSkill: "hmhl", unitConstraint: ["wlk"] },
    { id: "skhhel", name: "治愈术", type: "int", description: "治愈术+{0}", sort: 485, targetSkill: "hhel" },
    { id: "skhgsd", name: "幽灵盾", type: "int", description: "幽灵盾+{0}", sort: 486, targetSkill: "hgsd" },
    { id: "skhinv", name: "隐身术", type: "int", description: "隐身术+{0}", sort: 487, targetSkill: "hinv" },
    { id: "skhhsd", name: "神圣战甲术", type: "int", description: "神圣战甲术+{0}", sort: 488, targetSkill: "hhsd" },
    { id: "skhlok", name: "困魔咒", type: "int", description: "困魔咒+{0}", sort: 489, targetSkill: "hlok" },
    { id: "skhmhl", name: "群体治愈术", type: "int", description: "群体治愈术+{0}", sort: 490, targetSkill: "hmhl" },
    { id: "skpbaswlok", name: "精神力战法(限道士)", type: "int", description: "精神力战法+{0}（限道士）", sort: 491, targetSkill: "pbas", unitConstraint: ["wlk"] },
    { id: "skppoiwlok", name: "施毒术(限道士)", type: "int", description: "施毒术+{0}（限道士）", sort: 492, targetSkill: "ppoi", unitConstraint: ["wlk"] },
    { id: "skpsklwlok", name: "召唤骷髅(限道士)", type: "int", description: "召唤骷髅+{0}（限道士）", sort: 493, targetSkill: "pskl", unitConstraint: ["wlk"] },
    { id: "skprunwlok", name: "灵魂火符(限道士)", type: "int", description: "灵魂火符+{0}（限道士）", sort: 494, targetSkill: "prun", unitConstraint: ["wlk"] },
    { id: "skpcblwlok", name: "降魔剑术(限道士)", type: "int", description: "降魔剑术+{0}（限道士）", sort: 495, targetSkill: "pcbl", unitConstraint: ["wlk"] },
    { id: "skpsdmwlok", name: "召唤神兽(限道士)", type: "int", description: "召唤神兽+{0}（限道士）", sort: 496, targetSkill: "psdm", unitConstraint: ["wlk"] },
    { id: "skpbas", name: "精神力战法", type: "int", description: "精神力战法+{0}", sort: 497, targetSkill: "pbas" },
    { id: "skppoi", name: "施毒术", type: "int", description: "施毒术+{0}", sort: 498, targetSkill: "ppoi" },
    { id: "skpskl", name: "召唤骷髅", type: "int", description: "召唤骷髅+{0}", sort: 499, targetSkill: "pskl" },
    { id: "skprun", name: "灵魂火符", type: "int", description: "灵魂火符+{0}", sort: 500, targetSkill: "prun" },
    { id: "skpcbl", name: "降魔剑术", type: "int", description: "降魔剑术+{0}", sort: 501, targetSkill: "pcbl" },
    { id: "skpsdm", name: "召唤神兽", type: "int", description: "召唤神兽+{0}", sort: 502, targetSkill: "psdm" },
    { id: "silent", name: "无法攻击", type: "int", sort: 801 },
    { id: "stun", name: "昏迷", type: "int", sort: 802 },
    { id: "skpts", name: "技能点数", type: "int", sort: 803, save: true },
    { id: "setheavy", name: "重型套装", type: "number", sort: 821 },
    { id: "setwargod", name: "战神套装", type: "number", sort: 822 },
    { id: "setmara", name: "天魔套装", type: "number", sort: 823 },
    { id: "setjihad", name: "圣战套装", type: "number", sort: 824 },
    { id: "setsoul", name: "灵魂套装", type: "number", sort: 825 },
    { id: "setghost", name: "幽灵套装", type: "number", sort: 826 },
    { id: "setvenerable", name: "天尊套装", type: "number", sort: 827 },
    { id: "setmaster", name: "天师套装", type: "number", sort: 828 },
    { id: "setmagic", name: "魔法套装", type: "number", sort: 829 },
    { id: "setdemon", name: "恶魔套装", type: "number", sort: 830 },
    { id: "setmagegod", name: "法神套装", type: "number", sort: 831 },
    { id: "setcolorful", name: "霓裳套装", type: "number", sort: 832 },
    { id: "setblackiron", name: "黑铁套装", type: "number", sort: 833 },
    { id: "setmysterious", name: "神秘套装", type: "number", sort: 834 },
    { id: "setmemory", name: "记忆套装", type: "number", sort: 835 },
    { id: "setvoma", name: "沃玛套装", type: "number", sort: 836 },
    { id: "setzuma", name: "祖玛套装", type: "number", sort: 837 },
    { id: "setredmoon", name: "赤月套装", type: "number", sort: 838 },
    { id: "setprisma", name: "虹魔套装", type: "number", sort: 839 },
    { id: "setdragon", name: "龙之套装", type: "number", sort: 840 },
    { id: "setempire", name: "帝国套装", type: "number", sort: 841 },
    { id: "setany", name: "任意套装效果", type: "number", description: "套装件数需求-1", sort: 999 },
    { id: "skfbltm1", name: "1海魂", type: "number", description: "火球术可以点燃目标并造成{0.2}%的额外伤害", sort: 999, targetSkill: "fblt", isSkillMod: true },
    { id: "skfrngm1", name: "7巫异时刻", type: "number", description: "施放抗拒火环后，不消耗本回合。", sort: 999, targetSkill: "frng", isSkillMod: true },
    { id: "skfinfm1", name: "14龙牙", type: "number", description: "地狱火的引燃数量+{0}", sort: 999, targetSkill: "finf", isSkillMod: true },
    { id: "skfbalm1", name: "21火骷髅剑", type: "number", description: "大火球的波及数量+{0}", sort: 999, targetSkill: "fbal", isSkillMod: true },
    { id: "skfblsm1", name: "28魔杖", type: "number", description: "爆裂火焰使目标身上的点燃效果立即造成全额伤害", sort: 999, targetSkill: "fbls", isSkillMod: true },
    { id: "skfblsm2", name: "28纵火者", type: "number", description: "每个未命中的目标使你有{0.2}%的几率立即再次施放爆裂火焰", sort: 999, targetSkill: "fbls", isSkillMod: true },
    { id: "skfwalm1", name: "35火龙杖", type: "number", description: "火墙术的范围提升为3x3", sort: 999, targetSkill: "fwal", isSkillMod: true },
    { id: "skfwalm2", name: "35火神仲裁官", type: "number", description: "火墙范围内的目标造成的物理伤害降低{0.2}%", sort: 999, targetSkill: "fwal", isSkillMod: true },
    { id: "sktchmm1", name: "1偃月", type: "number", description: "诱惑之光可以对精英敌人使用", sort: 999, targetSkill: "tchm", isSkillMod: true },
    { id: "sktbltm1", name: "7充能短刃", type: "number", description: "雷电术对目标及其相邻的1个敌人造成{0.2}%的粉碎性打击", sort: 999, targetSkill: "tblt", isSkillMod: true },
    { id: "sktltnm1", name: "14电能印记", type: "number", description: "疾光电影的命中提升20%，但是伤害降低{0.2}%，同时，疾光电影不再对一条直线的敌人造成伤害，而是转化为闪电链，最多伤害4个目标", sort: 999, targetSkill: "tltn", isSkillMod: true },
    { id: "sktltnm2", name: "14 雷神战刃", type: "number", description: "疾光电影可以攻击2排目标", sort: 999, targetSkill: "tltn", isSkillMod: true },
    { id: "sktnovm1", name: "21渡劫刻印", type: "number", description: "受地狱雷光影响的目标降低{0.2}%风雷抗性，最多叠加3层", sort: 999, targetSkill: "tnov", isSkillMod: true },
    { id: "sktshdm1", name: "28启示录", type: "number", description: "魔法盾可以吸收你的生命上限{0.2}%的物理伤害", sort: 999, targetSkill: "tshd", isSkillMod: true },
    { id: "sktshdm2", name: "28血饮", type: "number", description: "魔法盾持续期间，你的反弹伤害效果提升{0.2}%", sort: 999, targetSkill: "tshd", isSkillMod: true },
    { id: "sktblzm1", name: "35 彩虹魔杖", type: "number", description: "冰咆哮可直接杀死生命值低于{0.2}%的小怪", sort: 999, targetSkill: "tblz", isSkillMod: true },
    { id: "sktblzm2", name: "35骨玉权杖", type: "number", description: "每命中一个目标，冰咆哮的伤害提升{0.2}%", sort: 999, targetSkill: "tblz", isSkillMod: true },
    { id: "skbbasm1", name: "1浮屠", type: "number", description: "使用斧类武器时，提升{0.2}%的暴击几率", sort: 999, targetSkill: "bbas", isSkillMod: true },
    { id: "skbcrtm1", name: "skbcrtm1", type: "number", description: "你的非物理伤害也能造成暴击", sort: 999, targetSkill: "bcrt", isSkillMod: true },
    { id: "skbthrm1", name: "skbthrm1", type: "number", description: "受影响的目标将受到额外{0.2}%的刺杀剑术伤害", sort: 999, targetSkill: "bthr", isSkillMod: true },
    { id: "skbclvm1", name: "skbclvm1", type: "number", description: "受影响的目标遭受流血效果，每回合受到{0.2}%的物理伤害", sort: 999, targetSkill: "bclv", isSkillMod: true },
    { id: "skbcrzm1", name: "skbcrzm1", type: "number", description: "施放十字斩后，你的刺杀剑术或者半月弯刀的冷却时间-1回合", sort: 999, targetSkill: "bcrz", isSkillMod: true },
    { id: "skbcrzm2", name: "skbcrzm2", type: "number", description: "你的十字斩攻击范围+1", sort: 999, targetSkill: "bcrz", isSkillMod: true },
    { id: "skbfblm1", name: "t4 weap", type: "number", description: "烈火剑法附带等额的神圣伤害，烈火剑法现在也是神圣系技能", sort: 999, targetSkill: "bfbl", skillTag: ["holy"], isSkillMod: true },
    { id: "skbfblm2", name: "skbfblm2", type: "number", description: "汲取火焰伤害的{0.2}%的生命值，烈火剑法现在也是道术系技能", sort: 999, targetSkill: "bfbl", skillTag: ["psyco"], isSkillMod: true },
    { id: "skxdefm1", name: "skxdefm1", type: "number", description: "被击中后恢复物理减伤{0.2}%的生命值", sort: 999, targetSkill: "xdef", isSkillMod: true },
    { id: "skxdogm1", name: "skxdogm1", type: "number", description: "提升等额的魔法闪避", sort: 999, targetSkill: "xdog", isSkillMod: true },
    { id: "skxctam1", name: "skxctam1", type: "number", description: "开启后，提升{0.2}%的最大生命值", sort: 999, targetSkill: "xcta", isSkillMod: true },
    { id: "skxwmsm1", name: "skxwmsm1", type: "number", description: "提升等额的火焰反弹", sort: 999, targetSkill: "xwms", isSkillMod: true },
    { id: "skxchgm1", name: "skxchgm1", type: "number", description: "施展野蛮冲撞后，你立即普通攻击一次", sort: 999, targetSkill: "xchg", isSkillMod: true },
    { id: "skxtstm1", name: "skxtstm1", type: "number", description: "受影响的目标的物理抗性降低{0.2}%", sort: 999, targetSkill: "xtst", isSkillMod: true },
    { id: "skxtstm2", name: "skxtstm2", type: "number", description: "再次被霜冻踏地击中时，会昏迷1回合", sort: 999, targetSkill: "xtst", isSkillMod: true },
    { id: "skhhelm1", name: "skhhelm1", type: "number", description: "治愈术会附加持续治疗效果，数值为治疗量的{0.2}%", sort: 999, targetSkill: "hhel", isSkillMod: true },
    { id: "skhhelm2", name: "skhhelm2", type: "number", description: "治愈术现在会治疗你的整个队伍", sort: 999, targetSkill: "hhel", isSkillMod: true },
    { id: "skhgsdm1", name: "skhgsdm1", type: "number", description: "可以吸收你的生命上限{0.2}%的非物理伤害", sort: 999, targetSkill: "hgsd", isSkillMod: true },
    { id: "skhinvm1", name: "skhinvm1", type: "number", description: "隐身状态的攻击造成{0.2}%的额外伤害", sort: 999, targetSkill: "hinv", isSkillMod: true },
    { id: "skhhsdm1", name: "skhhsdm1", type: "number", description: "神圣战甲同时提供等额的非物理减伤", sort: 999, targetSkill: "hhsd", isSkillMod: true },
    { id: "skhlokm1", name: "skhlokm1", type: "number", description: "受影响的目标将被定义为妖魔", sort: 999, targetSkill: "hlok", isSkillMod: true },
    { id: "skhlokm2", name: "skhlokm2", type: "number", description: "可对精英敌人和首领敌人施展，持续时间减半", sort: 999, targetSkill: "hlok", isSkillMod: true },
    { id: "skhmhlm1", name: "skhmhlm1", type: "number", description: "被神圣责罚杀死的敌人会为你恢复伤害的{0.2}%的生命值", sort: 999, targetSkill: "hmhl", isSkillMod: true },
    { id: "skhmhlm2", name: "skhmhlm2", type: "number", description: "每个受神圣责罚影响的目标为你提供{0.2}%的减伤", sort: 999, targetSkill: "hmhl", isSkillMod: true },
    { id: "skpbasm1", name: "skpbasm1", type: "number", description: "提升等额的暴击几率", sort: 999, targetSkill: "pbas", isSkillMod: true },
    { id: "skppoim1", name: "skppoim1", type: "number", description: "伤害类毒药的持续时间减半，伤害+100%", sort: 999, targetSkill: "ppoi", isSkillMod: true },
    { id: "skpsklm1", name: "skpsklm1", type: "number", description: "骷髅的生命值-90%，骷髅死亡时爆炸，造成火焰伤害，召唤骷髅现在也是火焰系技能", sort: 999, targetSkill: "pskl", skillTag: ["fire"], isSkillMod: true },
    { id: "skprunm1", name: "skprunm1", type: "number", description: "对不死生物的伤害提升{0.2}%", sort: 999, targetSkill: "prun", isSkillMod: true },
    { id: "skpcblm1", name: "skpcblm1", type: "number", description: "击杀妖魔以后，造成的所有伤害提升{0.2}%", sort: 999, targetSkill: "pcbl", isSkillMod: true },
    { id: "skpcblm2", name: "skpcblm2", type: "number", description: "对被灵魂火符命中的不死生物的伤害提升{0.2}%", sort: 999, targetSkill: "pcbl", isSkillMod: true },
    { id: "skpsdmm1", name: "skpsdmm1", type: "number", description: "神兽现在攻击扇形范围内的敌人，伤害类型变为毒素系，召唤神兽现在也是毒素系技能", sort: 999, targetSkill: "psdm", skillTag: ["poison"], isSkillMod: true },
    { id: "skpsdmm2", name: "skpsdmm2", type: "number", description: "神兽攻击时有概率战吼，整个队伍的物理伤害提升{0.2}%", sort: 999, targetSkill: "psdm", isSkillMod: true },
];

export const StatById = Object.fromEntries(Stats.map(e => [e.id, e]));
