export const Stats = [
    { id: "rthp", name: "生命", type: "number", depends: ["rtmaxhp"], derived: (d) => (d.setStat("rthp", Math.min(d.getStat("rtmaxhp"), d.getStat("rthp")))) },
    { id: "rtmaxhp", name: "生命上限", type: "number", depends: ["maxhp", "mhex"], derived: (d) => (d.setStat("rtmaxhp", Math.floor(d.getStat("maxhp") * (1 + d.getStat("mhex") / 100)))) },
    { id: "maxhp", name: "基础生命上限", type: "number" },
    { id: "mhex", name: "生命上限", type: "number" },
    { id: "rtmp", name: "魔法值", type: "number", depends: ["rtmaxmp"], derived: (d) => (d.setStat("rtmp", Math.min(d.getStat("rtmaxmp"), d.getStat("rtmp")))) },
    { id: "rtmaxmp", name: "魔法上限", type: "number", depends: ["maxmp", "mpex"], derived: (d) => (d.setStat("rtmaxmp", Math.floor(d.getStat("maxmp") * (1 + d.getStat("mpex") / 100)))) },
    { id: "maxmp", name: "基础魔法上限", type: "number" },
    { id: "mpex", name: "魔法上限", type: "number" },
    { id: "hreg", name: "恢复生命", type: "number" },
    { id: "mreg", name: "恢复魔法", type: "number" },
    { id: "exp", name: "经验值", type: "number" },
    { id: "xdr", name: "物理减免", type: "range" },
    { id: "fdr", name: "火焰减免", type: "range" },
    { id: "tdr", name: "风雷减免", type: "range" },
    { id: "hdr", name: "神圣减免", type: "range" },
    { id: "pdr", name: "毒素减免", type: "range" },
    { id: "xres", name: "基础物理抗性", type: "number" },
    { id: "fres", name: "基础火焰抗性", type: "number" },
    { id: "tres", name: "基础风雷抗性", type: "number" },
    { id: "hres", name: "基础神圣抗性", type: "number" },
    { id: "pres", name: "基础毒素抗性", type: "number" },
    { id: "mxxres", name: "最大物理抗性", type: "number" },
    { id: "mxfres", name: "最大火焰抗性", type: "number" },
    { id: "mxtres", name: "最大风雷抗性", type: "number" },
    { id: "mxhres", name: "最大神圣抗性", type: "number" },
    { id: "mxpres", name: "最大毒素抗性", type: "number" },
    { id: "rtxres", name: "物理抗性", type: "number", depends: ["xres", "mxxres"], derived: (d) => (d.setStat("rtxres", Math.min(75 + d.getStat("mxxres"), d.getStat("xres")))) },
    { id: "rtfres", name: "火焰抗性", type: "number", depends: ["fres", "mxfres"], derived: (d) => (d.setStat("rtfres", Math.min(75 + d.getStat("mxfres"), d.getStat("fres")))) },
    { id: "rttres", name: "风雷抗性", type: "number", depends: ["tres", "mxtres"], derived: (d) => (d.setStat("rttres", Math.min(75 + d.getStat("mxtres"), d.getStat("tres")))) },
    { id: "rthres", name: "神圣抗性", type: "number", depends: ["hres", "mxhres"], derived: (d) => (d.setStat("rthres", Math.min(75 + d.getStat("mxhres"), d.getStat("hres")))) },
    { id: "rtpres", name: "毒素抗性", type: "number", depends: ["pres", "mxpres"], derived: (d) => (d.setStat("rtpres", Math.min(75 + d.getStat("mxpres"), d.getStat("pres")))) },
    { id: "ures", name: "对不死减伤", type: "number", cgroup: "undead/demon" },
    { id: "dres", name: "对妖魔减伤", type: "number", cgroup: "undead/demon" },
    { id: "mres", name: "对近战减伤", type: "number", cgroup: "melee/ranged" },
    { id: "rres", name: "对远程减伤", type: "number", cgroup: "melee/ranged" },
    { id: "cres", name: "对精英减伤", type: "number", cgroup: "elite" },
    { id: "curs", name: "诅咒", type: "number" },
    { id: "bles", name: "祝福", type: "number" },
    { id: "luck", name: "幸运", type: "number" },
    { id: "eg", name: "获得金币", type: "number" },
    { id: "spd", name: "速度", type: "number" },
    { id: "doge", name: "闪避", type: "number" },
    { id: "mdoge", name: "法术闪避", type: "number" },
    { id: "xatk", name: "力量", type: "range" },
    { id: "hit", name: "准确", type: "number" },
    { id: "matk", name: "魔力", type: "range" },
    { id: "watk", name: "道术", type: "range" },
    { id: "xed", name: "物理增伤", type: "number" },
    { id: "fed", name: "火焰增伤", type: "number" },
    { id: "ted", name: "风雷增伤", type: "number" },
    { id: "hed", name: "神圣增伤", type: "number" },
    { id: "ped", name: "毒素增伤", type: "number" },
    { id: "ued", name: "对不死增伤", type: "number" },
    { id: "ded", name: "对妖魔增伤", type: "number" },
    { id: "med", name: "对近战增伤", type: "number" },
    { id: "red", name: "对远程增伤", type: "number" },
    { id: "ced", name: "对精英增伤", type: "number" },
    { id: "doted", name: "持续性效果增伤", type: "number" },
    { id: "hled", name: "治疗增强", type: "number" },
    { id: "flvl", name: "火焰系技能等级", type: "number" },
    { id: "tlvl", name: "风雷系技能等级", type: "number" },
    { id: "magelvl", name: "魔法师技能等级", type: "number" },
    { id: "blvl", name: "战术系技能等级", type: "number" },
    { id: "xlvl", name: "体术系技能等级", type: "number" },
    { id: "warrlvl", name: "武士技能等级", type: "number" },
    { id: "hlvl", name: "神圣系技能等级", type: "number" },
    { id: "plvl", name: "道法系技能等级", type: "number" },
    { id: "wlklvl", name: "道士技能等级", type: "number" },
    { id: "alvl", name: "所有技能等级", type: "number" },
    { id: "slvl", name: "召唤系技能等级", type: "number" },
    { id: "glvl", name: "防护系技能等级", type: "number" },
    { id: "cate", name: "分类", type: "set" },
    { id: "cb", name: "粉碎性打击", type: "number" },
    { id: "ow", name: "撕裂伤口", type: "number" },
    { id: "ref", name: "反弹伤害", type: "number" },
    { id: "ll", name: "近战吸血", type: "number" },
    { id: "ml", name: "近战吸魔", type: "number" },
    { id: "lr", name: "降低物理抗性", type: "number" },
    { id: "flr", name: "降低火焰抗性", type: "number" },
    { id: "tlr", name: "降低风雷抗性", type: "number" },
    { id: "hlr", name: "降低神圣抗性", type: "number" },
    { id: "plr", name: "降低毒素抗性", type: "number" },
    { id: "skfbltmage", name: "火球术", type: "number" },
    { id: "skfrngmage", name: "抗拒火环", type: "number" },
    { id: "skfinfmage", name: "地狱火", type: "number" },
    { id: "skfbalmage", name: "大火球", type: "number" },
    { id: "skfblsmage", name: "爆裂火焰", type: "number" },
    { id: "skfwalmage", name: "火墙术", type: "number" },
    { id: "skfblt", name: "火球术", type: "number" },
    { id: "skfrng", name: "抗拒火环", type: "number" },
    { id: "skfinf", name: "地狱火", type: "number" },
    { id: "skfbal", name: "大火球", type: "number" },
    { id: "skfbls", name: "爆裂火焰", type: "number" },
    { id: "skfwal", name: "火墙术", type: "number" },
    { id: "sktchmmage", name: "诱惑之光", type: "number" },
    { id: "sktbltmage", name: "雷电术", type: "number" },
    { id: "sktltnmage", name: "疾光电影", type: "number" },
    { id: "sktnovmage", name: "地狱雷光", type: "number" },
    { id: "sktshdmage", name: "魔法盾", type: "number" },
    { id: "sktblzmage", name: "冰咆哮", type: "number" },
    { id: "sktchm", name: "诱惑之光", type: "number" },
    { id: "sktblt", name: "雷电术", type: "number" },
    { id: "sktltn", name: "疾光电影", type: "number" },
    { id: "sktnov", name: "地狱雷光", type: "number" },
    { id: "sktshd", name: "魔法盾", type: "number" },
    { id: "sktblz", name: "冰咆哮", type: "number" },
    { id: "skbbaswarr", name: "基础剑术", type: "number" },
    { id: "skbcrtwarr", name: "攻杀剑术", type: "number" },
    { id: "skbthrwarr", name: "刺杀剑术", type: "number" },
    { id: "skbclvwarr", name: "半月弯刀", type: "number" },
    { id: "skbcrzwarr", name: "十字斩", type: "number" },
    { id: "skbfblwarr", name: "烈火剑法", type: "number" },
    { id: "skbbas", name: "基础剑术", type: "number" },
    { id: "skbcrt", name: "攻杀剑术", type: "number" },
    { id: "skbthr", name: "刺杀剑术", type: "number" },
    { id: "skbclv", name: "半月弯刀", type: "number" },
    { id: "skbcrz", name: "十字斩", type: "number" },
    { id: "skbfbl", name: "烈火剑法", type: "number" },
    { id: "skxdefwarr", name: "铁布衫", type: "number" },
    { id: "skxdogwarr", name: "猎犬步伐", type: "number" },
    { id: "skxctawarr", name: "战斗指挥", type: "number" },
    { id: "skxwmswarr", name: "龙皮术", type: "number" },
    { id: "skxchgwarr", name: "野蛮冲撞", type: "number" },
    { id: "skxtstwarr", name: "霜冻踏地", type: "number" },
    { id: "skxdef", name: "铁布衫", type: "number" },
    { id: "skxdog", name: "猎犬步伐", type: "number" },
    { id: "skxcta", name: "战斗指挥", type: "number" },
    { id: "skxwms", name: "龙皮术", type: "number" },
    { id: "skxchg", name: "野蛮冲撞", type: "number" },
    { id: "skxtst", name: "霜冻踏地", type: "number" },
    { id: "skhhelwlok", name: "治愈术", type: "number" },
    { id: "skhgsdwlok", name: "幽灵盾", type: "number" },
    { id: "skhinvwlok", name: "隐身术", type: "number" },
    { id: "skhhsdwlok", name: "神圣战甲术", type: "number" },
    { id: "skhlokwlok", name: "困魔咒", type: "number" },
    { id: "skhmhlwlok", name: "群体治愈术", type: "number" },
    { id: "skhhel", name: "治愈术", type: "number" },
    { id: "skhgsd", name: "幽灵盾", type: "number" },
    { id: "skhinv", name: "隐身术", type: "number" },
    { id: "skhhsd", name: "神圣战甲术", type: "number" },
    { id: "skhlok", name: "困魔咒", type: "number" },
    { id: "skhmhl", name: "群体治愈术", type: "number" },
    { id: "skpbaswlok", name: "精神力战法", type: "number" },
    { id: "skppoiwlok", name: "施毒术", type: "number" },
    { id: "skpsklwlok", name: "召唤骷髅", type: "number" },
    { id: "skprunwlok", name: "灵魂火符", type: "number" },
    { id: "skpcblwlok", name: "降魔剑术", type: "number" },
    { id: "skpsdmwlok", name: "召唤神兽", type: "number" },
    { id: "skpbas", name: "精神力战法", type: "number" },
    { id: "skppoi", name: "施毒术", type: "number" },
    { id: "skpskl", name: "召唤骷髅", type: "number" },
    { id: "skprun", name: "灵魂火符", type: "number" },
    { id: "skpcbl", name: "降魔剑术", type: "number" },
    { id: "skpsdm", name: "召唤神兽", type: "number" },
]
