export const Stats = [
    { id: "rthp", name: "生命", type: "number", format: "int", depends: ["rtmaxhp"], derived: (d) => (d.setStat("rthp", Math.min(d.getStat("rtmaxhp"), d.getStat("rthp")))) },
    { id: "rtmaxhp", name: "生命上限", type: "number", format: "int", depends: ["maxhp", "mhex"], derived: (d) => (d.setStat("rtmaxhp", Math.floor(d.getStat("maxhp") * (1 + d.getStat("mhex") / 100)))) },
    { id: "maxhp", name: "基础生命上限", type: "number", format: "int" },
    { id: "mhex", name: "生命上限", type: "number", format: "percent" },
    { id: "rtmp", name: "魔法值", type: "number", format: "int", depends: ["rtmaxmp"], derived: (d) => (d.setStat("rtmp", Math.min(d.getStat("rtmaxmp"), d.getStat("rtmp")))) },
    { id: "rtmaxmp", name: "魔法上限", type: "number", format: "int", depends: ["maxmp", "mpex"], derived: (d) => (d.setStat("rtmaxmp", Math.floor(d.getStat("maxmp") * (1 + d.getStat("mpex") / 100)))) },
    { id: "maxmp", name: "基础魔法上限", type: "number", format: "int" },
    { id: "mpex", name: "魔法上限", type: "number", format: "percent" },
    { id: "hreg", name: "恢复生命", type: "number", format: "int" },
    { id: "mreg", name: "恢复魔法", type: "number", format: "int" },
    { id: "exp", name: "经验值", type: "number", format: "int" },
    { id: "xdr", name: "物理减免", type: "range", format: "int" },
    { id: "fdr", name: "火焰减免", type: "range", format: "int" },
    { id: "tdr", name: "风雷减免", type: "range", format: "int" },
    { id: "hdr", name: "神圣减免", type: "range", format: "int" },
    { id: "pdr", name: "毒素减免", type: "range", format: "int" },
    { id: "xres", name: "基础物理抗性", type: "number", format: "percent" },
    { id: "fres", name: "基础火焰抗性", type: "number", format: "percent" },
    { id: "tres", name: "基础风雷抗性", type: "number", format: "percent" },
    { id: "hres", name: "基础神圣抗性", type: "number", format: "percent" },
    { id: "pres", name: "基础毒素抗性", type: "number", format: "percent" },
    { id: "mxxres", name: "最大物理抗性", type: "number", format: "percent" },
    { id: "mxfres", name: "最大火焰抗性", type: "number", format: "percent" },
    { id: "mxtres", name: "最大风雷抗性", type: "number", format: "percent" },
    { id: "mxhres", name: "最大神圣抗性", type: "number", format: "percent" },
    { id: "mxpres", name: "最大毒素抗性", type: "number", format: "percent" },
    { id: "rtxres", name: "物理抗性", type: "number", format: "percent", depends: ["xres", "mxxres"], derived: (d) => (d.setStat("rtxres", Math.min(75 + d.getStat("mxxres"), d.getStat("xres")))) },
    { id: "rtfres", name: "火焰抗性", type: "number", format: "percent", depends: ["fres", "mxfres"], derived: (d) => (d.setStat("rtfres", Math.min(75 + d.getStat("mxfres"), d.getStat("fres")))) },
    { id: "rttres", name: "风雷抗性", type: "number", format: "percent", depends: ["tres", "mxtres"], derived: (d) => (d.setStat("rttres", Math.min(75 + d.getStat("mxtres"), d.getStat("tres")))) },
    { id: "rthres", name: "神圣抗性", type: "number", format: "percent", depends: ["hres", "mxhres"], derived: (d) => (d.setStat("rthres", Math.min(75 + d.getStat("mxhres"), d.getStat("hres")))) },
    { id: "rtpres", name: "毒素抗性", type: "number", format: "percent", depends: ["pres", "mxpres"], derived: (d) => (d.setStat("rtpres", Math.min(75 + d.getStat("mxpres"), d.getStat("pres")))) },
    { id: "ures", name: "对不死减伤", type: "number", cgroup: "undead/demon", format: "percent" },
    { id: "dres", name: "对妖魔减伤", type: "number", cgroup: "undead/demon", format: "percent" },
    { id: "cres", name: "对精英减伤", type: "number", cgroup: "elite", format: "percent" },
    { id: "c1res", name: "对第一列敌人减伤", type: "number", cgroup: "formation", format: "percent" },
    { id: "c23res", name: "对第二三列敌人减伤", type: "number", cgroup: "formation", format: "percent" },
    { id: "dotres", name: "对持续性效果减伤", type: "number", cgroup: "dot", format: "percent" },
    { id: "sumres", name: "你的召唤物减伤", type: "number", format: "percent" },
    { id: "curs", name: "诅咒", type: "number", format: "int" },
    { id: "bles", name: "祝福", type: "number", format: "int" },
    { id: "luck", name: "幸运", type: "number", format: "percent" },
    { id: "eg", name: "获得金币", type: "number", format: "percent" },
    { id: "spd", name: "速度", type: "number", format: "int" },
    { id: "moral", name: "士气", type: "number", format: "int" },
    { id: "doge", name: "闪避", type: "number", format: "percent" },
    { id: "mdoge", name: "法术闪避", type: "number", format: "percent" },
    { id: "hit", name: "准确", type: "number", format: "percent" },
    { id: "mhit", name: "法术准确", type: "number", format: "percent" },
    { id: "crit", name: "暴击几率", type: "number", format: "percent" },
    { id: "critd", name: "暴击伤害", type: "number", format: "percent" },
    { id: "scrit", name: "法术暴击几率", type: "number", format: "percent" },
    { id: "scritd", name: "法术暴击伤害", type: "number", format: "percent" },
    { id: "str", name: "力量", type: "number", format: "int" },
    { id: "int", name: "魔力", type: "number", format: "int" },
    { id: "spi", name: "道术", type: "number", format: "int" },
    { id: "vit", name: "体力", type: "number", format: "int" },
    { id: "xdmg", name: "物理伤害", type: "range", format: "int" },
    { id: "fdmg", name: "火焰伤害", type: "range", format: "int" },
    { id: "tdmg", name: "风雷伤害", type: "range", format: "int" },
    { id: "hdmg", name: "神圣伤害", type: "range", format: "int" },
    { id: "pdmg", name: "毒素伤害", type: "range", format: "int" },
    { id: "xed", name: "物理增伤", type: "number", format: "percent" },
    { id: "fed", name: "火焰增伤", type: "number", format: "percent" },
    { id: "ted", name: "风雷增伤", type: "number", format: "percent" },
    { id: "hed", name: "神圣增伤", type: "number", format: "percent" },
    { id: "ped", name: "毒素增伤", type: "number", format: "percent" },
    { id: "ued", name: "对不死增伤", type: "number", format: "percent" },
    { id: "ded", name: "对妖魔增伤", type: "number", format: "percent" },
    { id: "ced", name: "对精英增伤", type: "number", format: "percent" },
    { id: "doted", name: "持续性效果增伤", type: "number", format: "percent" },
    { id: "hled", name: "治疗增强", type: "number", format: "percent" },
    { id: "col1ed", name: "对第一列增伤", type: "number", format: "percent" },
    { id: "col23ed", name: "对第二三列增伤", type: "number", format: "percent" },
    { id: "sumed", name: "召唤物增伤", type: "number", format: "percent" },
    { id: "flvl", name: "火焰系技能等级", type: "number", format: "int" },
    { id: "tlvl", name: "风雷系技能等级", type: "number", format: "int" },
    { id: "flvlmage", name: "火焰系技能等级", type: "number", format: "int" },
    { id: "tlvlmage", name: "风雷系技能等级", type: "number", format: "int" },
    { id: "magelvl", name: "魔法师技能等级", type: "number", format: "int" },
    { id: "blvl", name: "战术系技能等级", type: "number", format: "int" },
    { id: "xlvl", name: "体术系技能等级", type: "number", format: "int" },
    { id: "blvlwarr", name: "战术系技能等级", type: "number", format: "int" },
    { id: "xlvlwarr", name: "体术系技能等级", type: "number", format: "int" },
    { id: "warrlvl", name: "武士技能等级", type: "number", format: "int" },
    { id: "hlvl", name: "神圣系技能等级", type: "number", format: "int" },
    { id: "plvl", name: "道法系技能等级", type: "number", format: "int" },
    { id: "hlvlwlok", name: "神圣系技能等级", type: "number", format: "int" },
    { id: "plvlwlok", name: "道法系技能等级", type: "number", format: "int" },
    { id: "wlklvl", name: "道士技能等级", type: "number", format: "int" },
    { id: "alvl", name: "所有技能等级", type: "number", format: "int" },
    { id: "slvl", name: "召唤系技能等级", type: "number", format: "int" },
    { id: "glvl", name: "防护系技能等级", type: "number", format: "int" },
    { id: "cate", name: "分类", type: "set", format: "int" },
    { id: "cb", name: "粉碎性打击", type: "number", format: "percent" },
    { id: "pmh", name: "敌人治疗效果降低", type: "number", format: "percent" },
    { id: "xref", name: "反弹物理伤害", type: "number", format: "int" },
    { id: "fref", name: "反弹火焰伤害", type: "number", format: "int" },
    { id: "tref", name: "反弹风雷伤害", type: "number", format: "int" },
    { id: "href", name: "反弹神圣伤害", type: "number", format: "int" },
    { id: "pref", name: "反弹毒素伤害", type: "number", format: "int" },
    { id: "ll", name: "近战吸血", type: "number", format: "percent" },
    { id: "ml", name: "近战吸魔", type: "number", format: "percent" },
    { id: "sumreg", name: "召唤物恢复生命", type: "number", format: "int" },
    { id: "xlr", name: "降低物理抗性", type: "number", format: "percent" },
    { id: "flr", name: "降低火焰抗性", type: "number", format: "percent" },
    { id: "tlr", name: "降低风雷抗性", type: "number", format: "percent" },
    { id: "hlr", name: "降低神圣抗性", type: "number", format: "percent" },
    { id: "plr", name: "降低毒素抗性", type: "number", format: "percent" },
    { id: "skfbltmage", name: "火球术(限法师)", type: "number", format: "int" },
    { id: "skfrngmage", name: "抗拒火环(限法师)", type: "number", format: "int" },
    { id: "skfinfmage", name: "地狱火(限法师)", type: "number", format: "int" },
    { id: "skfbalmage", name: "大火球(限法师)", type: "number", format: "int" },
    { id: "skfblsmage", name: "爆裂火焰(限法师)", type: "number", format: "int" },
    { id: "skfwalmage", name: "火墙术(限法师)", type: "number", format: "int" },
    { id: "skfblt", name: "火球术", type: "number", format: "int" },
    { id: "skfrng", name: "抗拒火环", type: "number", format: "int" },
    { id: "skfinf", name: "地狱火", type: "number", format: "int" },
    { id: "skfbal", name: "大火球", type: "number", format: "int" },
    { id: "skfbls", name: "爆裂火焰", type: "number", format: "int" },
    { id: "skfwal", name: "火墙术", type: "number", format: "int" },
    { id: "sktchmmage", name: "诱惑之光(限法师)", type: "number", format: "int" },
    { id: "sktbltmage", name: "雷电术(限法师)", type: "number", format: "int" },
    { id: "sktltnmage", name: "疾光电影(限法师)", type: "number", format: "int" },
    { id: "sktnovmage", name: "地狱雷光(限法师)", type: "number", format: "int" },
    { id: "sktshdmage", name: "魔法盾(限法师)", type: "number", format: "int" },
    { id: "sktblzmage", name: "冰咆哮(限法师)", type: "number", format: "int" },
    { id: "sktchm", name: "诱惑之光", type: "number", format: "int" },
    { id: "sktblt", name: "雷电术", type: "number", format: "int" },
    { id: "sktltn", name: "疾光电影", type: "number", format: "int" },
    { id: "sktnov", name: "地狱雷光", type: "number", format: "int" },
    { id: "sktshd", name: "魔法盾", type: "number", format: "int" },
    { id: "sktblz", name: "冰咆哮", type: "number", format: "int" },
    { id: "skbbaswarr", name: "基础剑术(限战士)", type: "number", format: "int" },
    { id: "skbcrtwarr", name: "攻杀剑术(限战士)", type: "number", format: "int" },
    { id: "skbthrwarr", name: "刺杀剑术(限战士)", type: "number", format: "int" },
    { id: "skbclvwarr", name: "半月弯刀(限战士)", type: "number", format: "int" },
    { id: "skbcrzwarr", name: "十字斩(限战士)", type: "number", format: "int" },
    { id: "skbfblwarr", name: "烈火剑法(限战士)", type: "number", format: "int" },
    { id: "skbbas", name: "基础剑术", type: "number", format: "int" },
    { id: "skbcrt", name: "攻杀剑术", type: "number", format: "int" },
    { id: "skbthr", name: "刺杀剑术", type: "number", format: "int" },
    { id: "skbclv", name: "半月弯刀", type: "number", format: "int" },
    { id: "skbcrz", name: "十字斩", type: "number", format: "int" },
    { id: "skbfbl", name: "烈火剑法", type: "number", format: "int" },
    { id: "skxdefwarr", name: "铁布衫(限战士)", type: "number", format: "int" },
    { id: "skxdogwarr", name: "猎犬步伐(限战士)", type: "number", format: "int" },
    { id: "skxctawarr", name: "战斗指挥(限战士)", type: "number", format: "int" },
    { id: "skxwmswarr", name: "龙皮术(限战士)", type: "number", format: "int" },
    { id: "skxchgwarr", name: "野蛮冲撞(限战士)", type: "number", format: "int" },
    { id: "skxtstwarr", name: "霜冻踏地(限战士)", type: "number", format: "int" },
    { id: "skxdef", name: "铁布衫", type: "number", format: "int" },
    { id: "skxdog", name: "猎犬步伐", type: "number", format: "int" },
    { id: "skxcta", name: "战斗指挥", type: "number", format: "int" },
    { id: "skxwms", name: "龙皮术", type: "number", format: "int" },
    { id: "skxchg", name: "野蛮冲撞", type: "number", format: "int" },
    { id: "skxtst", name: "霜冻踏地", type: "number", format: "int" },
    { id: "skhhelwlok", name: "治愈术(限道士)", type: "number", format: "int" },
    { id: "skhgsdwlok", name: "幽灵盾(限道士)", type: "number", format: "int" },
    { id: "skhinvwlok", name: "隐身术(限道士)", type: "number", format: "int" },
    { id: "skhhsdwlok", name: "神圣战甲术(限道士)", type: "number", format: "int" },
    { id: "skhlokwlok", name: "困魔咒(限道士)", type: "number", format: "int" },
    { id: "skhmhlwlok", name: "群体治愈术(限道士)", type: "number", format: "int" },
    { id: "skhhel", name: "治愈术", type: "number", format: "int" },
    { id: "skhgsd", name: "幽灵盾", type: "number", format: "int" },
    { id: "skhinv", name: "隐身术", type: "number", format: "int" },
    { id: "skhhsd", name: "神圣战甲术", type: "number", format: "int" },
    { id: "skhlok", name: "困魔咒", type: "number", format: "int" },
    { id: "skhmhl", name: "群体治愈术", type: "number", format: "int" },
    { id: "skpbaswlok", name: "精神力战法(限道士)", type: "number", format: "int" },
    { id: "skppoiwlok", name: "施毒术(限道士)", type: "number", format: "int" },
    { id: "skpsklwlok", name: "召唤骷髅(限道士)", type: "number", format: "int" },
    { id: "skprunwlok", name: "灵魂火符(限道士)", type: "number", format: "int" },
    { id: "skpcblwlok", name: "降魔剑术(限道士)", type: "number", format: "int" },
    { id: "skpsdmwlok", name: "召唤神兽(限道士)", type: "number", format: "int" },
    { id: "skpbas", name: "精神力战法", type: "number", format: "int" },
    { id: "skppoi", name: "施毒术", type: "number", format: "int" },
    { id: "skpskl", name: "召唤骷髅", type: "number", format: "int" },
    { id: "skprun", name: "灵魂火符", type: "number", format: "int" },
    { id: "skpcbl", name: "降魔剑术", type: "number", format: "int" },
    { id: "skpsdm", name: "召唤神兽", type: "number", format: "int" },
    { id: "setwargod", name: "战神套装", type: "number", format: "int" },
    { id: "setmara", name: "天魔套装", type: "number", format: "int" },
    { id: "setjihad", name: "圣战套装", type: "number", format: "int" },
    { id: "setghost", name: "幽灵套装", type: "number", format: "int" },
    { id: "setvenerable", name: "天尊套装", type: "number", format: "int" },
    { id: "setmaster", name: "天师套装", type: "number", format: "int" },
    { id: "setdemon", name: "恶魔套装", type: "number", format: "int" },
    { id: "setmagegod", name: "法神套装", type: "number", format: "int" },
    { id: "setcolorful", name: "霓裳套装", type: "number", format: "int" },
    { id: "setblackiron", name: "黑铁套装", type: "number", format: "int" },
    { id: "setmysterious", name: "神秘套装", type: "number", format: "int" },
    { id: "setmemory", name: "记忆套装", type: "number", format: "int" },
    { id: "setvoma", name: "沃玛套装", type: "number", format: "int" },
    { id: "setzuma", name: "祖玛套装", type: "number", format: "int" },
    { id: "setredmoon", name: "赤月套装", type: "number", format: "int" },
    { id: "setprisma", name: "虹魔套装", type: "number", format: "int" },
    { id: "setdragon", name: "龙之套装", type: "number", format: "int" },
    { id: "setempire", name: "帝国套装", type: "number", format: "int" },
    { id: "sok", name: "插槽数量", type: "number", format: "int" },
    { id: "rw", name: "允许符文之语", type: "number", format: "int" },
    { id: "silent", name: "无法攻击", type: "number", format: "int" },
    { id: "stun", name: "昏迷", type: "number", format: "int" },
    { id: "prochit", name: "被击触发", type: "skillList", description: "被攻击时，有{0}%概率施展等级{1}的{2}", format: "int" },
    { id: "procatk", name: "攻击触发", type: "skillList", description: "攻击时，有{0}%概率施展等级{1}的{2}", format: "int" },
    { id: "skpts", name: "技能点数", type: "number", format: "int" },
];

export const StatById = Object.fromEntries(Stats.map(e => [e.id, e]));
