export const Stat = [
    { id: 1, iden: "hp", name: "生命值", type: "number", description: "Hero1 Description" },
    { id: 2, iden: "maxhp", name: "生命上限", type: "number", description: "Hero1 Description" },
    { id: 3, iden: "exp", name: "经验值", type: "number", description: "Hero1 Description" },

    { id: 10, iden: "mp", name: "魔法值", type: "number", description: "Hero1 Description" },
    { id: 11, iden: "maxmp", name: "魔法上限", type: "number", description: "Hero1 Description" },
    { id: 12, iden: "hreg", name: "恢复生命", type: "number", description: "Hero1 Description" },
    { id: 13, iden: "mreg", name: "恢复魔法", type: "number", description: "Hero1 Description" },
    { id: 14, iden: "mhex", name: "生命上限", type: "number", description: "Hero1 Description" },
    { id: 15, iden: "mpex", name: "魔法上限", type: "number", description: "Hero1 Description" },

    { id: 20, iden: "dr", name: "物理减免", type: "range", description: "Hero1 Description" },
    { id: 21, iden: "fdr", name: "火焰减免", type: "range", description: "Hero1 Description" },
    { id: 22, iden: "tdr", name: "风雷减免", type: "range", description: "Hero1 Description" },
    { id: 23, iden: "hdr", name: "神圣减免", type: "range", description: "Hero1 Description" },
    { id: 24, iden: "pdr", name: "毒素减免", type: "range", description: "Hero1 Description" },

    { id: 30, iden: "res", name: "物理抗性", type: "number", description: "Hero1 Description" },
    { id: 31, iden: "fres", name: "火焰抗性", type: "number", description: "Hero1 Description" },
    { id: 32, iden: "tres", name: "风雷抗性", type: "number", description: "Hero1 Description" },
    { id: 33, iden: "hres", name: "神圣抗性", type: "number", description: "Hero1 Description" },
    { id: 34, iden: "pres", name: "毒素抗性", type: "number", description: "Hero1 Description" },
    { id: 35, iden: "ures", name: "对不死抗性", type: "number", description: "Hero1 Description" },
    { id: 36, iden: "dres", name: "对妖魔抗性", type: "number", description: "Hero1 Description" },
    { id: 37, iden: "mres", name: "对近战抗性", type: "number", description: "Hero1 Description" },
    { id: 38, iden: "rres", name: "对远程抗性", type: "number", description: "Hero1 Description" },
    { id: 39, iden: "cres", name: "对精英抗性", type: "number", description: "Hero1 Description" },

    { id: 50, iden: "curs", name: "诅咒", type: "number", description: "Hero1 Description" },
    { id: 51, iden: "bles", name: "祝福", type: "number", description: "Hero1 Description" },
    { id: 52, iden: "luck", name: "幸运", type: "number", description: "Hero1 Description" },
    { id: 53, iden: "eg", name: "获得金币", type: "number", description: "Hero1 Description" },

    { id: 60, iden: "spd", name: "速度", type: "number", description: "Hero1 Description" },
    { id: 61, iden: "doge", name: "闪避", type: "number", description: "Hero1 Description" },
    { id: 62, iden: "mdoge", name: "法术闪避", type: "number", description: "Hero1 Description" },
    
    { id: 70, iden: "mxxres", name: "最大物理抗性", type: "number", description: "Hero1 Description" },
    { id: 71, iden: "mxfres", name: "最大火焰抗性", type: "number", description: "Hero1 Description" },
    { id: 72, iden: "mxtres", name: "最大风雷抗性", type: "number", description: "Hero1 Description" },
    { id: 73, iden: "mxhres", name: "最大神圣抗性", type: "number", description: "Hero1 Description" },
    { id: 74, iden: "mxpres", name: "最大毒素抗性", type: "number", description: "Hero1 Description" },

    { id: 100, iden: "atk", name: "攻击", type: "range", description: "Hero1 Description" },
    { id: 101, iden: "hit", name: "准确", type: "number", description: "Hero1 Description" },
    { id: 110, iden: "matk", name: "魔法", type: "range", description: "Hero1 Description" },
    { id: 120, iden: "watk", name: "道术", type: "range", description: "Hero1 Description" },

    { id: 130, iden: "ed", name: "物理增伤", type: "number", description: "Hero1 Description" },
    { id: 131, iden: "fed", name: "火焰增伤", type: "number", description: "Hero1 Description" },
    { id: 132, iden: "ted", name: "风雷增伤", type: "number", description: "Hero1 Description" },
    { id: 133, iden: "hed", name: "神圣增伤", type: "number", description: "Hero1 Description" },
    { id: 134, iden: "ped", name: "毒素增伤", type: "number", description: "Hero1 Description" },
    { id: 135, iden: "ued", name: "对不死增伤", type: "number", description: "Hero1 Description" },
    { id: 136, iden: "ded", name: "对妖魔增伤", type: "number", description: "Hero1 Description" },
    { id: 137, iden: "med", name: "对近战增伤", type: "number", description: "Hero1 Description" },
    { id: 138, iden: "red", name: "对远程增伤", type: "number", description: "Hero1 Description" },
    { id: 139, iden: "ced", name: "对精英增伤", type: "number", description: "Hero1 Description" },

    { id: 150, iden: "doted", name: "持续性效果增伤", type: "number", description: "Hero1 Description" },
    { id: 151, iden: "hled", name: "治疗增强", type: "number", description: "Hero1 Description" },

    // { id: 140, iden: "", name: "物理攻击", type: "range", description: "Hero1 Description" },
    // { id: 141, iden: "", name: "火焰攻击", type: "range", description: "Hero1 Description" },
    // { id: 142, iden: "", name: "风雷攻击", type: "range", description: "Hero1 Description" },
    // { id: 143, iden: "", name: "神圣攻击", type: "range", description: "Hero1 Description" },
    // { id: 144, iden: "", name: "毒素攻击", type: "range", description: "Hero1 Description" },
    { id: 200, iden: "flvl", name: "火焰系技能等级", type: "number", description: "Hero1 Description" },
    { id: 201, iden: "tlvl", name: "风雷系技能等级", type: "number", description: "Hero1 Description" },
    { id: 202, iden: "magelvl", name: "魔法师技能等级", type: "number", description: "Hero1 Description" },
    { id: 203, iden: "blvl", name: "战术系技能等级", type: "number", description: "Hero1 Description" },
    { id: 204, iden: "xlvl", name: "体术系技能等级", type: "number", description: "Hero1 Description" },
    { id: 205, iden: "warrlvl", name: "武士技能等级", type: "number", description: "Hero1 Description" },
    { id: 206, iden: "hlvl", name: "神圣系技能等级", type: "number", description: "Hero1 Description" },
    { id: 207, iden: "plvl", name: "道法系技能等级", type: "number", description: "Hero1 Description" },
    { id: 208, iden: "wlklvl", name: "道士技能等级", type: "number", description: "Hero1 Description" },
    { id: 209, iden: "alvl", name: "所有技能等级", type: "number", description: "Hero1 Description" },
    { id: 210, iden: "slvl", name: "召唤系技能等级", type: "number", description: "Hero1 Description" },
    { id: 211, iden: "glvl", name: "防护系技能等级", type: "number", description: "Hero1 Description" },

    { id: 300, iden: "cate", name: "分类", type: "list", description: "Hero1 Description" },
    { id: 301, iden: "cb", name: "粉碎性打击", type: "number", description: "Hero1 Description" },
    { id: 302, iden: "ow", name: "撕裂伤口", type: "number", description: "Hero1 Description" },
    { id: 303, iden: "ref", name: "反弹伤害", type: "number", description: "Hero1 Description" },
    { id: 304, iden: "ll", name: "近战吸血", type: "number", description: "Hero1 Description" },
    { id: 305, iden: "ml", name: "近战吸魔", type: "number", description: "Hero1 Description" },

    { id: 400, iden: "lr", name: "降低物理抗性", type: "number", description: "Hero1 Description" },
    { id: 401, iden: "flr", name: "降低火焰抗性", type: "number", description: "Hero1 Description" },
    { id: 402, iden: "tlr", name: "降低风雷抗性", type: "number", description: "Hero1 Description" },
    { id: 403, iden: "hlr", name: "降低神圣抗性", type: "number", description: "Hero1 Description" },
    { id: 404, iden: "plr", name: "降低毒素抗性", type: "number", description: "Hero1 Description" },

    { id: 500, iden: "skfbltmage", name: "火球术(限魔法师)", type: "number", description: "Hero1 Description" },
    { id: 501, iden: "skfrngmage", name: "抗拒火环(限魔法师)", type: "number", description: "Hero1 Description" },
    { id: 502, iden: "skfinfmage", name: "地狱火(限魔法师)", type: "number", description: "Hero1 Description" },
    { id: 503, iden: "skfbalmage", name: "大火球(限魔法师)", type: "number", description: "Hero1 Description" },
    { id: 504, iden: "skfblsmage", name: "爆裂火焰(限魔法师)", type: "number", description: "Hero1 Description" },
    { id: 505, iden: "skfwalmage", name: "火墙术(限魔法师)", type: "number", description: "Hero1 Description" },
    { id: 510, iden: "skfblt", name: "火球术", type: "number", description: "Hero1 Description" },
    { id: 511, iden: "skfrng", name: "抗拒火环", type: "number", description: "Hero1 Description" },
    { id: 512, iden: "skfinf", name: "地狱火", type: "number", description: "Hero1 Description" },
    { id: 513, iden: "skfbal", name: "大火球", type: "number", description: "Hero1 Description" },
    { id: 514, iden: "skfbls", name: "爆裂火焰", type: "number", description: "Hero1 Description" },
    { id: 515, iden: "skfwal", name: "火墙术", type: "number", description: "Hero1 Description" },

    { id: 600, iden: "sktchmmage", name: "诱惑之光(限魔法师)", type: "number", description: "Hero1 Description" },
    { id: 601, iden: "sktbltmage", name: "雷电术(限魔法师)", type: "number", description: "Hero1 Description" },
    { id: 602, iden: "sktltnmage", name: "疾光电影(限魔法师)", type: "number", description: "Hero1 Description" },
    { id: 603, iden: "sktnovmage", name: "地狱雷光(限魔法师)", type: "number", description: "Hero1 Description" },
    { id: 604, iden: "sktshdmage", name: "魔法盾(限魔法师)", type: "number", description: "Hero1 Description" },
    { id: 605, iden: "sktblzmage", name: "冰咆哮(限魔法师)", type: "number", description: "Hero1 Description" },
    { id: 610, iden: "sktchm", name: "诱惑之光", type: "number", description: "Hero1 Description" },
    { id: 611, iden: "sktblt", name: "雷电术", type: "number", description: "Hero1 Description" },
    { id: 612, iden: "sktltn", name: "疾光电影", type: "number", description: "Hero1 Description" },
    { id: 613, iden: "sktnov", name: "地狱雷光", type: "number", description: "Hero1 Description" },
    { id: 614, iden: "sktshd", name: "魔法盾", type: "number", description: "Hero1 Description" },
    { id: 615, iden: "sktblz", name: "冰咆哮", type: "number", description: "Hero1 Description" },

    { id: 700, iden: "skbbaswarr", name: "基础剑术(限武士)", type: "number", description: "Hero1 Description" },
    { id: 701, iden: "skbcrtwarr", name: "攻杀剑术(限武士)", type: "number", description: "Hero1 Description" },
    { id: 702, iden: "skbthrwarr", name: "刺杀剑术(限武士)", type: "number", description: "Hero1 Description" },
    { id: 703, iden: "skbclvwarr", name: "半月弯刀(限武士)", type: "number", description: "Hero1 Description" },
    { id: 704, iden: "skbcrzwarr", name: "十字斩(限武士)", type: "number", description: "Hero1 Description" },
    { id: 705, iden: "skbfblwarr", name: "烈火剑法(限武士)", type: "number", description: "Hero1 Description" },
    { id: 710, iden: "skbbas", name: "基础剑术", type: "number", description: "Hero1 Description" },
    { id: 711, iden: "skbcrt", name: "攻杀剑术", type: "number", description: "Hero1 Description" },
    { id: 712, iden: "skbthr", name: "刺杀剑术", type: "number", description: "Hero1 Description" },
    { id: 713, iden: "skbclv", name: "半月弯刀", type: "number", description: "Hero1 Description" },
    { id: 714, iden: "skbcrz", name: "十字斩", type: "number", description: "Hero1 Description" },
    { id: 715, iden: "skbfbl", name: "烈火剑法", type: "number", description: "Hero1 Description" },

    { id: 800, iden: "skxdefwarr", name: "铁布衫(限武士)", type: "number", description: "Hero1 Description" },
    { id: 801, iden: "skxdogwarr", name: "猎犬步伐(限武士)", type: "number", description: "Hero1 Description" },
    { id: 802, iden: "skxctawarr", name: "战斗指挥(限武士)", type: "number", description: "Hero1 Description" },
    { id: 803, iden: "skxwmswarr", name: "龙皮术(限武士)", type: "number", description: "Hero1 Description" },
    { id: 804, iden: "skxchgwarr", name: "野蛮冲撞(限武士)", type: "number", description: "Hero1 Description" },
    { id: 805, iden: "skxtstwarr", name: "霜冻踏地(限武士)", type: "number", description: "Hero1 Description" },
    { id: 810, iden: "skxdef", name: "铁布衫", type: "number", description: "Hero1 Description" },
    { id: 811, iden: "skxdog", name: "猎犬步伐", type: "number", description: "Hero1 Description" },
    { id: 812, iden: "skxcta", name: "战斗指挥", type: "number", description: "Hero1 Description" },
    { id: 813, iden: "skxwms", name: "龙皮术", type: "number", description: "Hero1 Description" },
    { id: 814, iden: "skxchg", name: "野蛮冲撞", type: "number", description: "Hero1 Description" },
    { id: 815, iden: "skxtst", name: "霜冻踏地", type: "number", description: "Hero1 Description" },

    { id: 900, iden: "skhhelwlok", name: "治愈术(限道士)", type: "number", description: "Hero1 Description" },
    { id: 901, iden: "skhgsdwlok", name: "幽灵盾(限道士)", type: "number", description: "Hero1 Description" },
    { id: 902, iden: "skhinvwlok", name: "隐身术(限道士)", type: "number", description: "Hero1 Description" },
    { id: 903, iden: "skhhsdwlok", name: "神圣战甲术(限道士)", type: "number", description: "Hero1 Description" },
    { id: 904, iden: "skhlokwlok", name: "困魔咒(限道士)", type: "number", description: "Hero1 Description" },
    { id: 905, iden: "skhmhlwlok", name: "群体治愈术(限道士)", type: "number", description: "Hero1 Description" },
    { id: 910, iden: "skhhel", name: "治愈术", type: "number", description: "Hero1 Description" },
    { id: 911, iden: "skhgsd", name: "幽灵盾", type: "number", description: "Hero1 Description" },
    { id: 912, iden: "skhinv", name: "隐身术", type: "number", description: "Hero1 Description" },
    { id: 913, iden: "skhhsd", name: "神圣战甲术", type: "number", description: "Hero1 Description" },
    { id: 914, iden: "skhlok", name: "困魔咒", type: "number", description: "Hero1 Description" },
    { id: 915, iden: "skhmhl", name: "群体治愈术", type: "number", description: "Hero1 Description" },

    { id: 1000, iden: "skpbaswlok", name: "精神力战法(限道士)", type: "number", description: "Hero1 Description" },
    { id: 1001, iden: "skppoiwlok", name: "施毒术(限道士)", type: "number", description: "Hero1 Description" },
    { id: 1002, iden: "skpsklwlok", name: "召唤骷髅(限道士)", type: "number", description: "Hero1 Description" },
    { id: 1003, iden: "skprunwlok", name: "灵魂火符(限道士)", type: "number", description: "Hero1 Description" },
    { id: 1004, iden: "skpcblwlok", name: "降魔剑术(限道士)", type: "number", description: "Hero1 Description" },
    { id: 1005, iden: "skpsdmwlok", name: "召唤神兽(限道士)", type: "number", description: "Hero1 Description" },
    { id: 1010, iden: "skpbas", name: "精神力战法", type: "number", description: "Hero1 Description" },
    { id: 1011, iden: "skppoi", name: "施毒术", type: "number", description: "Hero1 Description" },
    { id: 1012, iden: "skpskl", name: "召唤骷髅", type: "number", description: "Hero1 Description" },
    { id: 1013, iden: "skprun", name: "灵魂火符", type: "number", description: "Hero1 Description" },
    { id: 1014, iden: "skpcbl", name: "降魔剑术", type: "number", description: "Hero1 Description" },
    { id: 1015, iden: "skpsdm", name: "召唤神兽", type: "number", description: "Hero1 Description" },
]

/** @type {Record<number, ElementTypeOf<Stat>>}*/
export const StatById = {};
for (const e of Stat) {
    StatById[e.id] = e;
}
